// frameworks/angular/primitives/stat-card/stat-card.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { statCardStyles } from './stat-card.variants';

type Tone = 'neutral' | 'accent' | 'gold' | 'success' | 'warning' | 'danger' | 'info';
type DeltaTone = 'neutral' | 'positive' | 'negative';
type Direction = 'up' | 'down';

/** One metric on a dashboard: a micro-label, the number, and an optional delta pill.
 *  `tone` and `deltaTone` answer different questions about the same number. `tone`
 *  says what state the number IS in right now — a service at 99.98% uptime is
 *  healthy whether or not it improved this week, and two open incidents are two
 *  open incidents even when that is down from five. `deltaTone` says whether the
 *  change it just made was good; `deltaDirection` says which way it pointed. Both
 *  are separate inputs because they are separate facts, and every delta sign
 *  renders as an outline pill, never filled. The host itself is the recipe's
 *  `root` — it is the flex item a parent row lays out, so root-level classes must
 *  live on the host, not one element inside it. */
@Component({
  selector: 'arena-stat-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    <div [class]="styles().head()">
      <span [class]="styles().label()">{{ label() }}</span>
      @if (icon(); as glyph) {
        <span [class]="styles().icon()" aria-hidden="true"><i [class]="glyph"></i></span>
      }
    </div>
    <div [class]="styles().value()">{{ value() }}</div>
    @if (deltaValue(); as delta) {
      <span [class]="styles().delta()">
        <i [class]="deltaDirection() === 'down' ? 'ph-bold ph-arrow-down' : 'ph-bold ph-arrow-up'" aria-hidden="true"></i>
        {{ delta }}
      </span>
    }
    @if (sub(); as caption) {
      <span [class]="styles().sub()">{{ caption }}</span>
    }
  `,
})
export class StatCard {
  readonly label = input('');
  readonly value = input('');
  readonly tone = input<Tone>('neutral');
  readonly sub = input<string>();
  readonly icon = input<string>();
  readonly deltaValue = input<string>();
  readonly deltaTone = input<DeltaTone>('neutral');
  readonly deltaDirection = input<Direction>('up');

  protected readonly styles = computed(() => statCardStyles({ tone: this.tone(), deltaTone: this.deltaTone() }));
}

// frameworks/react/components/display/stat-card/StatCard.jsx
import React from 'react';

/* The delta pill's color says whether the change is GOOD, not which way it
 * points. Direction and sentiment are separate props because they are separate
 * facts: revenue down is bad, latency down is good, and a component cannot
 * know which metric it is showing. Both signs are outline — filled red belongs
 * to ConfirmDialog's final confirmation and nowhere else. */
const DELTA_TONES = {
  neutral: { border: 'var(--border-strong)', color: 'var(--text-muted)' },
  positive: { border: 'var(--success)', color: 'var(--success)' },
  negative: { border: 'var(--danger)', color: 'var(--danger)' },
};

/* The value's own tone, and it answers a different question from the delta's.
 * `delta.tone` says whether the number MOVED in a good direction; this says
 * what state the number IS in right now. A service at 99.98% uptime is
 * healthy whether or not it improved this week, and two open incidents are
 * two open incidents even when that is down from five. Same distinction the
 * component already draws between direction and sentiment, one level up.
 *
 * The vocabulary is Badge's, deliberately — one set of tone names across the
 * system beats a second set that is nearly the same. Here they are the solid
 * colors rather than the -soft pairs: this tints a glyph, not a surface. */
const VALUE_TONES = {
  neutral: 'var(--bone)',
  accent: 'var(--crimson)',
  gold: 'var(--gold)',
  success: 'var(--success)',
  warning: 'var(--warning)',
  danger: 'var(--danger)',
  info: 'var(--info)',
};

export function StatCard({ label, value, tone = 'neutral', delta, sub, icon }) {
  if (!label || !value) throw new Error('StatCard: `label` and `value` are required');
  const t = delta?.value ? (DELTA_TONES[delta.tone] || DELTA_TONES.neutral) : null;
  const valueColor = VALUE_TONES[tone] || VALUE_TONES.neutral;
  return (
    <div style={{
      background: 'var(--surface-card)', border: 'var(--bw) solid var(--color-base-300)',
      borderRadius: 'var(--r-lg)', padding: 'calc(var(--sp-1) * 5)', minHeight: 'calc(var(--sp-1) * 30)',
      display: 'flex', flexDirection: 'column', gap: 'calc(var(--sp-1) * 2)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'calc(var(--sp-1) * 3)' }}>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-2xs)', letterSpacing: 'var(--ls-label)', textTransform: 'uppercase', color: 'var(--mute)' }}>{label}</span>
        {icon && <span aria-hidden="true" style={{ display: 'inline-flex', fontSize: 'var(--icon-sm)', color: 'var(--mute)', opacity: 0.6 }}><i className={icon} /></span>}
      </div>
      <div style={{
        fontFamily: 'var(--font-display)', fontWeight: 'var(--fw-extrabold)', fontSize: 'var(--fs-h2)', lineHeight: 'var(--lh-snug)',
        color: valueColor, fontVariantNumeric: 'tabular-nums', margin: 0,
      }}>{value}</div>
      {delta?.value && (
        <span style={{
          alignSelf: 'flex-start', display: 'inline-flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 1)',
          borderRadius: 'var(--r-pill)', padding: 'calc(var(--sp-1) * 0.5) calc(var(--sp-1) * 2)',
          fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-sm)', fontWeight: 'var(--fw-semibold)',
          background: 'transparent', border: 'var(--bw) solid ' + t.border, color: t.color,
        }}>
          <i className={delta.direction === 'down' ? 'ph-bold ph-arrow-down' : 'ph-bold ph-arrow-up'} aria-hidden="true" />
          {delta.value}
        </span>
      )}
      {sub && <span style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-sm)', color: 'var(--mute)' }}>{sub}</span>}
    </div>
  );
}
