// frameworks/angular/components/feedback/toast/Toast.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output } from '@angular/core';
import type { ToastTone } from '../../../Api.generated';
import { dismissDefault, dismissActionable } from '../../../Tokens.generated';
import { toastStyles } from './Toast.variants';

export const TOAST_DISMISS = { default: dismissDefault, actionable: dismissActionable } as const;

@Component({
  selector: 'arena-toast',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.role]': "tone() === 'danger' ? 'alert' : 'status'",
    '[attr.aria-live]': "tone() === 'danger' ? 'assertive' : 'polite'",
    '[attr.data-persist]': "pinned() ? '' : null",
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="styles().body()">
      @if (title(); as heading) {
        <div [class]="styles().title()">{{ heading }}@if (pinned()) {
          <span [class]="styles().pinned()" title="Does not auto-dismiss">Pinned</span>
        }</div>
      }
      @if (message(); as text) {
        <div [class]="styles().message()">{{ text }}</div>
      }
      @if (actionLabel(); as label) {
        <button type="button" [class]="styles().action()" (click)="action.emit()">{{ label }}</button>
      }
    </div>
    @if (dismissible()) {
      <button type="button" [class]="styles().close()" aria-label="Close" (click)="close.emit()">
        <i class="ph-bold ph-x" aria-hidden="true"></i>
      </button>
    }
  `,
})
export class Toast {
  /** The bold lead line. */
  readonly title = input<string>();
  /** The body. */
  readonly message = input<string>();
  /** The side bar's colour, and whether the toast announces assertively. */
  readonly tone = input<ToastTone>('neutral');
  /** The label of the single inline action: Undo, Retry, View logs. Absent renders no action. */
  readonly actionLabel = input<string>();
  /** The inline action was activated. */
  readonly action = output<void>();
  /** Disables the host's auto-dismiss and shows the Pinned marker. **Implied by `tone: "danger"`, which ignores `false`**: a critical message that vanishes on a timer is one a user can miss entirely, and this was documented as mandatory in an error state while nothing enforced it. Set it explicitly for any other tone that must not disappear on its own. */
  readonly persist = input(false, { transform: booleanAttribute });
  /** Whether the × is shown. Every layer gates the × on this member and never on whether anything listens for `close`, because Arena never derives what it draws from what a consumer listens for. */
  readonly dismissible = input(false, { transform: booleanAttribute });
  /** The × was activated. */
  readonly close = output<void>();

  protected readonly pinned = computed(() => this.persist() || this.tone() === 'danger');
  protected readonly styles = computed(() => toastStyles({ tone: this.tone() }));
}

// frameworks/react/components/feedback/toast/Toast.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './Toast.classes.generated.ts';

import type { ToastTone } from '../../../Api.generated';
import { dismissDefault, dismissActionable } from '../../../Tokens.generated.js';

export interface ToastProps {

  /** The bold lead line. */
  title?: string;

  /** The body. */
  message?: string;

  /** The side bar's colour, and whether the toast announces assertively. */
  tone?: ToastTone;

  /** The label of the single inline action: Undo, Retry, View logs. Absent renders no action. */
  actionLabel?: string;

  /** The inline action was activated. */
  onAction?: () => void;

  /** Disables the host's auto-dismiss and shows the Pinned marker. **Implied by `tone: "danger"`, which ignores `false`**: a critical message that vanishes on a timer is one a user can miss entirely, and this was documented as mandatory in an error state while nothing enforced it. Set it explicitly for any other tone that must not disappear on its own. */
  persist?: boolean;

  /** Whether the × is shown. Every layer gates the × on this member and never on whether anything listens for `close`, because Arena never derives what it draws from what a consumer listens for. */
  dismissible?: boolean;

  /** The × was activated. */
  onClose?: () => void;
}

export const TOAST_DISMISS = { default: dismissDefault, actionable: dismissActionable } as const;

const toastStyles = arenaStyles(manifest);
const TONES = Object.keys(manifest.variants.tone);
type Tone = keyof typeof manifest.variants.tone;
const toneOf = (tone: string | undefined): Tone =>
  (tone && TONES.includes(tone) ? tone as Tone : 'neutral');

export function Toast({ title, message, tone = 'neutral', actionLabel, onAction, dismissible = false, onClose, persist = false }: ToastProps) {
  const pinned = persist || tone === 'danger';
  const styles = toastStyles({ tone: toneOf(tone) });
  return (
    <div role={tone === 'danger' ? 'alert' : 'status'} aria-live={tone === 'danger' ? 'assertive' : 'polite'}
      data-persist={pinned ? '' : undefined} className={styles.root()}>
      <div className={styles.body()}>
        {title && (
          <div className={styles.title()}>
            {title}
            {pinned && <span title="Does not auto-dismiss" className={styles.pinned()}>Pinned</span>}
          </div>
        )}
        {message && <div className={styles.message()}>{message}</div>}
        {actionLabel && (
          <button onClick={onAction} className={styles.action()}>{actionLabel}</button>
        )}
      </div>
      {dismissible && (
        <button onClick={onClose} aria-label="Close" className={styles.close()}>
          <i className="ph-bold ph-x" />
        </button>
      )}
    </div>
  );
}
