// frameworks/angular/components/navigation/arena-page-head/ArenaPageHead.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { arenaContainerWidth, arenaReadBreakpoint } from '../../../ContainerSize';
import { ArenaActions } from '../../../ProjectionMarkers';
import { arenaPageHeadStyles } from './ArenaPageHead.variants';
import type { ArenaPageHeadAlign } from '../../../Api.generated';

@Component({
  selector: 'arena-page-head',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="styles().titles()">
      <h1 [class]="styles().title()">{{ title() }}</h1>
      @if (subtitle(); as caption) {
        <p [class]="styles().subtitle()">{{ caption }}</p>
      }
    </div>
    @if (actions()) {
      <div [class]="styles().actions()"><ng-content select="[actions]" /></div>
    }
  `,
})
export class ArenaPageHead {
  /** The page title. Required: a page head with no title is a bug, not a state. */
  readonly title = input.required<string>();
  /** A muted line under the title. */
  readonly subtitle = input<string>();
  /** Cross-axis alignment of the actions block against the title, wide layout only. */
  readonly align = input<ArenaPageHeadAlign>('start');

  protected readonly actions = contentChild(ArenaActions);

  private readonly width = arenaContainerWidth();
  private readonly small = arenaReadBreakpoint('sm');

  protected readonly styles = computed(() => {
    const measured = this.width();
    return arenaPageHeadStyles({ narrow: measured !== null && measured < this.small, align: this.align() });
  });
}

// frameworks/react/components/navigation/arena-page-head/ArenaPageHead.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaPageHead.classes.generated.ts';
import { useArenaContainerWidth, arenaReadBreakpoint } from '../../../UseArenaContainerWidth.ts';

import type { ArenaPageHeadAlign } from '../../../Api.generated';

export interface ArenaPageHeadProps {

  /** The page title. Required: a page head with no title is a bug, not a state. */
  title: string;

  /** A muted line under the title. */
  subtitle?: string;

  /** Page-level controls, right-aligned in the head. */
  actions?: React.ReactNode;

  /** Cross-axis alignment of the actions block against the title, wide layout only. */
  align?: ArenaPageHeadAlign;
}


const arenaPageHeadStyles = arenaStyles(manifest);

export function ArenaPageHead({ title, subtitle, actions, align = 'start' }: ArenaPageHeadProps) {
  if (!title) throw new Error('ArenaPageHead: `title` is required');
  const [ref, width] = useArenaContainerWidth();
  const narrow = width !== null && width < arenaReadBreakpoint('sm');
  const styles = arenaPageHeadStyles({ narrow, align });

  return (
    <div ref={ref} className={styles.root()}>
      <div className={styles.titles()}>
        <h1 className={styles.title()}>{title}</h1>
        {subtitle && <p className={styles.subtitle()}>{subtitle}</p>}
      </div>
      {actions && <div className={styles.actions()}>{actions}</div>}
    </div>
  );
}
