// frameworks/react/components/display/arena-avatar/ArenaAvatar.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaAvatar.classes.generated.ts';

import type { ArenaAvatarSize, ArenaAvatarShape, ArenaAvatarStatus } from '../../../Api.generated';

export interface ArenaAvatarProps {
  /** Image URL. Absent renders initials from `name`. */
  src?: string;
  /** The person or entity name. Its first two words' initials render when there is no `src`, and it is the image's alt text. */
  name?: string;
  /** The avatar's diameter. */
  size?: ArenaAvatarSize;
  /** Circle for a person, rounded for a team. */
  shape?: ArenaAvatarShape;
  /** A presence dot in the state's colour. `offline` is a visible muted dot; omit `status` entirely for no dot. Optional: there is no invisible enum value. */
  status?: ArenaAvatarStatus;
}

const arenaAvatarStyles = arenaStyles(manifest);
const STATUSES = Object.keys(manifest.variants.status);
type Status = keyof typeof manifest.variants.status;
const statusOf = (status: string | undefined): Status | undefined =>
  (status && STATUSES.includes(status) ? status as Status : 'offline');

export function ArenaAvatar({ src, name = '', size = 'md', shape = 'circle', status }: ArenaAvatarProps) {
  const initials = name.trim().split(/\s+/).slice(0, 2).map((w) => w[0] || '').join('').toUpperCase();
  const styles = arenaAvatarStyles({ size, shape, status: status ? statusOf(status) : 'none' });
  return (
    <span className={styles.root()}>
      <span className={styles.box()}>
        {src ? <img src={src} alt={name} className={styles.image()} /> : initials}
      </span>
      {status && <span aria-label={status} title={status} className={styles.status()} />}
    </span>
  );
}

// frameworks/angular/components/display/arena-avatar/ArenaAvatar.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { arenaAvatarStyles } from './ArenaAvatar.variants';
import type { ArenaAvatarSize, ArenaAvatarShape, ArenaAvatarStatus } from '../../../Api.generated';

@Component({
  selector: 'arena-avatar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.name]': 'null',
  },
  template: `
    <span [class]="styles().box()">
      @if (src(); as source) {
        <img [src]="source" [alt]="name()" [class]="styles().image()" />
      } @else {
        {{ initials() }}
      }
    </span>
    @if (status(); as presence) {
      <span [class]="styles().status()" [attr.aria-label]="presence" [title]="presence"></span>
    }
  `,
})
export class ArenaAvatar {
  /** Image URL. Absent renders initials from `name`. */
  readonly src = input<string>();
  /** The person or entity name. Its first two words' initials render when there is no `src`, and it is the image's alt text. */
  readonly name = input('');
  /** The avatar's diameter. */
  readonly size = input<ArenaAvatarSize>('md');
  /** Circle for a person, rounded for a team. */
  readonly shape = input<ArenaAvatarShape>('circle');
  /** A presence dot in the state's colour. `offline` is a visible muted dot; omit `status` entirely for no dot. Optional: there is no invisible enum value. */
  readonly status = input<ArenaAvatarStatus>();

  protected readonly styles = computed(() =>
    arenaAvatarStyles({ size: this.size(), shape: this.shape(), status: this.status() ?? 'none' }));

  protected readonly initials = computed(() =>
    this.name().trim().split(/\s+/).slice(0, 2).map((word) => word[0] ?? '').join('').toUpperCase());
}
