// frameworks/angular/components/feedback/tooltip/Tooltip.ts
import {
  ChangeDetectionStrategy, Component, DOCUMENT, DestroyRef, ElementRef, Injector, TemplateRef,
  ViewContainerRef, computed, inject, input, viewChild,
} from '@angular/core';
import {
  type ConnectedPosition, type OverlayRef, createFlexibleConnectedPositionStrategy,
  createOverlayRef, createRepositionScrollStrategy,
} from '@angular/cdk/overlay';
import { TemplatePortal } from '@angular/cdk/portal';
import { delayClose, delayOpen, sp2 } from '../../../Tokens.generated';
import { tooltipStyles } from './Tooltip.variants';

let nextId = 0;

export const TOOLTIP_POSITIONS: ConnectedPosition[] = [
  { originX: 'center', originY: 'top', overlayX: 'center', overlayY: 'bottom', offsetY: -sp2 },
  { originX: 'center', originY: 'bottom', overlayX: 'center', overlayY: 'top', offsetY: sp2 },
];

export function joinDescribedBy(own: string | null, bubbleId: string): string {
  return own ? `${own} ${bubbleId}` : bubbleId;
}

export function stripDescribedBy(current: string | null, bubbleId: string): string | null {
  if (!current) return null;
  const rest = current.split(/\s+/).filter((id) => id && id !== bubbleId);
  return rest.length ? rest.join(' ') : null;
}

@Component({
  selector: 'arena-tooltip',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '(pointerenter)': 'scheduleOpen()',
    '(pointerleave)': 'scheduleClose()',
    '(focusin)': 'openNow()',
    '(focusout)': 'closeNow()',
  },
  template: `
    <ng-content />
    <ng-template #bubble>
      <span [class]="styles().bubble()" role="tooltip" [id]="bubbleId">{{ label() }}</span>
    </ng-template>
  `,
})
export class Tooltip {
  /** The bubble's text. Arena draws the bubble; the consumer names it. */
  readonly label = input.required<string>();

  protected readonly bubbleId = `arena-tooltip-${nextId++}`;
  protected readonly styles = computed(() => tooltipStyles({ anchored: true }));

  private readonly bubble = viewChild.required<TemplateRef<unknown>>('bubble');
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly injector = inject(Injector);
  private readonly viewContainer = inject(ViewContainerRef);
  private readonly doc = inject(DOCUMENT);

  private ref: OverlayRef | null = null;
  private timer: ReturnType<typeof setTimeout> | null = null;
  private detachEscape: (() => void) | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => this.closeNow());
  }

  protected scheduleOpen(): void {
    this.schedule(() => this.attach(), delayOpen);
  }

  protected scheduleClose(): void {
    this.schedule(() => this.detach(), delayClose);
  }

  protected openNow(): void {
    this.clearTimer();
    this.attach();
  }

  protected closeNow(): void {
    this.clearTimer();
    this.detach();
  }

  private schedule(run: () => void, ms: number): void {
    this.clearTimer();
    this.timer = setTimeout(() => {
      this.timer = null;
      run();
    }, ms);
  }

  private clearTimer(): void {
    if (this.timer !== null) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }

  private attach(): void {
    if (this.ref) return;
    const ref = createOverlayRef(this.injector, {
      positionStrategy: createFlexibleConnectedPositionStrategy(this.injector, this.host)
        .withPositions(TOOLTIP_POSITIONS)
        .withPush(false),
      scrollStrategy: createRepositionScrollStrategy(this.injector),
    });
    ref.attach(new TemplatePortal(this.bubble(), this.viewContainer));
    this.ref = ref;
    this.describeTrigger();
    this.listenForEscape();
  }

  private detach(): void {
    this.detachEscape?.();
    this.detachEscape = null;
    this.undescribeTrigger();
    this.ref?.dispose();
    this.ref = null;
  }

  private trigger(): HTMLElement | null {
    const first = this.host.nativeElement.firstElementChild;
    return first instanceof HTMLElement ? first : null;
  }

  private describeTrigger(): void {
    const trigger = this.trigger();
    if (trigger) {
      trigger.setAttribute('aria-describedby', joinDescribedBy(trigger.getAttribute('aria-describedby'), this.bubbleId));
    }
  }

  private undescribeTrigger(): void {
    const trigger = this.trigger();
    if (!trigger) return;
    const rest = stripDescribedBy(trigger.getAttribute('aria-describedby'), this.bubbleId);
    if (rest) trigger.setAttribute('aria-describedby', rest);
    else trigger.removeAttribute('aria-describedby');
  }

  private listenForEscape(): void {
    const onKeydown = (event: Event): void => {
      if (event instanceof KeyboardEvent && event.key === 'Escape') this.closeNow();
    };
    this.doc.addEventListener('keydown', onKeydown);
    this.detachEscape = () => this.doc.removeEventListener('keydown', onKeydown);
  }
}

// frameworks/react/components/feedback/tooltip/Tooltip.tsx
import React, { useEffect, useId, useRef, useState } from 'react';
import { delayOpen, delayClose } from '../../../Tokens.generated.js';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Tooltip.manifest.generated.ts';

export interface TooltipProps {

  /** The bubble's text. Arena draws the bubble; the consumer names it. */
  label: string;

  /** The element the tooltip describes and attaches to. */
  children: React.ReactNode;
}


const tooltipStyles = tv(manifest);

export function Tooltip({ children, label }: TooltipProps) {
  if (!label) throw new Error('Tooltip: `label` is required');
  if (!React.isValidElement(children) || children.type === React.Fragment) {
    throw new Error(
      'Tooltip: `children` must be a single element that forwards props to its own DOM node. '
      + 'A fragment or a bare string takes aria-describedby nowhere, so the bubble names nothing.',
    );
  }
  const [show, setShow] = useState(false);

  const bubbleId = `tooltip-${useId().replace(/:/g, '')}`;

  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const clear = () => { if (timer.current !== null) { clearTimeout(timer.current); timer.current = null; } };
  const schedule = (next: boolean, ms: number) => { clear(); timer.current = setTimeout(() => setShow(next), ms); };

  const now = (next: boolean) => { clear(); setShow(next); };
  useEffect(() => () => clear(), []);

  useEffect(() => {
    if (!show || typeof document === 'undefined') return undefined;
    const onEscape = (e: KeyboardEvent) => { if (e.key === 'Escape') now(false); };
    document.addEventListener('keydown', onEscape);
    return () => document.removeEventListener('keydown', onEscape);
  }, [show]);

  const own = children.props['aria-describedby'];
  const describedBy = show ? [own, bubbleId].filter(Boolean).join(' ') : own;
  const described = React.cloneElement(children, { 'aria-describedby': describedBy });

  const wrapRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const el = wrapRef.current && wrapRef.current.firstElementChild;
    if (!el) return;
    if (describedBy) el.setAttribute('aria-describedby', describedBy);
    else el.removeAttribute('aria-describedby');
  }, [describedBy]);
  const styles = tooltipStyles();
  return (
    <span ref={wrapRef} className={styles.root()}
      onMouseEnter={() => schedule(true, delayOpen)}
      onMouseLeave={() => schedule(false, delayClose)}
      onFocus={() => now(true)}
      onBlur={() => now(false)}>
      {described}
      {show && (
        <span role="tooltip" id={bubbleId} className={styles.bubble()}>
          {label}
        </span>
      )}
    </span>
  );
}
