// frameworks/react/components/display/calendar-event/CalendarEvent.jsx
import React from 'react';
import { IconButton } from '../../forms/icon-button/IconButton.jsx';

const KEBAB_RESERVE = 'calc(var(--dz-ctl-h-sm) + var(--bw) * 2)';

export const CalendarEvent = React.forwardRef(function CalendarEvent({
  id, title, start, end, colorId, onClick, interactive = false, disabled = false,
  actionsEnabled = false, actions,
  box, color, timeLabel, dateLabel, showTime, actionsBelow, tabIndex, defaultPanelOpen,
}, ref) {

  if (!id) throw new Error('CalendarEvent: `id` is required');
  if (!title) throw new Error('CalendarEvent: `title` is required');
  if (!start) throw new Error('CalendarEvent: `start` is required');
  if (!end) throw new Error('CalendarEvent: `end` is required');

  const hasPanel = actionsEnabled;
  const Tag = interactive && !hasPanel ? 'button' : 'div';

  const [panelOpen, setPanelOpen] = React.useState(Boolean(defaultPanelOpen));

  const bodyIsButton = interactive && hasPanel;

  const focusableRef = React.useRef(null);
  const kebabWrapRef = React.useRef(null);
  const panelRef = React.useRef(null);
  const setFocusable = (node) => {
    focusableRef.current = node;
    if (typeof ref === 'function') ref(node);
    else if (ref) ref.current = node;
  };

  const kebabEl = () => kebabWrapRef.current && kebabWrapRef.current.firstElementChild;

  const openedByUser = React.useRef(false);
  React.useEffect(() => {
    if (!panelOpen || !openedByUser.current) return;
    openedByUser.current = false;
    const panel = panelRef.current;
    if (!panel) return;

    const first = panel.querySelector('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    if (first) first.focus();
  }, [panelOpen]);

  const body = (
    <>
      <span style={{ fontSize: 'var(--dz-text-sm)', fontWeight: 'var(--fw-semibold)', color: 'var(--text-strong)',
        whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{title}</span>
      {showTime && (
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-2xs)', color: 'var(--mute)' }}>{timeLabel}</span>
      )}
    </>
  );

  return (
    <Tag ref={bodyIsButton ? undefined : setFocusable}

      type={interactive && !hasPanel ? 'button' : undefined}
      tabIndex={bodyIsButton ? undefined : tabIndex}
      onClick={interactive && !hasPanel && !disabled ? (e) => { e.stopPropagation(); onClick && onClick(); } : undefined}
      aria-label={interactive && !hasPanel ? `${title}, ${dateLabel}, ${timeLabel}` : undefined}
      aria-disabled={interactive && !hasPanel && disabled ? 'true' : undefined}
      onKeyDown={hasPanel ? (e) => {

        if (e.key === 'Escape' && panelOpen) {
          e.stopPropagation();
          setPanelOpen(false);
          const kebab = kebabEl();
          if (kebab) kebab.focus();
          return;
        }
        const kebab = kebabEl();
        if (!kebab) return;
        if (e.key === 'ArrowRight' && e.target !== kebab) {
          e.preventDefault(); e.stopPropagation(); kebab.focus();
        } else if (e.key === 'ArrowLeft' && e.target === kebab && focusableRef.current) {
          e.preventDefault(); e.stopPropagation(); focusableRef.current.focus();
        }
      } : undefined}
      style={{ position: 'absolute', ...box, boxSizing: 'border-box',
        display: 'flex', flexDirection: 'column', gap: 0,

        overflow: panelOpen ? 'visible' : 'hidden',
        textAlign: 'left', padding: 'calc(var(--sp-1) * 1) calc(var(--sp-1) * 1.5)',
        paddingRight: hasPanel && !actionsBelow ? KEBAB_RESERVE : 'calc(var(--sp-1) * 1.5)',
        background: `color-mix(in oklab, ${color} 16%, var(--surface-card))`,
        borderLeft: `var(--bw-strong) solid ${color}`, borderTop: 'none', borderRight: 'none', borderBottom: 'none',
        borderRadius: 'var(--r-sm)', cursor: interactive ? (disabled ? 'not-allowed' : 'pointer') : 'default',
        opacity: interactive && disabled ? 0.5 : 1,
        font: 'inherit' }}>
      {hasPanel ? (
        <>
          {interactive ? (
            <button type="button" ref={setFocusable} tabIndex={tabIndex}
              onClick={disabled ? undefined : (e) => { e.stopPropagation(); onClick && onClick(); }}
              aria-label={`${title}, ${dateLabel}, ${timeLabel}`}
              aria-disabled={disabled ? 'true' : undefined}

              style={{ display: 'flex', flexDirection: 'column', gap: 0,
                background: 'none', border: 'none', padding: 0, margin: 0,
                font: 'inherit', color: 'inherit', textAlign: 'left',
                cursor: disabled ? 'not-allowed' : 'pointer' }}>
              {body}
            </button>
          ) : body}
          <span ref={kebabWrapRef} style={{ position: 'absolute', right: 0, ...(actionsBelow ? { bottom: 0 } : { top: 0 }) }}>
            <IconButton icon="ph-bold ph-dots-three-vertical" label="Actions" size="sm"
              tabStop={false}
              onClick={() => { openedByUser.current = !panelOpen; setPanelOpen((o) => !o); }} />
            {panelOpen && (
              <span ref={panelRef} style={{ position: 'absolute', top: '100%', right: 0, zIndex: 1,
                display: 'flex', gap: 'var(--sp-2)', padding: 'var(--sp-2)',
                background: 'var(--surface-card)', border: 'var(--bw) solid var(--color-base-300)',
                borderRadius: 'var(--r-sm)', boxShadow: 'var(--shadow-2)' }}>
                {actions}
              </span>
            )}
          </span>
        </>
      ) : body}
    </Tag>
  );
});

// frameworks/angular/components/display/calendar-event/CalendarEvent.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, ElementRef, afterRenderEffect, booleanAttribute,
  computed, inject, input, output, signal, viewChild,
} from '@angular/core';
import type { CatSlot } from '../../../Api.generated';
import { catColor } from '../../../DataVisuals';
import { IconButton } from '../../forms/icon-button/IconButton';
import { CalendarState } from '../calendar/CalendarState';
import { formatDate, formatHM, showsTime, stacksActions } from '../calendar/CalendarInternals';
import { calendarEventStyles } from './CalendarEvent.variants';

const FOCUSABLE = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';

let seq = 0;

@Component({
  selector: 'arena-calendar-event',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconButton],
  host: { style: 'display: contents', '[attr.title]': 'null', '[attr.id]': 'null' },
  template: `
    @if (across(); as across) {
      @if (hasPanel()) {
        <div [id]="domId" [class]="chipClass()" [style]="across"
             [style.top.px]="topPx()" [style.height.px]="heightPx()"
             [style.background]="tint()" [style.borderLeftColor]="ink()"
             (keydown)="onKeydown($event)">
          @if (interactive()) {
            <button #focusable type="button" tabindex="-1" [class]="bodyClass()"
                    [attr.aria-label]="label()" [attr.aria-disabled]="inert()"
                    (click)="onActivate($event)">
              <span [class]="styles().title()">{{ heading() }}</span>
              @if (showTime()) {
                <span [class]="styles().time()">{{ timeLabel() }}</span>
              }
            </button>
          } @else {
            <span #focusable tabindex="-1" [class]="bodyClass()">
              <span [class]="styles().title()">{{ heading() }}</span>
              @if (showTime()) {
                <span [class]="styles().time()">{{ timeLabel() }}</span>
              }
            </span>
          }
          <span #kebabWrap [class]="kebabClass()">
            <arena-icon-button icon="ph-bold ph-dots-three-vertical" label="Actions" size="sm"
                               [tabStop]="false" (click)="togglePanel()" />
            @if (panelOpen()) {
              <span #panel [class]="styles().panel()" [style.zIndex]="1">
                <ng-content select="[actions]" />
              </span>
            }
          </span>
        </div>
      } @else if (interactive()) {
        <button #focusable [id]="domId" type="button" tabindex="-1" [class]="chipClass()"
                [style]="across" [style.top.px]="topPx()" [style.height.px]="heightPx()"
                [style.background]="tint()" [style.borderLeftColor]="ink()"
                [attr.aria-label]="label()" [attr.aria-disabled]="inert()"
                (click)="onActivate($event)">
          <span [class]="styles().title()">{{ heading() }}</span>
          @if (showTime()) {
            <span [class]="styles().time()">{{ timeLabel() }}</span>
          }
        </button>
      } @else {
        <div #focusable [id]="domId" tabindex="-1" [class]="chipClass()"
             [style]="across" [style.top.px]="topPx()" [style.height.px]="heightPx()"
             [style.background]="tint()" [style.borderLeftColor]="ink()">
          <span [class]="styles().title()">{{ heading() }}</span>
          @if (showTime()) {
            <span [class]="styles().time()">{{ timeLabel() }}</span>
          }
        </div>
      }
    }
  `,
})
export class CalendarEvent {
  readonly id = input.required<string>();
  readonly title = input.required<string>();
  readonly start = input.required<string>();
  readonly end = input.required<string>();
  readonly colorId = input<CatSlot>();
  readonly interactive = input(false, { transform: booleanAttribute });
  readonly actionsEnabled = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly click = output<void>();

  protected readonly domId = `arena-calendar-event-${seq++}`;

  private readonly state = inject(CalendarState);
  private readonly destroyRef = inject(DestroyRef);
  private readonly focusable = viewChild<ElementRef<HTMLElement>>('focusable');
  private readonly kebabWrap = viewChild<ElementRef<HTMLElement>>('kebabWrap');
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
  private openedByUser = false;

  protected readonly panelOpen = signal(false);

  protected readonly hasPanel = computed(() => this.actionsEnabled());

  private readonly placement = computed(() => this.state.placementOf(this));

  protected readonly topPx = computed(() => {
    const at = this.placement();
    return at ? this.state.y(at.startMin) : 0;
  });

  protected readonly heightPx = computed(() => {
    const at = this.placement();
    return at ? this.state.y(at.endMin) - this.state.y(at.startMin) : 0;
  });

  protected readonly across = computed(() => {
    const at = this.placement();
    if (!at) return null;
    const columns = this.state.days().length;
    const leftShare = ((at.dayIndex + at.col / at.cols) / columns) * 100;
    const widthShare = (1 / (at.cols * columns)) * 100;
    return { left: `${leftShare}%`, right: `${100 - leftShare - widthShare}%` };
  });

  protected readonly showTime = computed(() => {
    const at = this.placement();
    return at !== null && showsTime(this.heightPx(), this.state.slotWidth(at.cols));
  });

  protected readonly actionsBelow = computed(() => {
    const at = this.placement();
    return at !== null && stacksActions(this.heightPx(), this.state.slotWidth(at.cols));
  });

  protected readonly ink = computed(() => catColor(this.colorId() ?? 1));

  protected readonly tint = computed(
    () => `color-mix(in oklab, ${this.ink()} 16%, var(--surface-card))`,
  );

  protected readonly timeLabel = computed(() => {
    const at = this.placement();
    return at ? `${formatHM(at.startMin)} – ${formatHM(at.endMin)}` : '';
  });

  protected readonly label = computed(() => {
    const at = this.placement();
    if (!at) return null;
    const day = formatDate(at.dayIso, { weekday: 'long', day: 'numeric', month: 'long' });
    return `${this.heading()}, ${day}, ${this.timeLabel()}`;
  });

  protected readonly inert = computed(() => (this.disabled() ? 'true' : null));

  protected readonly heading = computed(() => {
    for (const [member, value] of [
      ['id', this.id()], ['title', this.title()], ['start', this.start()], ['end', this.end()],
    ] as const) {
      if (value.trim() === '') throw new Error(`CalendarEvent: \`${member}\` is required`);
    }
    return this.title();
  });

  protected readonly styles = computed(() => calendarEventStyles());

  protected readonly chipClass = computed(() => calendarEventStyles({
    reserve: this.hasPanel() && !this.actionsBelow(),
    panelOpen: this.panelOpen(),
    clickable: this.interactive() && !this.disabled(),
    disabled: this.interactive() && this.disabled(),
  }).chip());

  protected readonly bodyClass = computed(
    () => calendarEventStyles({ disabled: this.interactive() && this.disabled() }).chipBody(),
  );

  protected readonly kebabClass = computed(
    () => calendarEventStyles({ actionsBelow: this.actionsBelow() }).kebabWrap(),
  );

  constructor() {
    this.state.register(this, {
      domId: this.domId,
      focus: () => this.focusable()?.nativeElement.focus(),
    });
    this.destroyRef.onDestroy(() => this.state.release(this));

    afterRenderEffect(() => {
      if (!this.panelOpen() || !this.openedByUser) return;
      this.openedByUser = false;
      this.panel()?.nativeElement.querySelector<HTMLElement>(FOCUSABLE)?.focus();
    });
  }

  protected togglePanel(): void {
    this.openedByUser = !this.panelOpen();
    this.panelOpen.update((open) => !open);
  }

  protected onActivate(event: MouseEvent): void {
    event.stopPropagation();
    if (this.interactive() && !this.disabled()) this.click.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    const kebab = this.kebabWrap()?.nativeElement.querySelector<HTMLElement>('button');
    if (event.key === 'Escape' && this.panelOpen()) {
      event.stopPropagation();
      this.panelOpen.set(false);
      kebab?.focus();
      return;
    }
    if (!kebab) return;
    if (event.key === 'ArrowRight' && event.target !== kebab) {
      event.preventDefault();
      event.stopPropagation();
      kebab.focus();
    } else if (event.key === 'ArrowLeft' && event.target === kebab) {
      event.preventDefault();
      event.stopPropagation();
      this.focusable()?.nativeElement.focus();
    }
  }
}
