// frameworks/angular/components/navigation/side-nav-section/SideNavSection.ts
import {
  ChangeDetectionStrategy, Component, computed, contentChildren, forwardRef, inject, input,
} from '@angular/core';
import { SideNavChild, SideNavState, indentFor } from '../side-nav/SideNavState';
import { sideNavStyles } from '../side-nav/SideNav.variants';

let nextId = 0;

@Component({
  selector: 'arena-side-nav-section',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    SideNavState,
    { provide: SideNavChild, useExisting: forwardRef(() => SideNavSection) },
  ],
  host: {
    '[class]': 'styles().section()',
    role: 'group',
    '[attr.aria-labelledby]': 'labelId',
  },
  template: `
    <div [id]="labelId" [class]="styles().sectionLabel()" [style.paddingInlineStart]="indent()">{{ heading() }}</div>
    <ng-content />
  `,
})
export class SideNavSection {
  readonly label = input.required<string>();

  private readonly parent = inject(SideNavState, { skipSelf: true });
  private readonly own = inject(SideNavState);

  protected readonly labelId = `arena-side-nav-section-${nextId++}`;
  protected readonly children = contentChildren(SideNavChild);

  protected readonly heading = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('SideNavSection: `label` is required, and names the group its heading introduces');
    }
    return text;
  });

  protected readonly indent = computed(() => indentFor(this.parent.indentStep(), this.parent.depth()));
  protected readonly styles = computed(() => sideNavStyles());

  constructor() {
    this.own.depth = computed(() => this.parent.depth() + 1);
    this.own.activeId = this.parent.activeId;
    this.own.indentStep = this.parent.indentStep;
    this.own.activate = (id: string) => this.parent.activate(id);
  }

  protected ngAfterContentInit(): void {
    if (this.children().length === 0) {
      throw new Error('SideNavSection: a section with no children is not a legal shape — its heading would name nothing');
    }
  }
}

// frameworks/react/components/navigation/side-nav-section/SideNavSection.jsx
import React, { useId } from 'react';
import { injectInto, indentFor, COLUMN } from '../side-nav/SideNavInject.jsx';

export function SideNavSection({
  label, children,
  depth = 0, activeId, indentStep = 3, onActivate,
}) {

  if (!label?.trim()) throw new Error('SideNavSection: `label` is required');

  if (React.Children.toArray(children).length === 0) {
    throw new Error('SideNavSection: a section with no children is not a legal shape');
  }
  const labelId = useId();
  return (
    <div role="group" aria-labelledby={labelId} style={COLUMN}>
      <div id={labelId} style={{
        paddingInlineStart: indentFor(indentStep, depth),
        paddingBlock: 'calc(var(--sp-1) * 1.5)',
        fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)',
        letterSpacing: 'var(--ls-badge)', textTransform: 'uppercase',
        color: 'var(--mute)',
      }}>{label}</div>
      {injectInto(children, { depth: depth + 1, activeId, indentStep, onActivate })}
    </div>
  );
}
