// frameworks/angular/components/display/activity-feed/ActivityFeed.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input } from '@angular/core';
import type { ActivityItem } from '../../../Api.generated';
import { activityFeedStyles } from './ActivityFeed.variants';

export interface ActivityFeedRow {
  item: ActivityItem;
  itemClass: string;
  dotClass: string;
}

export function resolveActivityFeedRows(items: readonly ActivityItem[]): ActivityFeedRow[] {
  return items.map((item, index) => {
    const resolved = activityFeedStyles({ tone: item.tone ?? 'accent', divided: index > 0 });
    return { item, itemClass: resolved.item(), dotClass: resolved.dot() };
  });
}

@Component({
  selector: 'arena-activity-feed',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents', '(keydown)': 'onKeydown($event)' },
  template: `
    <ul [class]="base().root()" role="feed" [attr.aria-label]="labelText()"
        [attr.aria-busy]="busy() ? 'true' : 'false'">
      @for (row of rows(); track row.item.id ?? $index; let i = $index) {
        <li [class]="row.itemClass" role="article" tabindex="0"
            [attr.aria-posinset]="i + 1" [attr.aria-setsize]="rows().length">
          <span [class]="row.dotClass" aria-hidden="true"></span>
          <span [class]="base().text()">
            <b [class]="base().actor()">{{ row.item.actor }}</b> {{ row.item.action }}
            @if (row.item.target) {
              <span [class]="base().target()">{{ row.item.target }}</span>
            }
          </span>
          @if (row.item.time) {
            <span [class]="base().time()">{{ row.item.time }}</span>
          }
        </li>
      }
    </ul>
  `,
})
export class ActivityFeed {
  readonly label = input.required<string>();
  readonly items = input.required<readonly ActivityItem[]>();
  readonly busy = input(false, { transform: booleanAttribute });

  protected readonly labelText = computed(() => {
    const name = this.label();
    if (name.trim() === '') {
      throw new Error('ActivityFeed: `label` is required, and names what the events are about');
    }
    return name;
  });

  protected readonly base = computed(() => activityFeedStyles());
  protected readonly rows = computed(() => resolveActivityFeedRows(this.items()));

  protected onKeydown(event: KeyboardEvent): void {
    if (event.key !== 'PageDown' && event.key !== 'PageUp') return;
    const articles = Array.from(
      (event.currentTarget as HTMLElement).querySelectorAll<HTMLElement>('[role="article"]'),
    );
    if (articles.length === 0) return;
    const target = event.target as Element | null;
    const here = articles.indexOf(target?.closest('[role="article"]') as HTMLElement);
    const there = here === -1
      ? (event.key === 'PageDown' ? 0 : articles.length - 1)
      : here + (event.key === 'PageDown' ? 1 : -1);
    if (there < 0 || there >= articles.length) return;
    event.preventDefault();
    articles[there].focus();
  }
}

// frameworks/react/components/display/activity-feed/ActivityFeed.jsx
import React from 'react';

const TONES = {
  neutral: 'var(--bone-dim)', accent: 'var(--crimson)', gold: 'var(--gold)',
  success: 'var(--success)', warning: 'var(--warning)', danger: 'var(--danger)', info: 'var(--info)',
};

export function ActivityFeed({ items, label, busy = false }) {
  if (!label) throw new Error('ActivityFeed: `label` is required');
  if (items == null) throw new Error('ActivityFeed: `items` is required');

  const feedRef = React.useRef(null);

  const onKeyDown = (e) => {
    if (e.key !== 'PageDown' && e.key !== 'PageUp') return;
    const articles = [...feedRef.current.querySelectorAll('[role="article"]')];
    if (articles.length === 0) return;
    const here = articles.indexOf(e.target.closest('[role="article"]'));
    const there = here === -1
      ? (e.key === 'PageDown' ? 0 : articles.length - 1)
      : here + (e.key === 'PageDown' ? 1 : -1);
    if (there < 0 || there >= articles.length) return;
    e.preventDefault();
    articles[there].focus();
  };

  return (
    <ul ref={feedRef} role="feed" aria-label={label} aria-busy={busy ? 'true' : 'false'}
      onKeyDown={onKeyDown}
      style={{ display: 'flex', flexDirection: 'column', listStyle: 'none', margin: 0, padding: 0 }}>
      {items.map((item, i) => (
        <li key={item.id != null ? item.id : i}
          role="article" tabIndex={0}
          aria-posinset={i + 1} aria-setsize={items.length}
          style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 3)',
            padding: 'calc(var(--sp-1) * 3.5) 0',
            borderTop: i ? 'var(--bw) solid var(--color-base-300)' : 'none' }}>
          <span aria-hidden="true" style={{ flex: 'none', width: 'calc(var(--sp-1) * 2)', height: 'calc(var(--sp-1) * 2)',
            borderRadius: 'var(--r-pill)', background: TONES[item.tone] || TONES.accent }} />
          <span style={{ fontSize: 'var(--dz-text)', color: 'var(--bone-dim)' }}>
            <b style={{ color: 'var(--bone)' }}>{item.actor}</b> {item.action}
            {item.target && ' '}
            {item.target && <span style={{ color: 'var(--gold)', fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-md)' }}>{item.target}</span>}
          </span>
          {item.time && <span style={{ marginLeft: 'auto', fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', color: 'var(--mute)' }}>{item.time}</span>}
        </li>
      ))}
    </ul>
  );
}
