// frameworks/angular/components/navigation/tab/Tab.ts
import {
  ChangeDetectionStrategy, Component, computed, inject, input,
} from '@angular/core';
import { TabsState } from '../tabs/TabsState';
import { tabStyles } from './Tab.variants';

@Component({
  selector: 'arena-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().panel()',
    role: 'tabpanel',
    '[attr.id]': 'panelId()',
    '[attr.aria-labelledby]': 'tabId()',
    '[attr.tabindex]': 'selected() ? 0 : -1',
  },
  template: `<ng-content />`,
})
export class Tab {
  /** What this tab selects, and what the parent's `change` carries. */
  readonly value = input.required<string>();
  /** What the tab reads. Arena draws the button; the consumer names it. */
  readonly label = input.required<string>();

  private readonly tabs = inject(TabsState);

  protected readonly selected = computed(() => this.tabs.selected() === this.value());
  protected readonly panelId = computed(() => this.tabs.panelId(this.value()));
  protected readonly tabId = computed(() => this.tabs.tabId(this.value()));
  protected readonly styles = computed(() => tabStyles({ selected: this.selected() }));
}

// frameworks/react/components/navigation/tab/Tab.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from '../tabs/Tabs.manifest.generated.ts';

export interface TabInjected {
  selected: boolean;
  tabStop: boolean;
  tabId: string;
  panelId: string;
  onSelect: (value: string) => void;
}

export interface TabProps {

  /** What this tab selects, and what the parent's `change` carries. */
  value: string;

  /** What the tab reads. Arena draws the button; the consumer names it. */
  label: string;

  /** What the panel shows while this tab is selected. Tabs places it; Tab never renders it, because a tabpanel may not sit inside a tablist. */
  children?: React.ReactNode;
}


const tabsStyles = tv(manifest);

export function Tab({
  value, label,
  selected = false, tabStop = false, tabId, panelId, onSelect,
}: TabProps & Partial<TabInjected>) {

  if (!value) throw new Error('Tab: `value` is required');
  if (!label) throw new Error('Tab: `label` is required');
  return (
    <button type="button" role="tab" id={tabId}
      aria-selected={selected} aria-controls={panelId}

      tabIndex={tabStop ? 0 : -1}
      onClick={() => onSelect && onSelect(value)}
      className={tabsStyles({ selected }).tab()}>
      {label}
    </button>
  );
}
