// frameworks/react/components/charts/doughnut-chart/DoughnutChart.tsx
import React, { useState } from 'react';
import { useContainerWidth } from '../../../UseContainerWidth.ts';
import { resolveColors, arcPath, srOnly, valueWriter, CHART_HEIGHT } from '../../../DataVisuals.ts';
import { chartLegendMin, chartLegendMax, chartLegendGap, chartRingInset } from '../../../Tokens.generated.js';

import type { ChartLegendLayout, NumberFormat } from '../../../Api.generated';

export interface DoughnutChartProps {

  /** One label per slice, in the same order as `values`. A label with no value at its index is dropped. */
  labels: readonly string[];

  /** The parts, which are read as shares of their own total. A negative value floors at zero; a total of zero paints nothing. */
  values: readonly number[];

  /** Names the chart for the accessible name, the table caption and its value column. Required and guarded rather than defaulted: a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. Nothing can derive it -- what a chart is about is editorial, the same reason Table.label is required. */
  seriesLabel: string;

  /** Per-slice identity override, one ramp slot each. Absent assigns 1..N in order, which is the rule rather than a starting point. */
  slots?: readonly number[];

  /** How each legend row arranges its label and its figure. 'inline' puts them on one line, which is what fits a wide tile; 'stacked' puts the label above the figure; 'auto' measures the legend column and stacks when the row does not give. It exists because the two do not degrade equally: on one line the figure does not yield, so the label is what gets truncated, and a legend of numbers with nothing saying what they count is the opposite of a legend. The threshold is already declared, as the chart-legend-min and chart-legend-max tokens the ring width is clamped between; what was missing was the behaviour. */
  legendLayout?: ChartLegendLayout;

  /** A slice was activated by pointer, carrying its index in `values`. **In `values`, never in the drawn paths**, and that is the whole member: a slice worth zero paints nothing, so the shapes on screen and the entries in the array are two different lists, and a consumer indexing the SVG has to reproduce that omission from outside to translate one into the other. It is reverse engineering of a component's own DOM, which the next release breaks in silence. */
  onSliceActivate?: (index: number) => void;

  /** Appended verbatim to every number the chart draws: the legend value and the accessible table. Not the centre label, which is a percentage rather than a value. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  valueFormat?: NumberFormat;
}


export function DoughnutChart({
  labels, values, seriesLabel, slots, valueSuffix, valuePrefix, valueFormat,
  legendLayout = 'auto', onSliceActivate,
}: DoughnutChartProps) {
  if (!seriesLabel) throw new Error('DoughnutChart: `seriesLabel` is required (it names the series for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('DoughnutChart: `labels` is required');
  if (!values) throw new Error('DoughnutChart: `values` is required');
  const [ref, measured] = useContainerWidth();
  const [hover, setHover] = useState<number | null>(null);

  const width = measured ?? 600;
  const height = CHART_HEIGHT;
  const n = values.length;
  const fmt = valueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });
  const colors = resolveColors({ slots: slots ?? Array.from({ length: n }, (_, i) => i + 1), count: n });

  const total = values.reduce((a, b) => a + Math.max(0, b), 0);

  const legendW = Math.min(chartLegendMax, Math.max(chartLegendMin, width * 0.34));
  const stacked = legendLayout === 'auto' ? legendW < chartLegendMax : legendLayout === 'stacked';
  const plotW = Math.max(1, width - legendW - chartLegendGap);
  const cx = plotW / 2;
  const cy = height / 2;
  const rOuter = Math.max(1, Math.min(plotW, height) / 2 - chartRingInset);
  const rInner = rOuter * 0.62;

  const name = `${seriesLabel} — doughnut chart`;

  let angle = -Math.PI / 2;
  const segments = values.map((v, i) => {
    const share = total > 0 ? Math.max(0, v) / total : 0;
    const a0 = angle;
    const a1 = angle + share * Math.PI * 2;
    angle = a1;
    return { i, a0, a1, share };
  });

  return (
    <div ref={ref} style={{ position: 'relative', width: '100%', height, display: 'flex', gap: 'var(--chart-legend-gap)' }}>
      <svg width={plotW} height={height} role="img" aria-label={name}
        onMouseLeave={() => setHover(null)} style={{ display: 'block', flexShrink: 0 }}>
        {segments.map(({ i, a0, a1 }) => a1 > a0 && (
          <path key={i} d={arcPath(cx, cy, rOuter, rInner, a0, a1)} fill={colors[i]}

            stroke="var(--surface-card)"
            opacity={hover === null || hover === i ? 1 : 0.55}
            onMouseEnter={() => setHover(i)} onClick={() => onSliceActivate?.(i)}
            style={{ transition: 'opacity var(--dur-fast) var(--ease-out)', strokeWidth: 'var(--bw-strong)' }} />
        ))}
        {hover !== null && segments[hover] && (
          <text x={cx} y={cy} textAnchor="middle" dominantBaseline="middle"
            fill="var(--bone)" fontFamily="var(--font-mono)" style={{ fontSize: 'var(--dz-text-lg)' }}>
            {Math.round(segments[hover].share * 100)}%
          </text>
        )}
      </svg>

      {

}
      <div tabIndex={0} role="group" aria-label="Doughnut chart legend"
        style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 'calc(var(--sp-1) * 1.5)', overflow: 'auto' }}>
        {values.map((_, i) => (
          <div key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)}
            onClick={() => onSliceActivate?.(i)}
            style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2)', cursor: 'pointer', opacity: hover === null || hover === i ? 1 : 0.55 }}>
            <span aria-hidden="true" style={{ width: 'calc(var(--sp-1) * 2.5)', height: 'calc(var(--sp-1) * 2.5)', borderRadius: 'var(--r-xs)', background: colors[i], flexShrink: 0 }} />
            <span style={stacked
              ? { display: 'flex', flex: 1, minWidth: 0, flexDirection: 'column', alignItems: 'stretch' }
              : { display: 'flex', flex: 1, minWidth: 0, alignItems: 'baseline', gap: 'calc(var(--sp-1) * 2)', justifyContent: 'space-between' }}>
              <span style={{ flex: 1, minWidth: 0, fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-sm)', color: 'var(--text-body)',
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{labels[i] ?? ''}</span>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', color: 'var(--mute)' }}>{fmt(values[i] ?? 0)}</span>
            </span>
          </div>
        ))}
      </div>

      <table style={srOnly}>
        <caption>{name}</caption>
        <thead><tr><th>Category</th><th>{seriesLabel}</th></tr></thead>
        <tbody>
          {values.map((v, i) => <tr key={i}><th scope="row">{labels[i]}</th><td>{fmt(v)}</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// frameworks/angular/primitives/doughnut-chart/doughnut-chart.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';
import { containerWidth } from '../container-size';
import { CHART_HEIGHT, SR_ONLY, arcPath, resolveColors } from '../chart-internals';
import { chartLegendMin, chartLegendMax, chartLegendGap } from '../../tokens.generated';

/** The plot width assumed for the first paint, before `containerWidth()` has
 *  measured anything. Wide on purpose — a chart that starts narrow and widens
 *  flashes, where one that starts wide and settles does not. */
const ASSUMED_WIDTH = 600;

/** The ring starts at 12 o'clock. SVG angles run from 3 o'clock, so a quarter turn
 *  back is where a reader expects a part-of-a-whole to begin. */
const START_ANGLE = -Math.PI / 2;

/** The legend column's width in px: 34% of the container, clamped. Below the floor
 *  the labels ellipsis away to nothing; above the ceiling the ring starves. These
 *  are SVG-adjacent layout arithmetic on a measured pixel width, not CSS lengths on
 *  Arena's dimension scale — `DoughnutChart.jsx` writes the same three numbers, from
 *  tokens/src/chart.json. The 0.34 share stays a literal: a ratio deriving one
 *  dimension from another is not itself a design value. */
const LEGEND_MIN = chartLegendMin;
const LEGEND_MAX = chartLegendMax;
const LEGEND_SHARE = 0.34;

/** The flex gap between the ring and the legend, in px. The SVG is sized in user
 *  units, so the gap has to be subtracted from the plot as a number, read from the
 *  same `--chart-legend-gap` token the host's `gap` reads as a custom property —
 *  one token, two readings. From tokens/src/chart.json. */
const LEGEND_GAP = chartLegendGap;

/** How far the ring's outer edge sits inside the plot box, in px. Breathing room so a
 *  slice's stroke is not clipped by the SVG's own edge. */
const RING_INSET = 8;

/** The hole, as a fraction of the outer radius. A doughnut rather than a pie: the hole
 *  is what the centre percentage is read in, and it stops the smallest slices being
 *  compared by area alone. */
const INNER_RATIO = 0.62;

/** What an un-hovered slice fades to while a sibling is hovered. Opacity, not colour —
 *  the identity ramp must stay the identity ramp. */
const DIM_OPACITY = 0.55;

/* Every static style below is a camelCase object bound with `[style]`, never a
 * `style="a-b:c"` string in the template, for the reason bar-chart.ts and line-chart.ts
 * both record at length: check-dimension-literals.mjs finds a governed property by an
 * unbroken run of letters before a colon, so a kebab-case declaration in a template
 * string is either invisible to it (`font-size:` reads as a property named `size`) or
 * actively misread (`stroke-width:` reads as `width`, then runs the value scan off into
 * the rest of the template). An object gives the gate the same view of this component
 * that it has of React's `DoughnutChart.jsx`, where every one of these is an inline
 * style object key. This chart carries more of them than the other two, because its
 * legend is markup rather than SVG. */

/** The ring's own box. `flexShrink: 0` keeps the legend from squeezing the plot below
 *  the width its geometry was computed against. */
const SVG_STYLE = { display: 'block', flexShrink: '0' } as const satisfies Readonly<Record<string, string>>;

/** A slice. Opacity only, so there is no movement for `prefers-reduced-motion` to
 *  reduce. The stroke is the card surface showing through between slices rather than a
 *  border on them, which is why its colour is `--surface-card` and its weight is the
 *  strong border width. */
const SEGMENT_STYLE = {
  transition: 'opacity var(--dur-fast) var(--ease-out)', strokeWidth: 'var(--bw-strong)',
} as const satisfies Readonly<Record<string, string>>;

/** The hovered slice's percentage, read in the hole, in mono so it does not jitter
 *  between hovers. */
const CENTRE_LABEL_STYLE = { fontSize: 'var(--dz-text-lg)' } as const satisfies Readonly<Record<string, string>>;

/** The legend column. Not optional: slices are categories, and identity is never colour
 *  alone. `overflow: auto` so a long list scrolls rather than escaping the chart's height —
 *  which is why the element carries `tabindex="0"`/`role="group"`/`aria-label` in the
 *  template: a scrollable region nothing else can focus is unreachable by a keyboard user
 *  (WCAG 2.1.1), the same failure a `tabindex`-less `overflow: auto` box always is.
 *  `role="group"` rather than the WAI scrollable-region pattern's `role="region"`: a region
 *  is a page landmark a screen reader user jumps to directly, and this column is one part of
 *  a small chart, not something worth surfacing at that level — `aria-label` still gives it
 *  an accessible name either way. No focus style is bound here, and the reason is the
 *  charts' no-manifest exception rather than a preference: this layer styles focus with
 *  `focus-visible:` utilities carried by a component's manifest (see
 *  `ConfirmDialog.manifest.json`'s `focus-visible:ring-[length:var(--focus-width)]`), and
 *  `utilities.css` is generated from manifests only — so the three charts, which
 *  deliberately have none, cannot reach that idiom without being given one. The two
 *  inline alternatives are both worse than the UA default: a `[style]` object cannot
 *  express `:focus-visible` at all, and toggling a token-valued `boxShadow` from
 *  `(focus)`/`(blur)` would fire on a mouse click as readily as a Tab press, trading the
 *  browser's own keyboard-only heuristic for a ring that flashes on every click. Giving
 *  the doughnut a manifest purely to tokenize this outline is the real option, and it
 *  loses on cost today. */
const LEGEND_STYLE = {
  flex: '1', minWidth: '0', display: 'flex', flexDirection: 'column',
  justifyContent: 'center', gap: 'calc(var(--sp-1) * 1.5)', overflow: 'auto',
} as const satisfies Readonly<Record<string, string>>;

/** One legend row: swatch, label, value. `opacity` is bound separately, because it is
 *  the only part of the row that depends on the hover. */
const LEGEND_ROW_STYLE = {
  display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2)',
} as const satisfies Readonly<Record<string, string>>;

/** The colour chip. `background` is bound separately — it is the slice's own identity
 *  colour, and it is the whole point of the row. */
const SWATCH_STYLE = {
  width: 'calc(var(--sp-1) * 2.5)', height: 'calc(var(--sp-1) * 2.5)',
  borderRadius: 'var(--r-xs)', flexShrink: '0',
} as const satisfies Readonly<Record<string, string>>;

/** The category name, which takes the row's free space and ellipsises rather than
 *  wrapping — a wrapped legend row stops lining up with its swatch. */
const LEGEND_LABEL_STYLE = {
  flex: '1', minWidth: '0', fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-sm)',
  color: 'var(--text-body)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
} as const satisfies Readonly<Record<string, string>>;

/** The formatted value, in mono so digits align down the column. */
const LEGEND_VALUE_STYLE = {
  fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', color: 'var(--mute)',
} as const satisfies Readonly<Record<string, string>>;

/** One slice's share of the whole, as angles and as a percentage. */
export interface ArenaDoughnutSlice {
  /** The slice's 0-based position in `values`, which is also its ramp slot order. */
  index: number;
  /** Start angle in radians, 0 = 3 o'clock. */
  from: number;
  /** End angle in radians, always >= `from`. */
  to: number;
  /** The slice's fraction of the total, in `[0, 1]`. */
  share: number;
  /** `share` as whole percent, for the centre label. */
  percent: number;
}

/** Accumulates `values` into slices around the ring, clockwise from 12 o'clock.
 *  Negative values are floored at zero rather than sweeping backwards, and a total of
 *  zero yields zero-width slices rather than dividing by it — a chart of nothing paints
 *  nothing instead of throwing.
 *  @param values one number per category @returns one slice per value, in input order */
export function doughnutSlices(values: readonly number[]): ArenaDoughnutSlice[] {
  const total = values.reduce((sum, value) => sum + Math.max(0, value), 0);
  let angle = START_ANGLE;
  return values.map((value, index) => {
    const share = total > 0 ? Math.max(0, value) / total : 0;
    const from = angle;
    const to = angle + share * Math.PI * 2;
    angle = to;
    return { index, from, to, share, percent: Math.round(share * 100) };
  });
}

/** The legend column's width for a measured container width: a share of it, clamped
 *  between a floor that still fits a label and a ceiling that leaves the ring room.
 *  @param width the container's measured width in px @returns the legend width in px */
export function doughnutLegendWidth(width: number): number {
  return Math.min(LEGEND_MAX, Math.max(LEGEND_MIN, width * LEGEND_SHARE));
}

/** What is left for the ring once the legend and the gap between them are taken out.
 *  Never below 1px, so an SVG in a container narrower than its own legend still has a
 *  positive width rather than an invalid one.
 *  @param width the container's measured width in px @returns the plot width in px */
export function doughnutPlotWidth(width: number): number {
  return Math.max(1, width - doughnutLegendWidth(width) - LEGEND_GAP);
}

/** The ring's two radii. The outer fits the smaller of the plot's two axes, inset so the
 *  stroke is not clipped; the inner is a fixed fraction of it, so the hole scales with
 *  the ring instead of swallowing it at small sizes.
 *  @param plotWidth the plot width in px @param height the plot height in px
 *  @returns the outer and inner radii in px, both > 0 */
export function doughnutRadii(plotWidth: number, height: number): { outer: number; inner: number } {
  const outer = Math.max(1, Math.min(plotWidth, height) / 2 - RING_INSET);
  return { outer, inner: outer * INNER_RATIO };
}

/** Parts of one whole. Slices ARE categories, so this chart carries identity only —
 *  there is no `tone` input, because a slice cannot be a status. Colours come from the
 *  categorical ramp in order and are never cycled. One of the three hand-written SVG
 *  charts, so unlike every other primitive in this layer it carries styling of its own:
 *  a chart's visual identity is path data and presentation attributes, which a class
 *  string cannot hold. Every value in it is still a token.
 *
 *  The host is the box `containerWidth()` measures AND the row that lays the ring out
 *  beside its legend, so it declares `display:flex` explicitly rather than wrapping a
 *  flex `<div>` inside itself: `<arena-doughnut-chart>` is an unknown element whose UA
 *  default is `display:inline`, and a non-replaced inline box has no content width for a
 *  `ResizeObserver` to report — the ring would be laid out against the wrong number. A
 *  wrapper would have measured the host while laying out the wrapper, which is the same
 *  bug one element further away. `position:relative` is kept because the visually-hidden
 *  numbers table is absolutely positioned and must be contained here. This is the same
 *  hazard the manifest-driven display utility guards for every other primitive; a chart
 *  has no manifest, so it states the display itself. */
@Component({
  selector: 'arena-doughnut-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display:flex;position:relative;width:100%;gap:var(--chart-legend-gap)',
    '[style.height.px]': 'height',
  },
  template: `
    <svg [attr.width]="plotWidth()" [attr.height]="height" role="img" [attr.aria-label]="name()"
         [style]="svgStyle" (mouseleave)="hover.set(null)">
      @for (segment of segments(); track segment.index) {
        @if (segment.path) {
          <path [attr.d]="segment.path" [attr.fill]="segment.color" stroke="var(--surface-card)"
                [attr.opacity]="hover() === null || hover() === segment.index ? 1 : dimOpacity"
                (mouseenter)="hover.set(segment.index)" [style]="segmentStyle" />
        }
      }
      @if (active(); as segment) {
        <text [attr.x]="centreX()" [attr.y]="centreY()" text-anchor="middle" dominant-baseline="middle"
              fill="var(--bone)" font-family="var(--font-mono)"
              [style]="centreLabelStyle">{{ segment.percent }}%</text>
      }
    </svg>

    <div [style]="legendStyle" tabindex="0" role="group" aria-label="Doughnut chart legend">
      @for (segment of segments(); track segment.index) {
        <div [style]="legendRowStyle"
             [style.opacity]="hover() === null || hover() === segment.index ? 1 : dimOpacity"
             (mouseenter)="hover.set(segment.index)" (mouseleave)="hover.set(null)">
          <span aria-hidden="true" [style]="swatchStyle" [style.background]="segment.color"></span>
          <span [style]="legendLabelStyle">{{ segment.label }}</span>
          <span [style]="legendValueStyle">{{ segment.formatted }}</span>
        </div>
      }
    </div>

    <table [style]="srOnly">
      <caption>{{ name() }}</caption>
      <thead><tr><th>Category</th><th>{{ seriesLabel() ?? 'Value' }}</th></tr></thead>
      <tbody>
        @for (segment of segments(); track segment.index) {
          <tr><th scope="row">{{ segment.label }}</th><td>{{ segment.formatted }}</td></tr>
        }
      </tbody>
    </table>
  `,
})
export class DoughnutChart {
  readonly labels = input.required<string[]>();
  readonly values = input.required<number[]>();
  readonly seriesLabel = input<string>();
  readonly slots = input<number[]>();
  readonly valueSuffix = input<string>();

  protected readonly height = CHART_HEIGHT;
  protected readonly srOnly = SR_ONLY;
  protected readonly svgStyle = SVG_STYLE;
  protected readonly segmentStyle = SEGMENT_STYLE;
  protected readonly centreLabelStyle = CENTRE_LABEL_STYLE;
  protected readonly legendStyle = LEGEND_STYLE;
  protected readonly legendRowStyle = LEGEND_ROW_STYLE;
  protected readonly swatchStyle = SWATCH_STYLE;
  protected readonly legendLabelStyle = LEGEND_LABEL_STYLE;
  protected readonly legendValueStyle = LEGEND_VALUE_STYLE;
  protected readonly dimOpacity = DIM_OPACITY;
  protected readonly hover = signal<number | null>(null);

  /** The unit appended to every number this chart draws — the legend value and the
   *  accessible table alike, and never the centre label, which is a percentage
   *  rather than a value. Appended verbatim: the caller owns the leading space.
   *  `private`, so the reader never sees it as a member. */
  private readonly suffix = computed(() => this.valueSuffix() ?? '');

  private readonly measured = containerWidth();
  /** Wide first paint, then measured — the narrow branch never flashes. */
  private readonly width = computed(() => this.measured() ?? ASSUMED_WIDTH);

  /** The chart's accessible name, and the numbers table's caption. A name when one is
   *  given, the chart type alone when none is — the same rule bar-chart.ts and
   *  line-chart.ts follow. `protected`, so the reader never sees it as a member. */
  protected readonly name = computed(() => {
    const series = this.seriesLabel();
    return series ? `${series} — doughnut chart` : 'Doughnut chart';
  });

  protected readonly plotWidth = computed(() => doughnutPlotWidth(this.width()));
  protected readonly centreX = computed(() => this.plotWidth() / 2);
  protected readonly centreY = computed(() => this.height / 2);

  protected readonly segments = computed(() => {
    const values = this.values();
    // Identity only — slices ARE categories. `resolveColors` assigns the ramp in order
    // and never cycles it; a ninth slice folds to "Other" rather than reusing slot 1.
    const colors = resolveColors({
      slots: this.slots() ?? values.map((_, index) => index + 1),
      count: values.length,
    });
    const suffix = this.suffix();
    const centreX = this.centreX();
    const centreY = this.centreY();
    const { outer, inner } = doughnutRadii(this.plotWidth(), this.height);
    return doughnutSlices(values).map((slice) => ({
      ...slice,
      color: colors[slice.index],
      label: this.labels()[slice.index] ?? '',
      formatted: `${values[slice.index]}${suffix}`,
      path: slice.to > slice.from ? arcPath(centreX, centreY, outer, inner, slice.from, slice.to) : '',
    }));
  });

  protected readonly active = computed(() => {
    const index = this.hover();
    return index === null ? null : this.segments()[index] ?? null;
  });
}
