// frameworks/react/components/display/arena-activity-feed/ArenaActivityFeed.tsx
import React from 'react';
import { focusableElements } from '../../../UseDialogModal.ts';

import type { ArenaActivityItem } from '../../../Api.generated';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaActivityFeed.classes.generated.ts';

export type { ArenaActivityItem };

export interface ArenaActivityFeedProps {

  /** Names the feed for assistive technology. Required, and guarded at runtime: nothing can derive it, and a feed is a landmark a reader navigates BY, so say what the events are about ("Deployment activity"), never "Activity feed". */
  label: string;

  /** The events, newest first by convention. Each row is drawn by Arena; there is no per-item projection. */
  items: readonly ArenaActivityItem[];

  /** Whether a multi-step update to the feed is in progress, reflected as `aria-busy`. Set it while rows are being loaded or replaced and clear it once they settle, so a screen reader announces the settled feed rather than each intermediate state. It is an input rather than something Arena infers: only the host knows when its own loading has finished. */
  busy?: boolean;
}


const feedStyles = arenaStyles(manifest);
const TONES = Object.keys(manifest.variants.tone);
type ArenaTone = NonNullable<ArenaActivityItem['tone']>;
const toneOf = (tone: string | undefined): ArenaTone | undefined =>
  (tone && TONES.includes(tone) ? tone as ArenaTone : undefined);

export function ArenaActivityFeed({ items, label, busy = false }: ArenaActivityFeedProps) {
  if (!label?.trim()) throw new Error('ArenaActivityFeed: `label` is required');
  if (items == null) throw new Error('ArenaActivityFeed: `items` is required');

  const feedRef = React.useRef<HTMLUListElement | null>(null);

  const onKeyDown = (e: React.KeyboardEvent) => {
    const feed = feedRef.current;
    if (!feed) return;
    if (e.ctrlKey && (e.key === 'End' || e.key === 'Home')) {
      const after = e.key === 'End';
      const outside = focusableElements(feed.ownerDocument.body).filter((el) => !feed.contains(el));
      const position = after ? Node.DOCUMENT_POSITION_FOLLOWING : Node.DOCUMENT_POSITION_PRECEDING;
      const reachable = outside.filter((el) => feed.compareDocumentPosition(el) & position);
      const target = after ? reachable[0] : reachable[reachable.length - 1];
      if (!target) return;
      e.preventDefault();
      target.focus();
      return;
    }
    if (e.key !== 'PageDown' && e.key !== 'PageUp') return;
    const articles = [...feed.querySelectorAll<HTMLElement>('[role="article"]')];
    if (articles.length === 0) return;
    const from = e.target instanceof Element ? e.target.closest<HTMLElement>('[role="article"]') : null;
    const here = from === null ? -1 : articles.indexOf(from);
    const there = here === -1
      ? (e.key === 'PageDown' ? 0 : articles.length - 1)
      : here + (e.key === 'PageDown' ? 1 : -1);
    if (there < 0 || there >= articles.length) return;
    e.preventDefault();
    articles[there]?.focus();
  };

  return (
    <ul ref={feedRef} role="feed" aria-label={label} aria-busy={busy ? 'true' : 'false'}
      onKeyDown={onKeyDown}
      className={feedStyles({}).root()}>
      {items.map((item, i) => (
        <li key={item.id != null ? item.id : i}
          role="article" tabIndex={0}
          aria-posinset={i + 1} aria-setsize={items.length}
          className={feedStyles({ tone: toneOf(item.tone), divided: i > 0 }).item()}>
          <span aria-hidden="true" className={feedStyles({ tone: toneOf(item.tone) }).dot()} />
          <span className={feedStyles({}).text()}>
            <b className={feedStyles({}).actor()}>{item.actor}</b>
            {` ${item.action}${item.target ? ' ' : ''}`}
            {item.target && <span className={feedStyles({}).target()}>{item.target}</span>}
          </span>
          {item.time && <span className={feedStyles({}).time()}>{item.time}</span>}
        </li>
      ))}
    </ul>
  );
}

// frameworks/angular/components/display/arena-activity-feed/ArenaActivityFeed.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input } from '@angular/core';
import type { ArenaActivityItem } from '../../../Api.generated';
import { focusableElements } from '../../../FocusTrap';
import { arenaActivityFeedStyles } from './ArenaActivityFeed.variants';
import manifest from './ArenaActivityFeed.classes.generated';

const TONES = Object.keys(manifest.variants.tone);
type ArenaTone = NonNullable<ArenaActivityItem['tone']>;
const toneOf = (tone: string | undefined): ArenaTone | undefined =>
  (tone && TONES.includes(tone) ? tone as ArenaTone : undefined);

export interface ActivityFeedRow {
  item: ArenaActivityItem;
  itemClass: string;
  dotClass: string;
}

export function resolveActivityFeedRows(items: readonly ArenaActivityItem[]): ActivityFeedRow[] {
  return items.map((item, index) => {
    const resolved = arenaActivityFeedStyles({ tone: toneOf(item.tone), divided: index > 0 });
    return { item, itemClass: resolved.item(), dotClass: resolved.dot() };
  });
}

@Component({
  selector: 'arena-activity-feed',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents', '(keydown)': 'onKeydown($event)' },
  template: `
    <ul [class]="base().root()" role="feed" [attr.aria-label]="labelText()"
        [attr.aria-busy]="busy() ? 'true' : 'false'">
      @for (row of rows(); track row.item.id ?? $index; let i = $index) {
        <li [class]="row.itemClass" role="article" tabindex="0"
            [attr.aria-posinset]="i + 1" [attr.aria-setsize]="rows().length">
          <span [class]="row.dotClass" aria-hidden="true"></span>
          <span [class]="base().text()">
            <b [class]="base().actor()">{{ row.item.actor }}</b> {{ row.item.action }}
            @if (row.item.target) {
              <span [class]="base().target()">{{ row.item.target }}</span>
            }
          </span>
          @if (row.item.time) {
            <span [class]="base().time()">{{ row.item.time }}</span>
          }
        </li>
      }
    </ul>
  `,
})
export class ArenaActivityFeed {
  /** Names the feed for assistive technology. Required, and guarded at runtime: nothing can derive it, and a feed is a landmark a reader navigates BY, so say what the events are about ("Deployment activity"), never "Activity feed". */
  readonly label = input.required<string>();
  /** The events, newest first by convention. Each row is drawn by Arena; there is no per-item projection. */
  readonly items = input.required<readonly ArenaActivityItem[]>();
  /** Whether a multi-step update to the feed is in progress, reflected as `aria-busy`. Set it while rows are being loaded or replaced and clear it once they settle, so a screen reader announces the settled feed rather than each intermediate state. It is an input rather than something Arena infers: only the host knows when its own loading has finished. */
  readonly busy = input(false, { transform: booleanAttribute });

  protected readonly labelText = computed(() => {
    const name = this.label();
    if (name.trim() === '') {
      throw new Error('ArenaActivityFeed: `label` is required, and names what the events are about');
    }
    return name;
  });

  protected readonly base = computed(() => arenaActivityFeedStyles());
  protected readonly rows = computed(() => resolveActivityFeedRows(this.items()));

  protected onKeydown(event: KeyboardEvent): void {
    const feed = event.currentTarget as HTMLElement;
    if (event.ctrlKey && (event.key === 'End' || event.key === 'Home')) {
      const after = event.key === 'End';
      const outside = focusableElements(feed.ownerDocument.body).filter((el) => !feed.contains(el));
      const position = after ? Node.DOCUMENT_POSITION_FOLLOWING : Node.DOCUMENT_POSITION_PRECEDING;
      const reachable = outside.filter((el) => feed.compareDocumentPosition(el) & position);
      const target = after ? reachable[0] : reachable[reachable.length - 1];
      if (!target) return;
      event.preventDefault();
      target.focus();
      return;
    }
    if (event.key !== 'PageDown' && event.key !== 'PageUp') return;
    const articles = Array.from(feed.querySelectorAll<HTMLElement>('[role="article"]'));
    if (articles.length === 0) return;
    const target = event.target as Element | null;
    const here = articles.indexOf(target?.closest('[role="article"]') as HTMLElement);
    const there = here === -1
      ? (event.key === 'PageDown' ? 0 : articles.length - 1)
      : here + (event.key === 'PageDown' ? 1 : -1);
    if (there < 0 || there >= articles.length) return;
    event.preventDefault();
    articles[there].focus();
  }
}
