// frameworks/angular/components/display/arena-stat-card/ArenaStatCard.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { arenaStatCardStyles } from './ArenaStatCard.variants';
import type { ArenaTone, ArenaStatDelta } from '../../../Api.generated';

@Component({
  selector: 'arena-stat-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    <div [class]="styles().head()">
      <span [class]="styles().label()">{{ label() }}</span>
      @if (icon(); as glyph) {
        <span [class]="styles().icon()" aria-hidden="true"><i [class]="glyph"></i></span>
      }
    </div>
    <div [class]="styles().value()">{{ value() }}</div>
    @if (delta()?.value; as amount) {
      <span [class]="styles().delta()">
        <i [class]="delta()?.direction === 'down' ? 'ph-bold ph-arrow-down' : 'ph-bold ph-arrow-up'" aria-hidden="true"></i>
        {{ amount }}
      </span>
    }
    @if (sub(); as caption) {
      <span [class]="styles().sub()">{{ caption }}</span>
    }
  `,
})
export class ArenaStatCard {
  /** Short uppercase microlabel, two words at most. */
  readonly label = input.required<string>();
  /** Preformatted, e.g. "1,284" or "99.9%". ArenaStatCard never formats. */
  readonly value = input.required<string>();
  /** What state the number IS in right now, as against how it moved. ArenaBadge's vocabulary. */
  readonly tone = input<ArenaTone>('neutral');
  /** How the number moved. Absent renders no pill. */
  readonly delta = input<ArenaStatDelta>();
  /** Small muted line under the value: context, e.g. "vs last week". */
  readonly sub = input<string>();
  /** A Phosphor class name for a small glyph beside the label, drawn muted. Arena renders the aria-hidden wrapper and the `<i>`. */
  readonly icon = input<string>();

  protected readonly styles = computed(() => arenaStatCardStyles({ tone: this.tone(), deltaTone: this.delta()?.tone ?? 'neutral' }));
}

// frameworks/react/components/display/arena-stat-card/ArenaStatCard.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaStatCard.classes.generated.ts';

import type { ArenaStatDelta, ArenaTone } from '../../../Api.generated';

export type { ArenaStatDelta };

export interface ArenaStatCardProps {

  /** Short uppercase microlabel, two words at most. */
  label: string;

  /** Preformatted, e.g. "1,284" or "99.9%". ArenaStatCard never formats. */
  value: string;

  /** What state the number IS in right now, as against how it moved. ArenaBadge's vocabulary. */
  tone?: ArenaTone;
  /** How the number moved. Absent renders no pill. */
  delta?: ArenaStatDelta;

  /** Small muted line under the value: context, e.g. "vs last week". */
  sub?: string;

  /** A Phosphor class name for a small glyph beside the label, drawn muted. Arena renders the aria-hidden wrapper and the `<i>`. */
  icon?: string;
}


const arenaStatCardStyles = arenaStyles(manifest);

export function ArenaStatCard({ label, value, tone = 'neutral', delta, sub, icon }: ArenaStatCardProps) {
  if (!label || !value) throw new Error('ArenaStatCard: `label` and `value` are required');
  const styles = arenaStatCardStyles({ tone, deltaTone: delta?.tone ?? 'neutral' });
  return (
    <div className={styles.root()}>
      <div className={styles.head()}>
        <span className={styles.label()}>{label}</span>
        {icon && <span aria-hidden="true" className={styles.icon()}><i className={icon} /></span>}
      </div>
      <div className={styles.value()}>{value}</div>
      {delta?.value && (
        <span className={styles.delta()}>
          <i className={delta.direction === 'down' ? 'ph-bold ph-arrow-down' : 'ph-bold ph-arrow-up'} aria-hidden="true" />
          {delta.value}
        </span>
      )}
      {sub && <span className={styles.sub()}>{sub}</span>}
    </div>
  );
}
