// frameworks/angular/components/forms/input/Input.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output, signal,
} from '@angular/core';
import type { InputType, ValidateOn } from '../../../Api.generated';
import { inputStyles } from './Input.variants';

export function controlIdFor(id: string | undefined, label: string | undefined): string | null {
  if (id) return id;
  return label ? `in-${label.replace(/\s+/g, '-').toLowerCase()}` : null;
}

@Component({
  selector: 'arena-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    @if (label(); as text) {
      <label [class]="styles().label()" [attr.for]="controlId()">{{ text }}@if (required()) {
        <span [class]="styles().required()">*</span>
      }</label>
    }
    <div [class]="styles().field()">
      @if (icon()) {
        <i [class]="iconClass()" aria-hidden="true"></i>
      }
      @if (prefix(); as text) {
        <span [class]="styles().prefix()">{{ text }}</span>
      }
      <input [class]="styles().input()" [attr.id]="controlId()" [attr.type]="type()"
             [value]="value() ?? ''" [disabled]="disabled()" [readOnly]="readOnly()"
             [required]="required()" [attr.aria-invalid]="hasError()"
             [attr.placeholder]="placeholder()" [attr.name]="name()"
             [attr.autocomplete]="autoComplete()" [attr.min]="min()" [attr.max]="max()"
             [attr.step]="step()" [attr.maxlength]="maxLength()" [attr.pattern]="pattern()"
             (input)="onInput($event)" (change)="onNativeChange($event)" (blur)="onBlur($event)" />
      @if (hasError()) {
        <i [class]="statusIconClass('ph-fill ph-warning-circle')" aria-hidden="true"></i>
      } @else if (isValid()) {
        <i [class]="statusIconClass('ph-fill ph-check-circle')" aria-hidden="true"></i>
      }
    </div>
    @if (shownError(); as message) {
      <span [class]="styles().error()">{{ message }}</span>
    } @else if (hint(); as text) {
      <span [class]="styles().hint()">{{ text }}</span>
    }
  `,
})
export class Input {
  readonly label = input<string>();
  readonly id = input<string>();
  readonly hint = input<string>();
  readonly error = input<string>();
  readonly valid = input(false, { transform: booleanAttribute });
  readonly required = input(false, { transform: booleanAttribute });
  readonly validate = input<(value: string) => string>();
  readonly validateOn = input<ValidateOn>('blur');
  readonly type = input<InputType>('text');
  readonly icon = input<string>();
  readonly prefix = input<string>();
  readonly value = input<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly readOnly = input(false, { transform: booleanAttribute });
  readonly placeholder = input<string>();
  readonly name = input<string>();
  readonly autoComplete = input<string>();
  readonly min = input<string>();
  readonly max = input<string>();
  readonly step = input<string>();
  readonly maxLength = input<number>();
  readonly pattern = input<string>();
  readonly change = output<string>();
  readonly blur = output<string>();

  private readonly localError = signal<string | null>(null);
  private readonly touched = signal(false);

  protected readonly controlId = computed(() => controlIdFor(this.id(), this.label()));

  protected readonly shownError = computed(() => {
    const controlled = this.error();
    if (controlled !== undefined) return controlled;
    return this.touched() ? this.localError() : null;
  });

  protected readonly hasError = computed(() => Boolean(this.shownError()));

  protected readonly isValid = computed(() => !this.hasError()
    && (this.valid() || (this.touched() && this.validate() !== undefined && this.localError() === null)));

  protected readonly styles = computed(() => inputStyles({
    state: this.hasError() ? 'error' : this.isValid() ? 'valid' : 'neutral',
    disabled: this.disabled(),
    readonly: this.readOnly(),
  }));

  protected readonly iconClass = computed(() => `${this.styles().icon()} ${this.icon() ?? ''}`.trim());

  protected statusIconClass(glyph: string): string {
    return `${glyph} ${this.styles().statusIcon()}`;
  }

  protected onInput(event: Event): void {
    const text = (event.target as HTMLInputElement).value;
    this.change.emit(text);
    if (this.validateOn() === 'change') {
      this.touched.set(true);
      this.runValidate(text);
    }
  }

  protected onNativeChange(event: Event): void {
    event.stopPropagation();
  }

  protected onBlur(event: Event): void {
    const text = (event.target as HTMLInputElement).value;
    this.touched.set(true);
    this.runValidate(text);
    this.blur.emit(text);
  }

  private runValidate(text: string): void {
    const fn = this.validate();
    if (fn) this.localError.set(fn(text) || null);
  }
}

// frameworks/react/components/forms/input/Input.jsx
import React, { useEffect, useState } from 'react';

let injected = false;
function usePickerIndicator() {
  useEffect(() => {
    if (injected || typeof document === 'undefined') return;
    injected = true;
    const s = document.createElement('style');
    s.setAttribute('data-arena-input', '');
    s.textContent =
      '.arena-input::-webkit-calendar-picker-indicator{cursor:pointer;opacity:.6;' +
      'filter:invert(var(--picker-invert,1));transition:opacity var(--dur-fast) var(--ease-out)}' +
      '.arena-input::-webkit-calendar-picker-indicator:hover{opacity:1}';
    document.head.appendChild(s);
  }, []);
}

export function Input({
  label, id, hint, error, valid = false, required = false,
  validate, validateOn = 'blur', type = 'text',
  icon, prefix, value, disabled = false, readOnly = false,
  placeholder, name, autoComplete, min, max, step, maxLength, pattern,
  onChange, onBlur,
}) {
  usePickerIndicator();
  const [focus, setFocus] = useState(false);
  const [localErr, setLocalErr] = useState(null);
  const [touched, setTouched] = useState(false);
  const inputId = id || (label ? 'in-' + label.replace(/\s+/g, '-').toLowerCase() : undefined);

  const shownError = error != null ? error : (touched ? localErr : null);
  const isValid = !shownError && (valid || (touched && validate && localErr === null));

  const runValidate = (v) => { if (validate) setLocalErr(validate(v) || null); };
  const handleChange = (e) => { onChange && onChange(e.target.value); if (validateOn === 'change') { setTouched(true); runValidate(e.target.value); } };
  const handleBlur = (e) => { setFocus(false); setTouched(true); runValidate(e.target.value); onBlur && onBlur(e.target.value); };

  const borderColor = shownError ? 'var(--danger)' : focus ? 'var(--gold)' : isValid ? 'var(--success)' : 'var(--color-base-300)';
  const ring = shownError ? '0 0 0 var(--focus-width) var(--danger-soft)' : focus ? '0 0 0 var(--focus-width) var(--gold-soft)' : isValid ? '0 0 0 var(--focus-width) var(--success-soft)' : 'none';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'calc(var(--sp-1) * 1.5)' }}>
      {label && (
        <label htmlFor={inputId} style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)', letterSpacing: 'var(--ls-field-label)', textTransform: 'uppercase', color: 'var(--mute)' }}>
          {label}{required && <span style={{ color: 'var(--crimson)', marginLeft: 'calc(var(--sp-1) * 1)' }}>*</span>}
        </label>
      )}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2)', height: 'var(--dz-ctl-h)', padding: '0 calc(var(--sp-1) * 3)',
        background: readOnly ? 'var(--panel)' : 'var(--surface-input)', border: 'var(--bw) solid ' + borderColor,
        borderRadius: 'var(--r-sm)', boxShadow: ring, opacity: disabled ? 0.5 : 1,
        transition: 'border-color var(--dur-fast) var(--ease-out), box-shadow var(--dur-fast) var(--ease-out)' }}>
        {icon && <i className={icon} aria-hidden="true" style={{ color: 'var(--mute)' }} />}
        {prefix && <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-md)', color: 'var(--mute)' }}>{prefix}</span>}
        <input id={inputId} type={type} value={value} disabled={disabled} readOnly={readOnly}
          required={required} aria-invalid={!!shownError} className="arena-input"
          placeholder={placeholder} name={name} autoComplete={autoComplete}
          min={min} max={max} step={step} maxLength={maxLength} pattern={pattern}
          onFocus={() => setFocus(true)} onBlur={handleBlur} onChange={handleChange}
          style={{ flex: 1, minWidth: 0, background: 'transparent', border: 'none', outline: 'none',
            cursor: readOnly ? 'default' : 'text',
            color: 'var(--bone)', fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text)' }} />
        {shownError && <i className="ph-fill ph-warning-circle" aria-hidden="true" style={{ color: 'var(--danger)', fontSize: 'var(--icon-md)' }} />}
        {isValid && <i className="ph-fill ph-check-circle" aria-hidden="true" style={{ color: 'var(--success)', fontSize: 'var(--icon-md)' }} />}
      </div>
      {shownError ? <span style={{ fontSize: 'var(--dz-text-sm)', color: 'var(--danger)', fontFamily: 'var(--font-body)' }}>{shownError}</span>
        : hint && <span style={{ fontSize: 'var(--dz-text-sm)', color: 'var(--mute)', fontFamily: 'var(--font-body)' }}>{hint}</span>}
    </div>
  );
}
