// frameworks/angular/components/charts/arena-chart-card/ArenaChartCard.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { ArenaActions } from '../../../ProjectionMarkers';
import { arenaChartCardStyles } from './ArenaChartCard.variants';

@Component({
  selector: 'arena-chart-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    @if (title() || actions()) {
      <div [class]="styles().head()">
        @if (title(); as label) {
          <span [class]="styles().title()">{{ label }}</span>
        }
        @if (actions()) {
          <div [class]="styles().actions()"><ng-content select="[actions]" /></div>
        }
      </div>
    }
    <ng-content />
  `,
})
export class ArenaChartCard {
  /** The card heading. Absent renders no head unless `actions` is present. */
  readonly title = input<string>();

  protected readonly actions = contentChild(ArenaActions);

  protected readonly styles = computed(() => arenaChartCardStyles());
}

// frameworks/react/components/charts/arena-chart-card/ArenaChartCard.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaChartCard.classes.generated.ts';

export interface ArenaChartCardProps {

  /** The card heading. Absent renders no head unless `actions` is present. */
  title?: string;

  /** Controls in the head row, right-aligned beside the title. */
  actions?: React.ReactNode;
  /** The chart (or any body) the card frames. */
  children?: React.ReactNode;
}


const arenaChartCardStyles = arenaStyles(manifest);

export function ArenaChartCard({ title, actions, children }: ArenaChartCardProps) {
  const styles = arenaChartCardStyles();
  return (
    <div className={styles.root()}>
      {(title || actions) && (
        <div className={styles.head()}>
          {title && <span className={styles.title()}>{title}</span>}
          {actions && <div className={styles.actions()}>{actions}</div>}
        </div>
      )}
      {children}
    </div>
  );
}
