// frameworks/angular/components/navigation/arena-tab/ArenaTab.ts
import {
  ChangeDetectionStrategy, Component, computed, inject, input,
} from '@angular/core';
import { TabsState } from '../arena-tabs/TabsState';
import { arenaTabStyles } from './ArenaTab.variants';

@Component({
  selector: 'arena-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().panel()',
    role: 'tabpanel',
    '[attr.id]': 'panelId()',
    '[attr.aria-labelledby]': 'tabId()',
    '[attr.tabindex]': 'selected() ? 0 : -1',
  },
  template: `<ng-content />`,
})
export class ArenaTab {
  /** What this tab selects, and what the parent's `change` carries. */
  readonly value = input.required<string>();
  /** What the tab reads. Arena draws the button; the consumer names it. */
  readonly label = input.required<string>();

  private readonly tabs = inject(TabsState);

  protected readonly selected = computed(() => this.tabs.selected() === this.value());
  protected readonly panelId = computed(() => this.tabs.panelId(this.value()));
  protected readonly tabId = computed(() => this.tabs.tabId(this.value()));
  protected readonly styles = computed(() => arenaTabStyles({ selected: this.selected() }));
}

// frameworks/react/components/navigation/arena-tab/ArenaTab.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from '../arena-tabs/ArenaTabs.classes.generated.ts';

export interface TabInjected {
  selected: boolean;
  tabStop: boolean;
  tabId: string;
  panelId: string;
  onSelect: (value: string) => void;
}

export interface ArenaTabProps {

  /** What this tab selects, and what the parent's `change` carries. */
  value: string;

  /** What the tab reads. Arena draws the button; the consumer names it. */
  label: string;

  /** What the panel shows while this tab is selected. ArenaTabs places it; ArenaTab never renders it, because a tabpanel may not sit inside a tablist. */
  children?: React.ReactNode;
}


const arenaTabsStyles = arenaStyles(manifest);

export function ArenaTab({
  value, label,
  selected = false, tabStop = false, tabId, panelId, onSelect,
}: ArenaTabProps & Partial<TabInjected>) {

  if (!value) throw new Error('ArenaTab: `value` is required');
  if (!label) throw new Error('ArenaTab: `label` is required');
  return (
    <button type="button" role="tab" id={tabId}
      aria-selected={selected} aria-controls={panelId}

      tabIndex={tabStop ? 0 : -1}
      onClick={() => onSelect && onSelect(value)}
      className={arenaTabsStyles({ selected }).tab()}>
      {label}
    </button>
  );
}
