// frameworks/react/components/charts/line-chart/LineChart.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useContainerWidth } from '../../../UseContainerWidth.ts';
import {
  resolveColors, catColor, niceMax, ticks, srOnly, areaFill, plotWidth, railStyle, valueWriter,
  PAD, CHART_HEIGHT,
} from '../../../DataVisuals.ts';
import { chartPointR, chartPointRHover, chartLabelGap } from '../../../Tokens.generated.js';

import type { NumberFormat, SeriesTone } from '../../../Api.generated';

export type { SeriesTone };

export interface LineChartProps {

  /** One label per point, in the same order as `values`. A label with no value at its index is dropped. */
  labels: readonly string[];

  /** The plotted data, in order. One point per entry; a negative value clamps to the baseline. */
  values: readonly number[];

  /** Names the series for the accessible name, the table caption and its value column. Required and guarded rather than defaulted: a fallback of the chart TYPE satisfies roles.label mechanically and tells a screen-reader user nothing, so two charts on one page announce identically. Nothing can derive it -- what a series is about is editorial, the same reason Table.label is required. */
  seriesLabel: string;

  /** The identity colour from the categorical ramp. A line is one series, so there is no per-mark override. */
  slot?: number;

  /** Semantic colour, for a series that IS a state. Mutually exclusive with slot; passing both warns in development and tone wins. */
  tone?: SeriesTone;

  /** Fill under the line at 18% of the series colour: a tint, never a gradient. For a single series; two fills occlude each other. */
  area?: boolean;

  /** Appended verbatim to every number the chart draws: the axis ticks, the tooltip and the accessible table. Carries its own leading space if one is wanted. */
  valueSuffix?: string;

  /** Drawn verbatim before every number the chart writes, as valueSuffix is drawn after it. A currency that precedes its amount is the majority case worldwide and had no expression: with suffix alone, "1234.5 Bs." is what a chart drew where the table beside it read "Bs. 1.234,50", and the accessible table inherited the disagreement. */
  valuePrefix?: string;

  /** How each number is written before the prefix and suffix are added: which locale, how many fraction digits, whether thousands are grouped, whether large numbers are compacted. Absent, the raw JavaScript number, which is what this chart drew before the member existed. */
  valueFormat?: NumberFormat;

  /** The plot's height in px, the --chart-height token by default. A number rather than a dimension string, because the chart does arithmetic with it to place every mark, and a caller-supplied "20rem" is neither a token nor a derivation of one. */
  height?: number;

  /** The narrowest gap, in px, the chart draws between two adjacent points. Below it the chart stops compressing and overflows its container horizontally instead, scrolled and anchored to the most recent point: marker spacing is a legibility constant, not something that yields to the viewport, and thirty days in 390px is unreadable at any font size. Absent, the chart fits whatever width it is given. The rail it scrolls in is a keyboard-reachable region, because an overflow box nothing can focus is a trap. */
  minPointSpacing?: number;
}


export function LineChart({
  labels, values, seriesLabel, slot, tone, area = false, valueSuffix, valuePrefix, valueFormat,
  height = CHART_HEIGHT, minPointSpacing,
}: LineChartProps) {
  if (!seriesLabel) throw new Error('LineChart: `seriesLabel` is required (it names the series for the accessible name, and nothing can derive that)');
  if (!labels) throw new Error('LineChart: `labels` is required');
  if (!values) throw new Error('LineChart: `values` is required');
  const [ref, measured] = useContainerWidth();
  const rail = useRef<HTMLDivElement>(null);
  const [hover, setHover] = useState<number | null>(null);

  const available = measured ?? 600;
  const n = values.length;
  const width = plotWidth(available, n, minPointSpacing);
  const scrolls = width > available;
  const fmt = valueWriter({ prefix: valuePrefix, suffix: valueSuffix, format: valueFormat });

  useEffect(() => {
    const box = rail.current;
    if (!box || !scrolls) return;
    box.scrollLeft = box.scrollWidth - box.clientWidth;
  }, [scrolls, width]);

  const [color = catColor(1)] = resolveColors({ slot, tone, count: 1 });

  const max = niceMax(Math.max(0, ...values));
  const iw = Math.max(1, width - PAD.l - PAD.r);
  const ih = Math.max(1, height - PAD.t - PAD.b);
  const xOf = (i: number) => PAD.l + (n <= 1 ? iw / 2 : (iw / (n - 1)) * i);
  const yOf = (v: number) => PAD.t + ih - (Math.max(0, v) / max) * ih;
  const baseline = PAD.t + ih;

  const points = values.map((v, i) => `${xOf(i)},${yOf(v)}`).join(' ');
  const areaPath = n
    ? `M${xOf(0)},${baseline} L${values.map((v, i) => `${xOf(i)},${yOf(v)}`).join(' L')} L${xOf(n - 1)},${baseline} Z`
    : '';

  const name = `${seriesLabel} — line chart`;

  const onMove = (e: React.MouseEvent<SVGRectElement>) => {
    if (!n) return;
    const box = e.currentTarget.ownerSVGElement?.getBoundingClientRect();
    if (!box) return;
    const x = e.clientX - box.left;
    let best = 0;
    for (let i = 1; i < n; i++) if (Math.abs(xOf(i) - x) < Math.abs(xOf(best) - x)) best = i;
    setHover(best);
  };

  return (
    <div ref={ref} style={{ position: 'relative', width: '100%', height }}>
      <div ref={rail} style={railStyle} tabIndex={scrolls ? 0 : undefined}
        role={scrolls ? 'group' : undefined} aria-label={scrolls ? name : undefined}>
      <svg width={scrolls ? width : '100%'} height={height} role="img" aria-label={name} style={{ display: 'block', overflow: 'visible' }}>
        {ticks(max).map((t, i) => (
          <g key={i}>
            <line x1={PAD.l} x2={width - PAD.r} y1={yOf(t)} y2={yOf(t)} stroke="var(--border)" style={{ strokeWidth: 'var(--bw)' }} />
            <text x={PAD.l - chartLabelGap} y={yOf(t)} textAnchor="end" dominantBaseline="middle"
              fill="var(--text-muted)" fontFamily="var(--font-mono)" style={{ fontSize: 'var(--dz-text-2xs)' }}>{fmt(t)}</text>
          </g>
        ))}
        <line x1={PAD.l} x2={width - PAD.r} y1={baseline} y2={baseline} stroke="var(--line-strong)" style={{ strokeWidth: 'var(--bw)' }} />

        {}
        {area && n > 0 && (
          <path d={areaPath} fill={areaFill(color)} stroke="none" />
        )}

        {hover !== null && (
          <line x1={xOf(hover)} x2={xOf(hover)} y1={PAD.t} y2={baseline}
            stroke="var(--border-strong)" style={{ strokeWidth: 'var(--bw)' }} strokeDasharray="3 3" />
        )}

        {n > 1 && <polyline points={points} fill="none" stroke={color} style={{ strokeWidth: 'var(--bw-strong)' }}
          strokeLinejoin="round" strokeLinecap="round" />}

        {values.map((v, i) => (
          <circle key={i} cx={xOf(i)} cy={yOf(v)} r={hover === i ? chartPointRHover : chartPointR}
            fill={color} stroke="var(--surface-card)" style={{ strokeWidth: 'var(--bw-strong)' }} />
        ))}

        {

}
        {values.map((_, i) => (
          <text key={i} x={xOf(i)} y={height - chartLabelGap} textAnchor="middle"
            fill="var(--text-muted)" fontFamily="var(--font-body)" style={{ fontSize: 'var(--fs-xs)' }}>{labels[i] ?? ''}</text>
        ))}

        {
}
        <rect x={PAD.l} y={PAD.t} width={iw} height={ih} fill="transparent"
          onMouseMove={onMove} onMouseLeave={() => setHover(null)} />
      </svg>
      </div>

      {hover !== null && values[hover] !== undefined && (
        <div style={{
          position: 'absolute', left: xOf(hover), top: `calc(${yOf(values[hover])}px - calc(var(--sp-1) * 2.5))`,
          transform: 'translate(-50%,-100%)', pointerEvents: 'none', whiteSpace: 'nowrap',
          background: 'var(--bg-raised)', border: 'var(--bw) solid var(--border-strong)',
          borderRadius: 'var(--r-sm)', boxShadow: 'var(--shadow-2)', padding: 'calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)',
        }}>
          <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-xs)', color: 'var(--mute)' }}>{labels[hover]}</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-md)', color: 'var(--bone)' }}>{fmt(values[hover])}</div>
        </div>
      )}

      <table style={srOnly}>
        <caption>{name}</caption>
        <thead><tr><th>Point</th><th>{seriesLabel}</th></tr></thead>
        <tbody>
          {values.map((v, i) => <tr key={i}><th scope="row">{labels[i]}</th><td>{fmt(v)}</td></tr>)}
        </tbody>
      </table>
    </div>
  );
}

// frameworks/angular/primitives/line-chart/line-chart.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input, signal } from '@angular/core';
import { containerWidth } from '../container-size';
import { CHART_HEIGHT, PAD, SR_ONLY, niceMax, resolveColors, ticks } from '../chart-internals';
import type { SeriesTone } from '../../api.generated';
import { chartPointR, chartPointRHover } from '../../tokens.generated';

/** The plot width assumed for the first paint, before `containerWidth()` has
 *  measured anything. Wide on purpose — a chart that starts narrow and widens
 *  flashes, where one that starts wide and settles does not. */
const ASSUMED_WIDTH = 600;

/** The point marker's radius in px: the larger one is the hovered point. Both are
 *  SVG user units on a mark, not a CSS length on Arena's dimension scale, and the
 *  token layer models neither — `LineChart.jsx` writes the same two numbers, from
 *  tokens/src/chart.json. */
const POINT_R = chartPointR;
const POINT_R_HOVER = chartPointRHover;

/* Every static style below is a camelCase object bound with `[style]`, never a
 * `style="a-b:c"` string in the template, for the reason bar-chart.ts records at
 * length: check-dimension-literals.mjs finds a governed property by an unbroken
 * run of letters before a colon, so a kebab-case declaration in a template string
 * is either invisible to it (`font-size:` reads as a property named `size`) or
 * actively misread (`stroke-width:` reads as `width`, then runs the value scan off
 * into the rest of the template). An object gives the gate the same view of this
 * component that it has of React's `LineChart.jsx`, where every one of these is an
 * inline style object key. */

/** The grid lines, the baseline and the hover crosshair: a hairline at the token
 *  border width. */
const LINE_STYLE = { strokeWidth: 'var(--bw)' } as const satisfies Readonly<Record<string, string>>;

/** The series' own stroke weight, shared by the polyline and by the halo that rings
 *  each point in the card surface. One weight, so the marks read as one series. */
const SERIES_STROKE_STYLE = { strokeWidth: 'var(--bw-strong)' } as const satisfies Readonly<Record<string, string>>;

/** The value-axis tick labels, in mono at the micro size. */
const TICK_LABEL_STYLE = { fontSize: 'var(--dz-text-2xs)' } as const satisfies Readonly<Record<string, string>>;

/** The point labels along the bottom, in the body face one step up from the ticks. */
const POINT_LABEL_STYLE = { fontSize: 'var(--fs-xs)' } as const satisfies Readonly<Record<string, string>>;

/** The hover tooltip's surface. `left` and `top` are bound separately, because they
 *  are the only part of it computed from the data. */
const TOOLTIP_STYLE = {
  position: 'absolute', transform: 'translate(-50%,-100%)', pointerEvents: 'none',
  whiteSpace: 'nowrap', background: 'var(--bg-raised)',
  border: 'var(--bw) solid var(--border-strong)', borderRadius: 'var(--r-sm)',
  boxShadow: 'var(--shadow-2)', padding: 'calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2.5)',
} as const satisfies Readonly<Record<string, string>>;

/** The tooltip's point line — the quieter of its two rows. */
const TOOLTIP_LABEL_STYLE = {
  fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-xs)', color: 'var(--mute)',
} as const satisfies Readonly<Record<string, string>>;

/** The tooltip's value line, in mono so digits align between hovers. */
const TOOLTIP_VALUE_STYLE = {
  fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-md)', color: 'var(--bone)',
} as const satisfies Readonly<Record<string, string>>;

/** A plotted point's position in SVG coordinates. */
export interface ArenaLinePoint {
  /** Horizontal position, padding included — the same origin the SVG uses. */
  x: number;
  /** Vertical position, top-down. */
  y: number;
}

/** Where point `index` of `count` sits horizontally. A lone point centres in the
 *  plot rather than pinning to the left edge, which would read as a series that
 *  starts and stops immediately.
 *  @param index the 0-based point @param count how many points there are
 *  @param innerWidth the plot width in px, padding already removed
 *  @returns the x coordinate, measured from the SVG's own origin */
export function lineX(index: number, count: number, innerWidth: number): number {
  return PAD.l + (count <= 1 ? innerWidth / 2 : (innerWidth / (count - 1)) * index);
}

/** Projects a value onto the plot's pixel height, top-down: `0` lands on the
 *  baseline and `max` lands on the plot's top edge. Negative values clamp to the
 *  baseline, because a one-axis line chart has no room below it.
 *  @param value the datum @param max the axis top (always > 0, per `niceMax`)
 *  @param innerHeight the plot height in px, padding already removed
 *  @returns the y coordinate of the value */
export function lineValueY(value: number, max: number, innerHeight: number): number {
  return PAD.t + innerHeight - (Math.max(0, value) / max) * innerHeight;
}

/** The index of the point nearest a pointer position. One overlay owns the pointer,
 *  so the crosshair snaps to a real datum instead of drifting between two; per-point
 *  hit targets would leave dead gaps between them. Ties go to the earlier point.
 *  @param points the plotted points @param x the pointer's x, in SVG coordinates
 *  @returns the winning index, or -1 when there are no points */
export function nearestPointIndex(points: readonly ArenaLinePoint[], x: number): number {
  if (points.length === 0) return -1;
  let best = 0;
  for (let i = 1; i < points.length; i++) {
    if (Math.abs(points[i].x - x) < Math.abs(points[best].x - x)) best = i;
  }
  return best;
}

/** The series as an SVG `points` list for `<polyline>`.
 *  @param points the plotted points @returns the space-separated coordinate pairs */
export function linePoints(points: readonly ArenaLinePoint[]): string {
  return points.map((point) => `${point.x},${point.y}`).join(' ');
}

/** The filled area under the series: the line itself, closed down to the baseline at
 *  each end. Empty for an empty series, so nothing is painted rather than a stray
 *  `M`-only path.
 *  @param points the plotted points @param baseline the baseline's y coordinate
 *  @returns an SVG path `d`, or `''` when there is nothing to fill */
export function lineAreaPath(points: readonly ArenaLinePoint[], baseline: number): string {
  if (points.length === 0) return '';
  const line = points.map((point) => `${point.x},${point.y}`).join(' L');
  return `M${points[0].x},${baseline} L${line} L${points[points.length - 1].x},${baseline} Z`;
}

/** One series over time, with an optional area tint under it. Identity by `slot`, or
 *  meaning by `tone` — never both. One of the three hand-written SVG charts, so unlike
 *  every other primitive in this layer it carries styling of its own: a chart's visual
 *  identity is path data and presentation attributes, which a class string cannot
 *  hold. Every value in it is still a token.
 *
 *  The host is both the box `containerWidth()` measures and the containing block the
 *  tooltip is positioned against, so it declares `display:block` explicitly:
 *  `<arena-line-chart>` is an unknown element whose UA default is `display:inline`,
 *  and a non-replaced inline box has no content width for a `ResizeObserver` to
 *  report — every point would be laid out against the wrong number. This is the same
 *  hazard the manifest-driven display utility guards for every other primitive; a
 *  chart has no manifest, so it states the display itself. */
@Component({
  selector: 'arena-line-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display:block;position:relative',
    '[style.height.px]': 'height',
  },
  template: `
    <svg width="100%" [attr.height]="height" role="img" [attr.aria-label]="name()"
         style="display:block;overflow:visible">
      @for (tick of gridLines(); track tick.value) {
        <g>
          <line [attr.x1]="pad.l" [attr.x2]="width() - pad.r" [attr.y1]="tick.y" [attr.y2]="tick.y"
                stroke="var(--border)" [style]="lineStyle" />
          <text [attr.x]="tickLabelX" [attr.y]="tick.y" text-anchor="end" dominant-baseline="middle"
                fill="var(--text-muted)" font-family="var(--font-mono)"
                [style]="tickLabelStyle">{{ tick.label }}</text>
        </g>
      }
      <line [attr.x1]="pad.l" [attr.x2]="width() - pad.r" [attr.y1]="baseline()" [attr.y2]="baseline()"
            stroke="var(--line-strong)" [style]="lineStyle" />

      @if (area() && points().length > 0) {
        <path [attr.d]="areaPath()" [attr.fill]="areaFill()" stroke="none" />
      }

      @if (active(); as point) {
        <line [attr.x1]="point.x" [attr.x2]="point.x" [attr.y1]="pad.t" [attr.y2]="baseline()"
              stroke="var(--border-strong)" stroke-dasharray="3 3" [style]="lineStyle" />
      }

      @if (points().length > 1) {
        <polyline [attr.points]="polyline()" fill="none" [attr.stroke]="color()"
                  stroke-linejoin="round" stroke-linecap="round" [style]="seriesStrokeStyle" />
      }

      @for (point of points(); track point.index) {
        <circle [attr.cx]="point.x" [attr.cy]="point.y"
                [attr.r]="hover() === point.index ? pointRHover : pointR"
                [attr.fill]="color()" stroke="var(--surface-card)" [style]="seriesStrokeStyle" />
      }

      @for (point of points(); track point.index) {
        <text [attr.x]="point.x" [attr.y]="pointLabelY" text-anchor="middle"
              fill="var(--text-muted)" font-family="var(--font-body)"
              [style]="pointLabelStyle">{{ point.label }}</text>
      }

      <rect [attr.x]="pad.l" [attr.y]="pad.t" [attr.width]="innerWidth()" [attr.height]="innerHeight()"
            fill="transparent" (mousemove)="onMove($event)" (mouseleave)="hover.set(null)" />
    </svg>

    @if (active(); as point) {
      <div [style]="tooltipStyle" [style.left.px]="point.x"
           [style.top]="'calc(' + point.y + 'px - calc(var(--sp-1) * 2.5))'">
        <div [style]="tooltipLabelStyle">{{ point.label }}</div>
        <div [style]="tooltipValueStyle">{{ point.formatted }}</div>
      </div>
    }

    <table [style]="srOnly">
      <caption>{{ name() }}</caption>
      <thead><tr><th>Point</th><th>{{ seriesLabel() ?? 'Value' }}</th></tr></thead>
      <tbody>
        @for (point of points(); track point.index) {
          <tr><th scope="row">{{ point.label }}</th><td>{{ point.formatted }}</td></tr>
        }
      </tbody>
    </table>
  `,
})
export class LineChart {
  readonly labels = input.required<string[]>();
  readonly values = input.required<number[]>();
  readonly seriesLabel = input<string>();
  readonly slot = input<number>();
  readonly tone = input<SeriesTone>();
  readonly area = input(false, { transform: booleanAttribute });
  readonly valueSuffix = input<string>();

  protected readonly height = CHART_HEIGHT;
  protected readonly pad = PAD;
  protected readonly srOnly = SR_ONLY;
  protected readonly lineStyle = LINE_STYLE;
  protected readonly seriesStrokeStyle = SERIES_STROKE_STYLE;
  protected readonly tickLabelStyle = TICK_LABEL_STYLE;
  protected readonly pointLabelStyle = POINT_LABEL_STYLE;
  protected readonly tooltipStyle = TOOLTIP_STYLE;
  protected readonly tooltipLabelStyle = TOOLTIP_LABEL_STYLE;
  protected readonly tooltipValueStyle = TOOLTIP_VALUE_STYLE;
  protected readonly pointR = POINT_R;
  protected readonly pointRHover = POINT_R_HOVER;
  protected readonly tickLabelX = PAD.l - 8;
  protected readonly pointLabelY = CHART_HEIGHT - 8;
  protected readonly hover = signal<number | null>(null);

  /** The unit appended to every number this chart draws — the axis ticks, the
   *  tooltip and the accessible table alike. Appended verbatim: the caller owns
   *  the leading space. `private`, so the reader never sees it as a member. */
  private readonly suffix = computed(() => this.valueSuffix() ?? '');

  private readonly measured = containerWidth();
  /** Wide first paint, then measured — the narrow branch never flashes. */
  protected readonly width = computed(() => this.measured() ?? ASSUMED_WIDTH);

  /** One series, one colour — `resolveColors` still owns the identity/meaning rule. */
  protected readonly color = computed(() => resolveColors({ slot: this.slot(), tone: this.tone(), count: 1 })[0]);
  /** The area is the series colour at 18% — a tint of the line, never a gradient. */
  protected readonly areaFill = computed(() => `color-mix(in oklab, ${this.color()} 18%, transparent)`);

  protected readonly name = computed(() => {
    const series = this.seriesLabel();
    return series ? `${series} — line chart` : 'Line chart';
  });

  private readonly max = computed(() => niceMax(Math.max(0, ...this.values())));
  protected readonly innerWidth = computed(() => Math.max(1, this.width() - PAD.l - PAD.r));
  protected readonly innerHeight = computed(() => Math.max(1, this.height - PAD.t - PAD.b));
  protected readonly baseline = computed(() => PAD.t + this.innerHeight());

  protected readonly gridLines = computed(() => {
    const max = this.max();
    const innerHeight = this.innerHeight();
    const suffix = this.suffix();
    return ticks(max).map((value) => ({ value, y: lineValueY(value, max, innerHeight), label: `${value}${suffix}` }));
  });

  protected readonly points = computed(() => {
    const values = this.values();
    const max = this.max();
    const innerWidth = this.innerWidth();
    const innerHeight = this.innerHeight();
    const suffix = this.suffix();
    return values.map((value, index) => ({
      index,
      x: lineX(index, values.length, innerWidth),
      y: lineValueY(value, max, innerHeight),
      label: this.labels()[index] ?? '',
      formatted: `${value}${suffix}`,
    }));
  });

  protected readonly polyline = computed(() => linePoints(this.points()));
  protected readonly areaPath = computed(() => lineAreaPath(this.points(), this.baseline()));

  protected readonly active = computed(() => {
    const index = this.hover();
    return index === null ? null : this.points()[index] ?? null;
  });

  /** Snaps the crosshair to the point nearest the pointer.
   *  @param event the pointer move over the plot overlay */
  protected onMove(event: MouseEvent): void {
    // Measured against the SVG's box, not the overlay rect's: `point.x` already
    // carries PAD.l, so comparing it to a rect-relative x would snap a whole left
    // pad early. React measures against the rect and has exactly that bug.
    const box = (event.currentTarget as SVGRectElement).ownerSVGElement?.getBoundingClientRect();
    if (!box) return;
    const index = nearestPointIndex(this.points(), event.clientX - box.left);
    if (index >= 0) this.hover.set(index);
  }
}
