// frameworks/react/components/feedback/alert/Alert.jsx
import React from 'react';
const TONES = {
  info:    { color: 'var(--info)',    soft: 'var(--info-soft)',    icon: 'ph-fill ph-info' },
  success: { color: 'var(--success)', soft: 'var(--success-soft)', icon: 'ph-fill ph-check-circle' },
  warning: { color: 'var(--warning)', soft: 'var(--warning-soft)', icon: 'ph-fill ph-warning' },
  danger:  { color: 'var(--danger)',  soft: 'var(--danger-soft)',  icon: 'ph-fill ph-warning-octagon' },
  neutral: { color: 'var(--line-strong)', soft: 'var(--panel)',    icon: 'ph-fill ph-note' },
};
/** Persistent message embedded in the page (not ephemeral). Unlike Toast, it stays
 * until the condition is resolved. Use `tone` for severity; `actionLabel` +
 * `onAction` add an inline action; `dismissible` shows the × (single Phosphor
 * ph-x close icon) and `onClose` handles it. */
export function Alert({ tone = 'info', title, children, icon, actionLabel, onAction, dismissible, onClose }) {
  const t = TONES[tone] || TONES.info;
  return (
    <div role={tone === 'danger' ? 'alert' : 'status'}
      style={{ display: 'flex', gap: 'calc(var(--sp-1) * 3)', alignItems: 'flex-start', padding: 'calc(var(--sp-1) * 3.5) calc(var(--sp-1) * 4)',
        background: t.soft, border: 'var(--bw) solid ' + t.color, borderRadius: 'var(--r-md)' }}>
      <i className={icon || t.icon} style={{ color: t.color, fontSize: 'var(--icon-lg)', lineHeight: 'var(--dz-lh)', flexShrink: 0, marginTop: 0 }} />
      <div style={{ flex: 1 }}>
        {title && <div style={{ fontFamily: 'var(--font-body)', fontWeight: 'var(--fw-semibold)', fontSize: 'var(--dz-text)', color: 'var(--bone)' }}>{title}</div>}
        {children && <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--fs-sm)', color: 'var(--bone-dim)', lineHeight: 'var(--lh-body)', marginTop: title ? 'var(--sp-1)' : 0 }}>{children}</div>}
        {actionLabel && (
          <button onClick={onAction}
            style={{ marginTop: 'calc(var(--sp-1) * 2.5)', background: 'none', border: 'none', padding: 0, cursor: 'pointer',
              fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', fontWeight: 'var(--fw-bold)', letterSpacing: 'var(--ls-uppercase-status)', textTransform: 'uppercase', color: t.color }}>
            {actionLabel}
          </button>
        )}
      </div>
      {dismissible && (
        <button onClick={onClose} aria-label="Dismiss"
          style={{ display: 'inline-flex', alignItems: 'center', background: 'none', border: 'none', color: 'var(--mute)', cursor: 'pointer', fontSize: 'var(--icon-md)', lineHeight: 'var(--dz-lh)' }}>
          <i className="ph-bold ph-x" />
        </button>
      )}
    </div>
  );
}

// frameworks/angular/primitives/alert/alert.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { alertStyles } from './alert.variants';

type Tone = 'info' | 'success' | 'warning' | 'danger' | 'neutral';

const TONE_ICONS: Record<Tone, string> = {
  info: 'ph-fill ph-info',
  success: 'ph-fill ph-check-circle',
  warning: 'ph-fill ph-warning',
  danger: 'ph-fill ph-warning-octagon',
  neutral: 'ph-fill ph-note',
};

/** Persistent in-page message; unlike a toast it stays until the condition it
 *  reports is resolved. The host itself is the recipe's `root` — it is the
 *  flex item a parent lays out, so root-level classes and the `role` they
 *  imply must live on the host, not one element inside it. `tone="danger"`
 *  renders `role="alert"`, which interrupts a screen reader; every other
 *  tone renders `role="status"`. */
@Component({
  selector: 'arena-alert',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.role]': "tone() === 'danger' ? 'alert' : 'status'",
  },
  template: `
    <i [class]="styles().icon() + ' ' + (icon() ?? toneIcon())" aria-hidden="true"></i>
    <div [class]="styles().body()">
      @if (title(); as heading) {
        <div [class]="styles().title()">{{ heading }}</div>
      }
      <div [class]="styles().message()"><ng-content /></div>
      @if (actionLabel(); as label) {
        <button type="button" [class]="styles().action()" (click)="action.emit()">{{ label }}</button>
      }
    </div>
    @if (dismissible()) {
      <button type="button" [class]="styles().close()" aria-label="Dismiss" (click)="closed.emit()">
        <i class="ph-bold ph-x" aria-hidden="true"></i>
      </button>
    }
  `,
})
export class Alert {
  readonly tone = input<Tone>('info');
  readonly title = input<string>();
  readonly icon = input<string>();
  readonly actionLabel = input<string>();
  readonly dismissible = input(false);
  readonly action = output<void>();
  readonly closed = output<void>();

  protected readonly styles = computed(() => alertStyles({ tone: this.tone() }));
  protected readonly toneIcon = computed(() => TONE_ICONS[this.tone()]);
}
