// frameworks/angular/components/navigation/side-nav/SideNav.ts
import {
  ChangeDetectionStrategy, Component, computed, inject, input, numberAttribute, output, signal,
} from '@angular/core';
import { SideNavState } from './SideNavState';
import { sideNavStyles } from './SideNav.variants';

@Component({
  selector: 'arena-side-nav',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [SideNavState],
  host: {
    '[class]': 'styles().root()',
    role: 'navigation',
    '[attr.aria-label]': 'label()',
  },
  template: `<ng-content />`,
})
export class SideNav {
  /** The id of the current destination. The SideNavItem whose id matches is marked aria-current="page", and no item is marked when it names none of them. */
  readonly active = input<string>();
  /** Names this navigation landmark. Required, and guarded at runtime: the guard trims before it decides, so a blank name is refused as well as an absent one, because ariaLabel="" renders a landmark with no accessible name, which is the defect arriving through a value that is present. Guarded rather than defaulted: the navigation pattern asks each landmark on a page for a UNIQUE name, and a constant default satisfies the existence half while two sidebars on one page stay indistinguishable. Nothing can derive it either; what a nav is FOR is editorial. Say what it navigates -- "Primary", "Project settings" -- the Table.label and SegmentedControl.ariaLabel shape. */
  readonly ariaLabel = input.required<string>();
  /** How far each nesting level indents, as a MULTIPLIER of --sp-1 rather than a length: the row at depth N is padded calc(var(--sp-1) * 3 + var(--sp-1) * indentStep * N). A CSS string was rejected -- a caller-supplied "1.5rem" is neither a token nor a derivation of one, so it would stop re-densifying inside .arena-compact, and no gate would catch it because the gate that forbids a bare length scans source and not the values a caller passes in. */
  readonly indentStep = input(3, { transform: numberAttribute });
  /** An item was activated, carrying its id. It carries the id alone, on the Breadcrumbs precedent that the platform event leaves the payload and the item travels by itself, and under the compound shape there is no item datum left to carry either, because the consumer wrote the element and already holds everything on it. Where the item has an href, Arena has already cancelled the anchor by the time this fires, so a listener routes and does not double-navigate; ctrl-click, middle-click and open-in-new-tab are the browser's and fire nothing, so a consumer who wires no listener still has a working column of real links. */
  readonly nav = output<string>();

  private readonly state = inject(SideNavState);

  protected readonly label = computed(() => {
    const name = this.ariaLabel();
    if (name.trim() === '') {
      throw new Error('SideNav: `ariaLabel` is required, and names which navigation this landmark is');
    }
    return name;
  });

  protected readonly styles = computed(() => sideNavStyles());

  constructor() {
    this.state.depth = signal(0);
    this.state.activeId = this.active;
    this.state.indentStep = this.indentStep;
    this.state.activate = (id: string) => this.nav.emit(id);
  }
}

// frameworks/react/components/navigation/SideNav.jsx
import React from 'react';
import { injectInto, COLUMN } from './side-nav-inject.jsx';

/** The sidebar's navigation list -- the list alone, not the frame around it.
 *  See the Non-goals in the source spec for why there is no AppShell.
 *
 *  A COMPOUND component. The consumer writes one <SideNavItem> per destination,
 *  optionally grouped by <SideNavSection> and <SideNavCollapsible>; SideNav walks
 *  its direct children and injects where each sits, which id is active and the
 *  handler that reports `nav`. None of what it injects is a member of any
 *  contract -- the Table/TableRow shape, one size down. */
export function SideNav({ children, active, ariaLabel, indentStep = 3, onNav }) {
  /* Falsy, not absence-only: `ariaLabel=""` renders <nav aria-label="">, a
   * landmark with NO accessible name -- exactly the defect the guard exists to
   * prevent, arriving through a value that is present. An accessible name is
   * guarded rather than defaulted because the constant default was itself the
   * defect: the navigation pattern asks each landmark on a page for a UNIQUE
   * name, two sidebars sharing one are indistinguishable, and nothing can derive
   * what a nav is for. */
  if (!ariaLabel) throw new Error('SideNav: `ariaLabel` is required');
  return (
    <nav aria-label={ariaLabel} style={COLUMN}>
      {injectInto(children, { depth: 0, activeId: active, indentStep, onActivate: onNav })}
    </nav>
  );
}
