// frameworks/angular/components/navigation/side-nav-collapsible/SideNavCollapsible.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, contentChildren, effect,
  forwardRef, inject, input, output, signal, untracked,
} from '@angular/core';
import { SideNavChild, SideNavState, indentFor } from '../side-nav/SideNavState';
import { sideNavStyles } from '../side-nav/SideNav.variants';
import { SideNavItem } from '../side-nav-item/SideNavItem';

@Component({
  selector: 'arena-side-nav-collapsible',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    SideNavState,
    { provide: SideNavChild, useExisting: forwardRef(() => SideNavCollapsible) },
  ],
  host: {
    '[class]': 'styles().section()',
    '[attr.id]': 'null',
  },
  template: `
    <button type="button" [id]="triggerId()" [class]="styles().trigger()"
            [style.paddingInlineStart]="indent()"
            [attr.aria-expanded]="expanded()" [attr.aria-controls]="regionId()"
            (click)="press()" (keydown)="onKeydown($event)">
      @if (icon(); as glyph) {
        <i [class]="styles().icon() + ' ' + glyph" aria-hidden="true"></i>
      }
      <span [class]="styles().triggerLabel()">{{ heading() }}</span>
      <i [class]="styles().caret() + ' ' + caretGlyph()" aria-hidden="true"></i>
    </button>
    <div [id]="regionId()" [class]="styles().region()" role="group"
         [attr.aria-labelledby]="triggerId()" [hidden]="!expanded()">
      <ng-content />
    </div>
  `,
})
export class SideNavCollapsible {
  /** Identifies the group. The disclosure pattern needs two DOM ids that resolve -- the trigger's aria-controls must name the region, and the region's aria-labelledby must name the trigger -- and Arena derives both from this member, as `${id}-trigger` and `${id}-region`. Neither wiring is conditional: every collapsible has a trigger and a region, so there is no shape in which the id goes unused, and that is why it is required rather than optional. A group is a thing a consumer names anyway. Falsy-guarded as well as required: a blank id yields the pair `-trigger`/`-region`, which every other blank-id collapsible on the page would share, and duplicate ids make aria-controls resolve to the wrong element rather than to none. A consumer can address either element from outside as a consequence -- an aria-describedby, a deep link, a test hook -- but that is a benefit of the derivation, not the reason for it. */
  readonly id = input.required<string>();
  /** What the trigger reads, and the accessible name of both the trigger and the region it controls. Required and falsy-guarded. */
  readonly label = input.required<string>();
  /** A Phosphor class name drawn before the label. The caret that reports expanded-ness is Arena's own and is not this member. */
  readonly icon = input<string>();
  /** Whether the group starts open. It is a seed, not a control: after the first render the state is the component's, and the group also opens itself when it comes to hold the active destination. */
  readonly defaultExpanded = input(false, { transform: booleanAttribute });
  /** The trigger was pressed, carrying the state it moved to. It fires on a press ONLY: the automatic expansion that follows the active destination is Arena's decision rather than the user's, and reporting it here would be a lie a consumer persists. */
  readonly toggle = output<boolean>();

  private readonly parent = inject(SideNavState, { skipSelf: true });
  private readonly own = inject(SideNavState);
  private readonly items = contentChildren(SideNavItem, { descendants: true });
  private readonly open = signal<boolean | null>(null);

  protected readonly triggerId = computed(() => `${this.key()}-trigger`);
  protected readonly regionId = computed(() => `${this.key()}-region`);
  protected readonly expanded = computed(() => this.open() ?? (this.defaultExpanded() || this.holdsActive()));
  protected readonly caretGlyph = computed(() => (this.expanded() ? 'ph-bold ph-caret-down' : 'ph-bold ph-caret-right'));

  protected readonly holdsActive = computed(() => {
    const active = this.parent.activeId();
    return active !== undefined && this.items().some((item) => item.id() === active);
  });

  protected readonly heading = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('SideNavCollapsible: `label` is required, and names the group its trigger opens');
    }
    return text;
  });

  protected readonly indent = computed(() => indentFor(this.parent.indentStep(), this.parent.depth()));
  protected readonly styles = computed(() => sideNavStyles());

  constructor() {
    this.own.depth = computed(() => this.parent.depth() + 1);
    this.own.activeId = this.parent.activeId;
    this.own.indentStep = this.parent.indentStep;
    this.own.activate = (id: string) => this.parent.activate(id);

    effect(() => {
      const holds = this.holdsActive();
      untracked(() => {
        if (holds) this.open.set(true);
      });
    });
  }

  protected press(): void {
    const next = !this.expanded();
    this.open.set(next);
    this.toggle.emit(next);
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    this.press();
  }

  private key(): string {
    const id = this.id();
    if (id.trim() === '') {
      throw new Error('SideNavCollapsible: `id` is required, and is what its trigger and its region are named from');
    }
    return id;
  }
}

// frameworks/react/components/navigation/SideNavCollapsible.jsx
import React, { useEffect, useState } from 'react';
import { injectInto, indentFor } from './side-nav-inject.jsx';
import { SideNavItem } from './SideNavItem.jsx';

/** Whether `id` names a SideNavItem anywhere in this subtree.
 *
 *  Matched by element TYPE and not by `props.id` alone: a collapsible carries an
 *  id of its own, and a consumer who names a group after a destination has not
 *  said the group IS that destination. Importing SideNavItem for the comparison
 *  makes no cycle -- SideNavItem imports only the shared helpers.
 *
 *  Exported so its own test can exercise it without a render.
 *  @param {React.ReactNode} children @param {string} [id] */
export function subtreeHasItem(children, id) {
  if (!id) return false;
  for (const child of React.Children.toArray(children)) {
    if (!React.isValidElement(child)) continue;
    if (child.type === SideNavItem && child.props.id === id) return true;
    if (subtreeHasItem(child.props.children, id)) return true;
  }
  return false;
}

/** A named group that shows and hides its own contents. Binds the `disclosure`
 *  pattern: a real <button> carrying aria-expanded, with aria-controls naming the
 *  region it toggles.
 *
 *  IT IS NOT A TREEVIEW, and the binding says so. With arbitrary nesting the
 *  structure resembles one, and APG's treeview would demand aria-level on every
 *  node, a roving tab stop and four-direction arrow navigation. None of that is
 *  designed here: each collapsible is an independent disclosure, which is what
 *  production sidebars ship and what a nav landmark full of links actually is. */
export function SideNavCollapsible({
  id, label, icon, defaultExpanded = false, children, onToggle,
  depth = 0, activeId, indentStep = 3, onActivate,
}) {
  /* Falsy rather than absence-only, the same operator decision SideNavItem's
   * guards carry: `label` is the trigger's whole accessible name and `id` is
   * what both DOM ids are derived from, so a present-but-blank value IS the
   * defect -- a blank id would produce the pair "-trigger"/"-region", which two
   * blank-id collapsibles on one page would share. */
  if (!id) throw new Error('SideNavCollapsible: `id` is required');
  if (!label) throw new Error('SideNavCollapsible: `label` is required');

  const holdsActive = subtreeHasItem(children, activeId);
  /* Seeded AND effected, and both halves are load-bearing. Seeding alone never
   * reopens the group when the route moves into it; an effect alone renders the
   * active destination HIDDEN in a server pass, because effects do not run under
   * renderToStaticMarkup. Together they open it on first paint and on every later
   * transition into holding the active id -- and leave the user free to collapse
   * it again, which a derived `expanded || holdsActive` would not. */
  const [expanded, setExpanded] = useState(defaultExpanded || holdsActive);
  useEffect(() => { if (holdsActive) setExpanded(true); }, [holdsActive]);

  /* Derived from the required `id` rather than from useId(). The pattern needs two
   * ids that resolve -- the trigger's aria-controls names the region, the region's
   * aria-labelledby names the trigger -- and neither wiring is conditional, so
   * there is no shape where the id goes unused. A useId value would satisfy both
   * of those and be unaddressable from outside, which is the secondary reason;
   * the first is simply that a group is a thing the consumer names.
   *
   * NOT the api/README.md `id`-member rule, which points the other way: that rule
   * is about a component that GENERATES an id and thereby takes the consumer's
   * only path to the element away, and its remedy is an OPTIONAL `id?: string`
   * with the generated value as fallback (the Input/Textarea shape). This
   * component generates nothing, so that rule's premise does not hold here and it
   * is not the authority for a required member. SideNavSection is the sibling
   * case -- its label id is internal, nothing outside needs to name it, so it uses
   * useId and declares no member at all. */
  const regionId = `${id}-region`;
  const triggerId = `${id}-trigger`;

  /* `toggle` reports the BUTTON PRESS only. The auto-expand above is Arena's
   * decision, not the user's, and reporting it as one would be a lie a consumer
   * persists. */
  const press = () => {
    const next = !expanded;
    setExpanded(next);
    if (onToggle) onToggle(next);
  };

  const glyph = icon
    ? <i className={icon} aria-hidden="true" style={{ fontSize: 'var(--icon-lg)', display: 'inline-flex' }} />
    : null;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-1)' }}>
      <button id={triggerId} type="button" aria-expanded={expanded} aria-controls={regionId}
        onClick={press}
        style={{
          display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 3)',
          paddingBlock: 'calc(var(--sp-1) * 2.5)',
          paddingInlineEnd: 'calc(var(--sp-1) * 3)',
          paddingInlineStart: indentFor(indentStep, depth),
          borderRadius: 'var(--r-sm)', background: 'transparent', color: 'var(--mute)',
          border: 'none', cursor: 'pointer', textAlign: 'left',
          fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text)', fontWeight: 'var(--fw-medium)',
        }}>
        {glyph}
        <span style={{ flex: 1 }}>{label}</span>
        <i className={expanded ? 'ph-bold ph-caret-down' : 'ph-bold ph-caret-right'}
          aria-hidden="true" style={{ fontSize: 'var(--icon-md)', display: 'inline-flex' }} />
      </button>
      {/* `hidden` AND display, never one of them -- an inline display:flex beats
          [hidden]'s UA display:none, and hidden alone would lose the column. */}
      <div id={regionId} role="group" aria-labelledby={triggerId} hidden={!expanded}
        style={{ display: expanded ? 'flex' : 'none', flexDirection: 'column', gap: 'var(--sp-1)' }}>
        {injectInto(children, { depth: depth + 1, activeId, indentStep, onActivate })}
      </div>
    </div>
  );
}
