// frameworks/angular/components/forms/arena-switch/ArenaSwitch.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output,
} from '@angular/core';
import type { ArenaOrientation, ArenaSwitchSize } from '../../../Api.generated';
import { arenaSwitchStyles } from './ArenaSwitch.variants';

export type SwitchFootprint = `${ArenaOrientation}-${ArenaSwitchSize}`;
export type SwitchThumb = `${'on' | 'off'}-${ArenaOrientation}`;

export function footprintFor(orientation: ArenaOrientation, size: ArenaSwitchSize): SwitchFootprint {
  return `${orientation}-${size}`;
}

export function thumbFor(state: boolean, orientation: ArenaOrientation): SwitchThumb {
  return `${state ? 'on' : 'off'}-${orientation}`;
}

@Component({
  selector: 'arena-switch',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    <button type="button" role="switch" [class]="styles().track()"
            [attr.aria-checked]="state()" [attr.aria-label]="label()"
            [disabled]="disabled()" (click)="activate()">
      <span [class]="styles().knob()" aria-hidden="true">
        @if (glyph()) {
          <i [class]="glyphClass()" aria-hidden="true"></i>
        }
      </span>
    </button>
    <span [class]="styles().label()" (click)="activate()">
      {{ label() }}
      @if (confirm()) {
        <i [class]="guardClass()" aria-hidden="true" title="Requires confirmation"></i>
      }
    </span>
  `,
})
export class ArenaSwitch {
  /** The current on/off value. Controlled: the consumer owns it and pushes it each render. */
  readonly state = input(false, { transform: booleanAttribute });
  /** Whether the switch lies horizontally or stands vertically. */
  readonly orientation = input<ArenaOrientation>('horizontal');
  /** The switch's overall size. */
  readonly size = input<ArenaSwitchSize>('md');
  /** A Phosphor class name for the glyph shown while on. Arena draws the aria-hidden `<i>`. */
  readonly iconOn = input<string>();
  /** A Phosphor class name for the glyph shown while off. */
  readonly iconOff = input<string>();
  /** The accessible name for the switch, also drawn beside it. */
  readonly label = input.required<string>();
  /** Whether the switch is inoperable. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** When set, a change is not applied on the fly; it is requested through `requestChange` so the host can confirm it first. */
  readonly confirm = input(false, { transform: booleanAttribute });
  /** The switch was turned on. */
  readonly funcOn = output<void>();
  /** The switch was turned off. */
  readonly funcOff = output<void>();
  /** A change was requested while `confirm` is set: the host opens an ArenaConfirmDialog and, on confirmation, flips `state` (the requested value is always the negation of the current one). */
  readonly requestChange = output<void>();

  protected readonly glyph = computed(() => (this.state() ? this.iconOn() : this.iconOff()));

  protected readonly styles = computed(() => arenaSwitchStyles({
    size: this.size(),
    orientation: this.orientation(),
    checked: this.state(),
    disabled: this.disabled(),
    footprint: footprintFor(this.orientation(), this.size()),
    thumb: thumbFor(this.state(), this.orientation()),
  }));

  protected readonly glyphClass = computed(() => `${this.styles().icon()} ${this.glyph() ?? ''}`.trim());
  protected readonly guardClass = computed(() => `ph-bold ph-shield-check ${this.styles().guard()}`);

  protected activate(): void {
    if (this.disabled()) return;
    if (this.confirm()) {
      this.requestChange.emit();
      return;
    }
    if (this.state()) this.funcOff.emit();
    else this.funcOn.emit();
  }
}

// frameworks/react/components/forms/arena-switch/ArenaSwitch.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaSwitch.classes.generated.ts';

import type { ArenaOrientation, ArenaSwitchSize } from '../../../Api.generated';

export interface ArenaSwitchProps {
  /** The current on/off value. Controlled: the consumer owns it and pushes it each render. */
  state?: boolean;
  /** Whether the switch lies horizontally or stands vertically. */
  orientation?: ArenaOrientation;
  /** The switch's overall size. */
  size?: ArenaSwitchSize;
  /** A Phosphor class name for the glyph shown while on. Arena draws the aria-hidden `<i>`. */
  iconOn?: string;
  /** A Phosphor class name for the glyph shown while off. */
  iconOff?: string;
  /** The accessible name for the switch, also drawn beside it. */
  label: string;
  /** Whether the switch is inoperable. */
  disabled?: boolean;
  /** When set, a change is not applied on the fly; it is requested through `requestChange` so the host can confirm it first. */
  confirm?: boolean;
  /** The switch was turned on. */
  onFuncOn?: () => void;
  /** The switch was turned off. */
  onFuncOff?: () => void;
  /** A change was requested while `confirm` is set: the host opens an ArenaConfirmDialog and, on confirmation, flips `state` (the requested value is always the negation of the current one). */
  onRequestChange?: () => void;
}


const arenaSwitchStyles = arenaStyles(manifest);

export function ArenaSwitch({
  state = false, orientation = 'horizontal', size = 'md',
  iconOn, iconOff, label, disabled = false, confirm = false,
  onFuncOn, onFuncOff, onRequestChange,
}: ArenaSwitchProps) {
  if (!label) throw new Error('ArenaSwitch: `label` is required (a switch must have an accessible name)');
  const icon = state ? iconOn : iconOff;
  const styles = arenaSwitchStyles({
    size,
    orientation,
    checked: state,
    disabled,
    footprint: `${orientation}-${size}`,
    thumb: `${state ? 'on' : 'off'}-${orientation}`,
  });

  const activate = () => {
    if (disabled) return;
    if (confirm) { onRequestChange && onRequestChange(); return; }
    if (state) { onFuncOff && onFuncOff(); } else { onFuncOn && onFuncOn(); }
  };

  return (
    <span className={styles.root()}>
      <button type="button" role="switch" aria-checked={state} aria-label={label} disabled={disabled} onClick={activate}
        className={styles.track()}>
        <span aria-hidden="true" className={styles.knob()}>
          {icon && <i aria-hidden="true" className={`${icon} ${styles.icon()}`} />}
        </span>
      </button>
      {label && (
        <span onClick={activate} className={styles.label()}>
          {label}
          {confirm && <i className={`ph-bold ph-shield-check ${styles.guard()}`} aria-hidden="true" title="Requires confirmation" />}
        </span>
      )}
    </span>
  );
}
