// frameworks/angular/primitives/avatar/avatar.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { avatarStyles } from './avatar.variants';

type Size = 'xs' | 'sm' | 'md' | 'lg';
type Shape = 'circle' | 'rounded';
type Status = 'online' | 'busy' | 'away' | 'offline';

/** Person or entity mark — the image when `src` is set, initials from `name` otherwise. */
@Component({
  selector: 'arena-avatar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [class]="styles().root()">
      <span [class]="styles().box()">
        @if (src(); as source) {
          <img [src]="source" [alt]="name()" [class]="styles().image()" />
        } @else {
          {{ initials() }}
        }
      </span>
      @if (status(); as presence) {
        <span [class]="styles().status()" [attr.aria-label]="presence" [title]="presence"></span>
      }
    </span>
  `,
})
export class Avatar {
  readonly src = input<string>();
  readonly name = input('');
  readonly size = input<Size>('md');
  readonly shape = input<Shape>('circle');
  readonly status = input<Status>();

  protected readonly styles = computed(() =>
    avatarStyles({ size: this.size(), shape: this.shape(), status: this.status() ?? 'none' }));

  protected readonly initials = computed(() =>
    this.name().trim().split(/\s+/).slice(0, 2).map((word) => word[0] ?? '').join('').toUpperCase());
}

// frameworks/react/components/display/avatar/Avatar.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Avatar.manifest.generated.ts';

import type { AvatarSize, AvatarShape, AvatarStatus } from '../../../Api.generated';

export interface AvatarProps {
  /** Image URL. Absent renders initials from `name`. */
  src?: string;
  /** The person or entity name. Its first two words' initials render when there is no `src`, and it is the image's alt text. */
  name?: string;
  /** The avatar's diameter. */
  size?: AvatarSize;
  /** Circle for a person, rounded for a team. */
  shape?: AvatarShape;
  /** A presence dot in the state's colour. `offline` is a visible muted dot; omit `status` entirely for no dot. Optional: there is no invisible enum value. */
  status?: AvatarStatus;
}

const avatarStyles = tv(manifest);
const STATUSES = Object.keys(manifest.variants.status);
type Status = keyof typeof manifest.variants.status;
const statusOf = (status: string | undefined): Status | undefined =>
  (status && STATUSES.includes(status) ? status as Status : 'offline');

export function Avatar({ src, name = '', size = 'md', shape = 'circle', status }: AvatarProps) {
  const initials = name.trim().split(/\s+/).slice(0, 2).map((w) => w[0] || '').join('').toUpperCase();
  const styles = avatarStyles({ size, shape, status: status ? statusOf(status) : 'none' });
  return (
    <span className={styles.root()}>
      <span className={styles.box()}>
        {src ? <img src={src} alt={name} className={styles.image()} /> : initials}
      </span>
      {status && <span aria-label={status} title={status} className={styles.status()} />}
    </span>
  );
}
