// frameworks/react/components/forms/button/Button.tsx
import React from 'react';

import type { ButtonType, ButtonVariant, ControlSize } from '../../../Api.generated';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Button.manifest.generated.ts';

export interface ButtonProps {

  /** The button's label. Sits between the two icons when both are given. */
  children?: React.ReactNode;
  /** Which action this is. Danger is outline, never filled. */
  variant?: ButtonVariant;
  /** Height, from the density tokens, so the button re-densifies inside .arena-compact. */
  size?: ControlSize;

  /** Phosphor class name drawn before the label. Replaced by the spinner while loading. */
  icon?: string;

  /** Phosphor class name drawn after the label: a caret on a menu trigger, an arrow on a next action. */
  iconRight?: string;

  /** Replaces the leading icon with a spinner and blocks activation. The spin slows under reduced motion rather than stopping: a frozen spinner reads as a hung process. */
  loading?: boolean;

  /** Stretches to the container's width. */
  full?: boolean;
  /** Blocks activation and dims the control. Implied by loading. */
  disabled?: boolean;

  /** Native button behaviour. Defaults to 'button' so a button inside a form does not submit it by accident. */
  type?: ButtonType;

  /** Submitted with the form, when the button submits one. */
  name?: string;

  /** The value submitted under `name`. */
  value?: string;

  /** Focused on mount. */
  autoFocus?: boolean;

  /** The id of the form this button belongs to, when it is not a descendant of it. */
  form?: string;

  /** Whether the control is reached from the page's Tab sequence. Set false when it lives inside a composite that manages its own focus (a grid with a roving tab stop, a menu), where reaching it by Tab would be a second way in. Arena writes tabindex="-1" and the control stays programmatically focusable; a positive tab order is not expressible and never should be. Table's actions column is where this one is needed: a Button inside a row of a grid. */
  tabStop?: boolean;

  /** The button was activated, by pointer or by keyboard. */
  onClick?: () => void;
}


const buttonStyles = tv(manifest);

export function Button({
  children, variant = 'primary', size = 'md', icon, iconRight,
  disabled = false, loading = false, full = false,
  type = 'button', name, value, autoFocus = false, form, onClick, tabStop = true,
}: ButtonProps) {
  const styles = buttonStyles({ variant, size, full });

  return (
    <button
      className={styles.root()}
      type={type}
      name={name}
      value={value}
      autoFocus={autoFocus}
      form={form}
      onClick={onClick}
      tabIndex={tabStop ? undefined : -1}
      disabled={disabled || loading}
    >
      {loading
        ? <span className={styles.spinner()} aria-hidden="true" />
        : icon && <i className={icon} aria-hidden="true" />}
      {children}
      {iconRight && <i className={iconRight} aria-hidden="true" />}
    </button>
  );
}

// frameworks/angular/components/forms/button/Button.ts
import {
  ChangeDetectionStrategy, Component, ElementRef, afterNextRender, booleanAttribute, computed,
  input, output, viewChild,
} from '@angular/core';
import type { ButtonType, ButtonVariant, ControlSize } from '../../../Api.generated';
import { buttonStyles } from './Button.variants';

@Component({
  selector: 'arena-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display: contents',
    '[attr.name]': 'null',
  },
  template: `
    <button #control [class]="styles().root()" [attr.type]="type()" [disabled]="inert()"
            [attr.name]="name()" [attr.value]="value()" [attr.form]="form()"
            [attr.tabindex]="tabStop() ? null : -1" (click)="onClick($event)">
      @if (loading()) {
        <span [class]="styles().spinner()" aria-hidden="true"></span>
      } @else if (icon(); as glyph) {
        <i [class]="glyph" aria-hidden="true"></i>
      }
      <ng-content />
      @if (iconRight(); as glyph) {
        <i [class]="glyph" aria-hidden="true"></i>
      }
    </button>
  `,
})
export class Button {
  /** Which action this is. Danger is outline, never filled. */
  readonly variant = input<ButtonVariant>('primary');
  /** Height, from the density tokens, so the button re-densifies inside .arena-compact. */
  readonly size = input<ControlSize>('md');
  /** Phosphor class name drawn before the label. Replaced by the spinner while loading. */
  readonly icon = input<string>();
  /** Phosphor class name drawn after the label: a caret on a menu trigger, an arrow on a next action. */
  readonly iconRight = input<string>();
  /** Replaces the leading icon with a spinner and blocks activation. The spin slows under reduced motion rather than stopping: a frozen spinner reads as a hung process. */
  readonly loading = input(false, { transform: booleanAttribute });
  /** Stretches to the container's width. */
  readonly full = input(false, { transform: booleanAttribute });
  /** Blocks activation and dims the control. Implied by loading. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Native button behaviour. Defaults to 'button' so a button inside a form does not submit it by accident. */
  readonly type = input<ButtonType>('button');
  /** Submitted with the form, when the button submits one. */
  readonly name = input<string>();
  /** The value submitted under `name`. */
  readonly value = input<string>();
  /** Focused on mount. */
  readonly autoFocus = input(false, { transform: booleanAttribute });
  /** The id of the form this button belongs to, when it is not a descendant of it. */
  readonly form = input<string>();
  /** Whether the control is reached from the page's Tab sequence. Set false when it lives inside a composite that manages its own focus (a grid with a roving tab stop, a menu), where reaching it by Tab would be a second way in. Arena writes tabindex="-1" and the control stays programmatically focusable; a positive tab order is not expressible and never should be. Table's actions column is where this one is needed: a Button inside a row of a grid. */
  readonly tabStop = input(true, { transform: booleanAttribute });
  /** The button was activated, by pointer or by keyboard. */
  readonly click = output<void>();

  protected readonly inert = computed(() => this.disabled() || this.loading());
  protected readonly styles = computed(() => buttonStyles({
    variant: this.variant(), size: this.size(), full: this.full(),
  }));

  private readonly control = viewChild<ElementRef<HTMLButtonElement>>('control');

  constructor() {
    afterNextRender(() => {
      if (this.autoFocus()) this.control()?.nativeElement.focus();
    });
  }

  protected onClick(event: MouseEvent): void {
    event.stopPropagation();
    if (!this.inert()) this.click.emit();
  }
}
