// frameworks/react/components/feedback/confirm-dialog/ConfirmDialog.tsx
import React, { useId, useRef, useState } from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './ConfirmDialog.manifest.generated.ts';
import { Button } from '../../forms/button/Button.tsx';
import { useDialogModal } from '../../../UseDialogModal.ts';

export interface ConfirmDialogProps {
  /** Whether the dialog is shown. The host owns it, as in the other three modals: defaulting it would let a ConfirmDialog whose open was never wired render nothing forever and look like a working closed dialog. */
  open: boolean;
  /** The dialog was dismissed -- by the Cancel action or by the Escape key, in both layers. A scrim click is deliberately NOT one of them: this component never closes on click-outside. No payload. */
  onCancel?: () => void;
  /** The action was confirmed. */
  onConfirm?: () => void;

  /** The dialog heading, and the name the panel's aria-labelledby points at. Required: nothing can derive a name for a confirmation, because its subject is editorial, and a modal announcing only its role is worse than none at all. */
  title: string;
  /** Small uppercase label above the title. */
  eyebrow?: string;
  /** The dialog body: the question and any detail. */
  children?: React.ReactNode;
  /** The confirm button's label. */
  confirmLabel?: string;
  /** The cancel button's label. */
  cancelLabel?: string;
  /** Gives the confirm button Arena's only filled danger surface. */
  destructive?: boolean;
  /** Locks the confirm button until this exact word is typed. */
  requireText?: string;
}


const confirmStyles = tv(manifest);

export function ConfirmDialog({ open, onCancel, onConfirm, title, eyebrow = 'Confirm', children,
  confirmLabel = 'Confirm', cancelLabel = 'Cancel', destructive = false, requireText }: ConfirmDialogProps) {

  if (!title) throw new Error('ConfirmDialog: `title` is required');
  if (open == null) throw new Error('ConfirmDialog: `open` is required');
  const [typed, setTyped] = useState('');

  const panelRef = useRef<HTMLDivElement | null>(null);
  const onKeyDown = useDialogModal({ open, panelRef, onDismiss: onCancel });

  const titleId = useId();
  if (!open) return null;
  const locked = requireText ? typed.trim() !== requireText : false;
  const styles = confirmStyles({ destructive, invalid: locked && typed !== '', open: true });
  return (
    <div className={styles.root()}>
      <div role="alertdialog" aria-modal="true"
        ref={panelRef} tabIndex={-1} onKeyDown={onKeyDown} aria-labelledby={titleId}
        className={styles.panel()}>
        <div className={styles.head()}>
          <div className={styles.eyebrow()}>{eyebrow}</div>
          <div id={titleId} className={styles.title()}>{title}</div>
        </div>
        <div className={styles.body()}>
          {children}
          {requireText && (
            <div className={styles.requireBlock()}>
              <div className={styles.requireLabel()}>Type "{requireText}" to confirm</div>
              <input value={typed} onChange={(e) => setTyped(e.target.value)}
                className={styles.input()} />
            </div>
          )}
        </div>
        <div className={styles.foot()}>
          <Button variant="ghost" onClick={onCancel}>{cancelLabel}</Button>
          <button type="button" onClick={onConfirm} disabled={locked} className={styles.confirm()}>
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

// frameworks/angular/primitives/confirm-dialog/confirm-dialog.ts
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { confirmDialogStyles } from './confirm-dialog.variants';

/** Confirmation of a high-consequence action. Never closes on click-outside —
 *  losing a half-finished decision to a stray click is the failure this
 *  component exists to prevent. The host itself is the recipe's `root`, the
 *  fixed full-viewport scrim; `open` drives it between the overlay and
 *  `hidden` rather than a wrapper element omitting itself, and the panel and
 *  its content are the template's top level, gated by the same `open` input
 *  so no interactive control sits in the DOM while closed. `destructive`
 *  gives the confirm button Arena's only filled danger surface
 *  (`bg-error-fill`) — every other danger affordance in the system stays
 *  outline. `requireText` locks the confirm button until the typed value
 *  matches it exactly. */
@Component({
  selector: 'arena-confirm-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    @if (open()) {
      <div [class]="styles().panel()" role="alertdialog" aria-modal="true">
        <div [class]="styles().head()">
          <div [class]="styles().eyebrow()">{{ eyebrow() }}</div>
          @if (title(); as heading) {
            <div [class]="styles().title()">{{ heading }}</div>
          }
        </div>
        <div [class]="styles().body()">
          <ng-content />
          @if (requireText(); as required) {
            <div [class]="styles().requireBlock()">
              <div [class]="styles().requireLabel()">Type "{{ required }}" to confirm</div>
              <input [class]="styles().input()" [value]="typed()" (input)="onType($event)" autofocus />
            </div>
          }
        </div>
        <div [class]="styles().foot()">
          <button type="button" [class]="styles().cancel()" (click)="cancelled.emit()">{{ cancelLabel() }}</button>
          <button type="button" [class]="styles().confirm()" [disabled]="locked()" (click)="confirmed.emit()">{{ confirmLabel() }}</button>
        </div>
      </div>
    }
  `,
})
export class ConfirmDialog {
  readonly open = input(false);
  readonly title = input<string>();
  readonly eyebrow = input('Confirm');
  readonly confirmLabel = input('Confirm');
  readonly cancelLabel = input('Cancel');
  readonly destructive = input(false);
  readonly requireText = input<string>();
  readonly cancelled = output<void>();
  readonly confirmed = output<void>();

  protected readonly typed = signal('');
  protected readonly locked = computed(() => {
    const required = this.requireText();
    return required !== undefined && this.typed().trim() !== required;
  });
  protected readonly styles = computed(() => confirmDialogStyles({
    destructive: this.destructive(),
    invalid: this.locked() && this.typed().length > 0,
    open: this.open(),
  }));

  protected onType(event: Event): void {
    this.typed.set((event.target as HTMLInputElement).value);
  }
}
