// frameworks/react/components/navigation/arena-pagination/ArenaPagination.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaPagination.classes.generated.ts';
import { arenaPageWindow } from './PaginationWindow.ts';

export interface ArenaPaginationProps {

  /** The current page, 1-based. */
  page: number;

  /** How many pages there are. Required, and guarded at runtime: an ArenaPagination with no page count renders a window over nothing. */
  pageCount: number;

  /** Names this navigation landmark. Required, and guarded at runtime: two paginated tables in one dashboard is a routine layout, and a shared constant name leaves them indistinguishable while satisfying the requirement mechanically. It was optional with a "ArenaPagination" default for one batch, which narrowed the gap rather than closing it: a name the caller omits is still the constant. Say what is being paged: "Deployments", not "Pages". */
  ariaLabel: string;

  /** A page was chosen; carries the new 1-based page. Never fires for the current page, nor for a page outside 1..pageCount. */
  onChange?: (page: number) => void;
}


const arenaPaginationStyles = arenaStyles(manifest);

export function ArenaPagination({ page, pageCount, ariaLabel, onChange }: ArenaPaginationProps) {

  if (!ariaLabel?.trim()) throw new Error('ArenaPagination: `ariaLabel` is required');
  if (page == null) throw new Error('ArenaPagination: `page` is required');
  if (pageCount == null) throw new Error('ArenaPagination: `pageCount` is required');
  const styles = arenaPaginationStyles();
  const go = (p: number) => { if (p >= 1 && p <= pageCount && p !== page) onChange && onChange(p); };
  const nav = (dir: number, dis: boolean) => (
    <button onClick={() => go(page + dir)} disabled={dis} aria-label={dir < 0 ? 'Previous' : 'Next'}
      className={styles.nav()}>
      <i className={dir < 0 ? 'ph-bold ph-caret-left' : 'ph-bold ph-caret-right'} />
    </button>
  );
  return (
    <nav aria-label={ariaLabel} className={styles.root()}>
      {nav(-1, page <= 1)}
      {arenaPageWindow(page, pageCount).map((p, i) =>
        p === '\u2026'
          ? <span key={'e' + i} className={styles.ellipsis()}>{'\u2026'}</span>
          : (
            <button key={p} onClick={() => go(Number(p))} aria-current={p === page ? 'page' : undefined}
              className={`${styles.page()} ${p === page ? styles.pageCurrent() : styles.pageOther()}`}>{p}</button>
          ))}
      {nav(1, page >= pageCount)}
    </nav>
  );
}

// frameworks/angular/components/navigation/arena-pagination/ArenaPagination.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { arenaPageWindow } from './PaginationWindow';
import { arenaPaginationStyles } from './ArenaPagination.variants';

@Component({
  selector: 'arena-pagination',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <nav [class]="styles().root()" [attr.aria-label]="label()">
      <button type="button" [class]="styles().nav()" [disabled]="page() <= 1"
              aria-label="Previous" (click)="go(page() - 1)">
        <i class="ph-bold ph-caret-left" aria-hidden="true"></i>
      </button>
      @for (slot of slots(); track $index) {
        @if (slot === '…') {
          <span [class]="styles().ellipsis()">{{ slot }}</span>
        } @else {
          <button type="button" [class]="pageClass(slot)"
                  [attr.aria-current]="slot === page() ? 'page' : null"
                  (click)="go(slot)">{{ slot }}</button>
        }
      }
      <button type="button" [class]="styles().nav()" [disabled]="page() >= pageCount()"
              aria-label="Next" (click)="go(page() + 1)">
        <i class="ph-bold ph-caret-right" aria-hidden="true"></i>
      </button>
    </nav>
  `,
})
export class ArenaPagination {
  /** The current page, 1-based. */
  readonly page = input.required<number>();
  /** How many pages there are. Required, and guarded at runtime: an ArenaPagination with no page count renders a window over nothing. */
  readonly pageCount = input.required<number>();
  /** Names this navigation landmark. Required, and guarded at runtime: two paginated tables in one dashboard is a routine layout, and a shared constant name leaves them indistinguishable while satisfying the requirement mechanically. It was optional with a "ArenaPagination" default for one batch, which narrowed the gap rather than closing it: a name the caller omits is still the constant. Say what is being paged: "Deployments", not "Pages". */
  readonly ariaLabel = input.required<string>();
  /** A page was chosen; carries the new 1-based page. Never fires for the current page, nor for a page outside 1..pageCount. */
  readonly change = output<number>();

  protected readonly label = computed(() => {
    const name = this.ariaLabel();
    if (name.trim() === '') {
      throw new Error('ArenaPagination: `ariaLabel` is required, and names what is being paged');
    }
    return name;
  });

  protected readonly slots = computed(() => {
    const total = this.pageCount();
    if (!Number.isInteger(total) || total < 1) {
      throw new Error('ArenaPagination: `pageCount` is required, and is a whole number of at least 1');
    }
    return arenaPageWindow(this.page(), total);
  });

  protected readonly styles = computed(() => arenaPaginationStyles());

  protected pageClass(page: number): string {
    const styles = arenaPaginationStyles();
    return `${styles.page()} ${page === this.page() ? styles.pageCurrent() : styles.pageOther()}`;
  }

  protected go(page: number): void {
    if (page < 1 || page > this.pageCount() || page === this.page()) return;
    this.change.emit(page);
  }
}
