// frameworks/react/components/feedback/sheet/Sheet.tsx
import React, { useId } from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Sheet.manifest.generated.ts';

import type { SheetPlacement } from '../../../Api.generated';

export interface SheetProps {

  /** Whether the panel is on the page at all. The host owns it, the same way it owns a dialog's. Closed renders nothing, which is what distinguishes it from collapsed. */
  open: boolean;

  /** The edge the panel is anchored to. It spans that edge and stands off the device's own inset there, so a bottom sheet on a phone clears the home indicator. */
  placement?: SheetPlacement;

  /** Names the panel for assistive technology and heads it visually. It is also the accessible name of the fold control, so a reader hears which panel is being folded rather than the word Toggle. Required and **guarded at runtime** rather than defaulted: what this panel is showing is editorial, and a constant fallback would satisfy the pattern mechanically while telling a screen-reader user nothing. */
  title: string;

  /** Whether the body is folded away. The header stays visible either way: a collapsed panel is still on the page and still says what it is, which is why folding is not the same act as closing. The body is hidden rather than removed, so the fold control's reference to it never points at nothing. */
  collapsed?: boolean;

  /** The fold control was pressed, carrying the state it moved to. Arena never folds the panel by itself, so a host that ignores this gets a control that reports and a body that does not move. */
  onCollapsedChange?: (collapsed: boolean) => void;

  /** Whether the close control is shown. Every layer gates it on this member and never on whether anything listens for `close`, per R6. */
  dismissible?: boolean;

  /** The panel was dismissed, by the close control or by Escape. No payload. Escape reports here rather than adding a member of its own, and it is the only key the panel takes: a non-modal panel leaves every other key to the page behind it. */
  onClose?: () => void;

  /** The panel's body, which is what folds away. */
  children?: React.ReactNode;

  /** A row that stays put while the body scrolls: a total and its action, a pair of filters buttons. It is outside the folding body on purpose, so a folded panel can still carry the one action it exists for. */
  footer?: React.ReactNode;
}

const sheetStyles = tv(manifest);

export function Sheet({
  open, placement = 'bottom', title, collapsed = false, onCollapsedChange,
  dismissible = false, onClose, children, footer,
}: SheetProps) {

  if (!title || title.trim() === '') throw new Error('Sheet: `title` is required, and names the panel and the control that folds it');

  if (open == null) throw new Error('Sheet: `open` is required');

  const id = useId();
  const triggerId = `${id}-trigger`;
  const bodyId = `${id}-body`;

  const onKeyDown = (event: React.KeyboardEvent) => {
    if (event.key !== 'Escape') return;
    event.preventDefault();
    onClose?.();
  };

  if (!open) return null;
  const styles = sheetStyles({ placement, open: true });
  return (
    <div onKeyDown={onKeyDown} className={styles.root()}>
      <div className={styles.head()}>
        <button type="button" id={triggerId} aria-expanded={!collapsed} aria-controls={bodyId}
          onClick={() => onCollapsedChange?.(!collapsed)} className={styles.trigger()}>
          <span>{title}</span>
          <i className={`${collapsed ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down'} ${styles.caret()}`}
            aria-hidden="true" />
        </button>
        {dismissible && (
          <button type="button" onClick={onClose} aria-label="Close" className={styles.close()}>
            <i className="ph-bold ph-x" aria-hidden="true" />
          </button>
        )}
      </div>
      <div id={bodyId} role="group" aria-labelledby={triggerId} hidden={collapsed} className={styles.body()}>
        {children}
      </div>
      {footer && <div className={styles.foot()}>{footer}</div>}
    </div>
  );
}

// frameworks/angular/components/feedback/sheet/Sheet.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, contentChild, input, output } from '@angular/core';
import type { SheetPlacement } from '../../../Api.generated';
import { ArenaFooter } from '../../../ProjectionMarkers';
import { sheetStyles } from './Sheet.variants';

let nextId = 0;

@Component({
  selector: 'arena-sheet',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '(keydown)': 'onKeydown($event)',
    '[attr.title]': 'null',
  },
  template: `
    @if (open()) {
      <div [class]="styles().head()">
        <button type="button" [id]="triggerId" [class]="styles().trigger()"
                [attr.aria-expanded]="!collapsed()" [attr.aria-controls]="bodyId"
                (click)="fold()" (keydown)="onTriggerKeydown($event)">
          <span>{{ heading() }}</span>
          <i [class]="styles().caret() + ' ' + caretGlyph()" aria-hidden="true"></i>
        </button>
        @if (dismissible()) {
          <button type="button" [class]="styles().close()" aria-label="Close" (click)="close.emit()">
            <i class="ph-bold ph-x" aria-hidden="true"></i>
          </button>
        }
      </div>
      <div [id]="bodyId" [class]="styles().body()" role="group"
           [attr.aria-labelledby]="triggerId" [hidden]="collapsed()">
        <ng-content />
      </div>
      @if (footer()) {
        <div [class]="styles().foot()"><ng-content select="[footer]" /></div>
      }
    }
  `,
})
export class Sheet {
  /** Whether the panel is on the page at all. The host owns it, the same way it owns a dialog's. Closed renders nothing, which is what distinguishes it from collapsed. */
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });
  /** The edge the panel is anchored to. It spans that edge and stands off the device's own inset there, so a bottom sheet on a phone clears the home indicator. */
  readonly placement = input<SheetPlacement>('bottom');
  /** Names the panel for assistive technology and heads it visually. It is also the accessible name of the fold control, so a reader hears which panel is being folded rather than the word Toggle. Required and **guarded at runtime** rather than defaulted: what this panel is showing is editorial, and a constant fallback would satisfy the pattern mechanically while telling a screen-reader user nothing. */
  readonly title = input.required<string>();
  /** Whether the body is folded away. The header stays visible either way: a collapsed panel is still on the page and still says what it is, which is why folding is not the same act as closing. The body is hidden rather than removed, so the fold control's reference to it never points at nothing. */
  readonly collapsed = input(false, { transform: booleanAttribute });
  /** The fold control was pressed, carrying the state it moved to. Arena never folds the panel by itself, so a host that ignores this gets a control that reports and a body that does not move. */
  readonly collapsedChange = output<boolean>();
  /** Whether the close control is shown. Every layer gates it on this member and never on whether anything listens for `close`, per R6. */
  readonly dismissible = input(false, { transform: booleanAttribute });
  /** The panel was dismissed, by the close control or by Escape. No payload. Escape reports here rather than adding a member of its own, and it is the only key the panel takes: a non-modal panel leaves every other key to the page behind it. */
  readonly close = output<void>();

  protected readonly footer = contentChild(ArenaFooter);
  protected readonly triggerId = `arena-sheet-${nextId}-trigger`;
  protected readonly bodyId = `arena-sheet-${nextId++}-body`;

  protected readonly caretGlyph = computed(() => (this.collapsed() ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down'));
  protected readonly styles = computed(() => sheetStyles({ placement: this.placement(), open: this.open() }));

  protected readonly heading = computed(() => {
    const text = this.title();
    if (text.trim() === '') {
      throw new Error('Sheet: `title` is required, and names the panel and the control that folds it');
    }
    return text;
  });

  protected fold(): void {
    this.collapsedChange.emit(!this.collapsed());
  }

  protected onTriggerKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    this.fold();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.open() || event.key !== 'Escape') return;
    event.preventDefault();
    this.close.emit();
  }
}
