// frameworks/react/components/display/arena-badge/ArenaBadge.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaBadge.classes.generated.ts';

import type { ArenaTone } from '../../../Api.generated';

export interface ArenaBadgeProps {

  /** The label text. Short: a badge is a chip, not a sentence. */
  children?: React.ReactNode;
  /** System status (success/warning/danger/info) reflects an object's actual state; emphasis (accent, gold) is editorial; neutral carries no semantic weight. */
  tone?: ArenaTone;

  /** Draws a filled dot in the tone colour before the label. */
  dot?: boolean;
}

const arenaBadgeStyles = arenaStyles(manifest);
const TONES = Object.keys(manifest.variants.tone);
const toneOf = (tone: string | undefined): ArenaTone | undefined =>
  (tone && TONES.includes(tone) ? tone as ArenaTone : 'neutral');

export function ArenaBadge({ children, tone = 'neutral', dot = false }: ArenaBadgeProps) {
  const styles = arenaBadgeStyles({ tone: toneOf(tone) });
  return (
    <span className={styles.root()}>
      {dot && <span className={styles.dot()} />}
      {children}
    </span>
  );
}

// frameworks/angular/components/display/arena-badge/ArenaBadge.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input } from '@angular/core';
import type { ArenaTone } from '../../../Api.generated';
import { arenaBadgeStyles } from './ArenaBadge.variants';

@Component({
  selector: 'arena-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    @if (dot()) {
      <span [class]="styles().dot()"></span>
    }
    <ng-content />
  `,
})
export class ArenaBadge {
  /** System status (success/warning/danger/info) reflects an object's actual state; emphasis (accent, gold) is editorial; neutral carries no semantic weight. */
  readonly tone = input<ArenaTone>('neutral');
  /** Draws a filled dot in the tone colour before the label. */
  readonly dot = input(false, { transform: booleanAttribute });

  protected readonly styles = computed(() => arenaBadgeStyles({ tone: this.tone() }));
}
