// frameworks/react/components/feedback/toast/Toast.jsx
import React from 'react';
const TOAST_TONES = { neutral: 'var(--line-strong)', success: 'var(--success)', danger: 'var(--danger)', gold: 'var(--gold)' };

export function Toast({ title, message, tone = 'neutral', actionLabel, onAction, dismissible = false, onClose, persist = false }) {
  return (
    <div role={tone === 'danger' ? 'alert' : 'status'} aria-live={tone === 'danger' ? 'assertive' : 'polite'} data-persist={persist ? '' : undefined}
      style={{ display: 'flex', gap: 'calc(var(--sp-1) * 3)', alignItems: 'flex-start', width: 'calc(var(--sp-1) * 85)', padding: 'calc(var(--sp-1) * 3.5) calc(var(--sp-1) * 4)', zIndex: 'var(--z-toast)',
      background: 'var(--surface-card)', border: 'var(--bw) solid var(--color-base-300)',
      borderLeft: 'var(--bw-strong) solid ' + (TOAST_TONES[tone] || TOAST_TONES.neutral), borderRadius: 'var(--r-md)', boxShadow: 'var(--shadow-2)' }}>
      <div style={{ flex: 1 }}>
        {title && <div style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2)', fontFamily: 'var(--font-body)', fontWeight: 'var(--fw-semibold)', fontSize: 'var(--dz-text)', color: 'var(--bone)' }}>{title}{persist && <span title="Does not auto-dismiss" style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-2xs)', letterSpacing: 'var(--ls-column-header)', color: 'var(--mute)', border: 'var(--bw) solid var(--color-base-300)', borderRadius: 'var(--r-xs)', padding: '0 calc(var(--sp-1) * 1)', textTransform: 'uppercase' }}>Pinned</span>}</div>}
        {message && <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--fs-sm)', color: 'var(--mute)', marginTop: 'calc(var(--sp-1) * 0.5)' }}>{message}</div>}
        {actionLabel && (
          <button onClick={onAction}
            style={{ marginTop: 'calc(var(--sp-1) * 2.5)', background: 'none', border: 'none', padding: 0, cursor: 'pointer',
              fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', fontWeight: 'var(--fw-bold)', letterSpacing: 'var(--ls-uppercase-status)', textTransform: 'uppercase',
              color: tone === 'danger' ? 'var(--gold)' : 'var(--crimson)' }}>
            {actionLabel}
          </button>
        )}
      </div>
      {dismissible && <button onClick={onClose} aria-label="Close" style={{ display: 'inline-flex', alignItems: 'center', background: 'none', border: 'none', color: 'var(--mute)', cursor: 'pointer', fontSize: 'var(--icon-md)', lineHeight: 'var(--dz-lh)' }}><i className="ph-bold ph-x" /></button>}
    </div>
  );
}

// frameworks/angular/components/feedback/toast/Toast.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output } from '@angular/core';
import type { ToastTone } from '../../../Api.generated';
import { toastStyles } from './Toast.variants';

@Component({
  selector: 'arena-toast',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.role]': "tone() === 'danger' ? 'alert' : 'status'",
    '[attr.aria-live]': "tone() === 'danger' ? 'assertive' : 'polite'",
    '[attr.data-persist]': "pinned() ? '' : null",
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="styles().body()">
      @if (title(); as heading) {
        <div [class]="styles().title()">{{ heading }}@if (pinned()) {
          <span [class]="styles().pinned()" title="Does not auto-dismiss">Pinned</span>
        }</div>
      }
      @if (message(); as text) {
        <div [class]="styles().message()">{{ text }}</div>
      }
      @if (actionLabel(); as label) {
        <button type="button" [class]="styles().action()" (click)="action.emit()">{{ label }}</button>
      }
    </div>
    @if (dismissible()) {
      <button type="button" [class]="styles().close()" aria-label="Close" (click)="close.emit()">
        <i class="ph-bold ph-x" aria-hidden="true"></i>
      </button>
    }
  `,
})
export class Toast {
  readonly title = input<string>();
  readonly message = input<string>();
  readonly tone = input<ToastTone>('neutral');
  readonly actionLabel = input<string>();
  readonly action = output<void>();
  readonly persist = input(false, { transform: booleanAttribute });
  readonly dismissible = input(false, { transform: booleanAttribute });
  readonly close = output<void>();

  protected readonly pinned = computed(() => this.persist() || this.tone() === 'danger');
  protected readonly styles = computed(() => toastStyles({ tone: this.tone() }));
}
