// frameworks/react/components/display/table-row/TableRow.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from '../table/Table.classes.generated.ts';
import type { ArenaTableColumn } from '../../../Api.generated';
import type { TableCellInjected } from '../table-cell/TableCell.tsx';

const rowStyles = arenaStyles(manifest);

export interface TableRowInjected {
  rowIndex: number;
  columns: readonly ArenaTableColumn[];
  layout: 'table' | 'card';
  cursorCol: number | null;
  onCellFocus: (row: number, col: number) => void;
}

export interface TableRowProps {

  /** The row's cells. One TableCell per cell; a row may carry fewer or more than there are columns, and the grid's cursor is clamped against what is really there. */
  children?: React.ReactNode;

  /** Whether the row can be activated. A boolean rather than "is `click` bound?": Arena never derives what it draws from what a consumer listens for, because an outbound member's subscriber list is private in at least one platform and a consumer's binding leaves nothing in the DOM to detect, so deriving the interactive shape from it is a divergence waiting to happen, and it was one. Below --bp-md the row is a card, and an interactive card is a role="button" tab stop with an Enter/Space handler; a non-interactive one is inert, because a dead tab stop on every row of every table is worse than the gap it would close. */
  interactive?: boolean;

  /** Whether the row is drawn but cannot be activated: a record the consumer's rules lock. It reflects through `aria-disabled` rather than the native attribute, and the card shape stays a role="button" in the tab order rather than leaving it, because a disabled control nobody can reach is a control nobody knows exists. With no `click` there is nothing to disable and the row is inert already. */
  disabled?: boolean;

  /** The row was activated, by pointer or by Enter on one of its cells. No payload, because the consumer wrote this element and already holds the row this is about. */
  onClick?: () => void;
}


export function TableRow({
  children, onClick, interactive = false, disabled = false,
  rowIndex = 0, columns = [], layout = 'table', cursorCol = null, onCellFocus,
}: TableRowProps & Partial<TableRowInjected>) {

  const cells = React.Children.toArray(children).map((child, ci) => (
    React.isValidElement<Partial<TableCellInjected>>(child)
      ? React.cloneElement(child, {
        column: columns[ci],
        layout,

        tabIndex: layout === 'card' ? undefined : (ci === cursorCol ? 0 : -1),
        onCellFocus: layout === 'card' || !onCellFocus ? undefined : () => onCellFocus(rowIndex, ci),
      })
      : child
  ));

  const activate = interactive && onClick && !disabled ? onClick : undefined;
  const cursor = interactive ? (disabled ? 'not-allowed' : 'pointer') : 'default';

  if (layout === 'card') {
    return (
      <div onClick={activate}
        role={interactive ? 'button' : undefined}
        tabIndex={interactive ? 0 : undefined}
        aria-disabled={interactive && disabled ? 'true' : undefined}
        onKeyDown={activate ? (e) => {
          if (e.key !== 'Enter' && e.key !== ' ') return;
          e.preventDefault();
          activate();
        } : undefined}
        className={rowStyles({ narrow: true }).card()}>
        {cells}
      </div>
    );
  }

  const base = rowStyles({ narrow: false });
  const rowClass = [
    rowIndex <= 1 ? `${base.row()} ${base.rowFirst()}` : base.row(),
    activate ? base.rowInteractive() : '',
  ].filter(Boolean).join(' ');

  return (
    <tr role="row" onClick={activate}
      aria-disabled={onClick && disabled ? 'true' : undefined}

      className={rowClass}>
      {cells}
    </tr>
  );
}

// frameworks/angular/components/display/table-row/TableRow.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, booleanAttribute, computed, contentChildren,
  inject, input, output,
} from '@angular/core';
import { TableCell } from '../table-cell/TableCell';
import { TableState } from '../table/TableState';
import { TableRowState } from './TableRowState';
import { tableRowStyles } from './TableRow.variants';

@Component({
  selector: 'arena-table-row',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [TableRowState],
  host: { style: 'display: contents' },
  template: `
    <div [class]="rowClass()" [attr.role]="role()" [attr.aria-disabled]="inert()"
         [attr.tabindex]="cardStop()" (keydown)="onKeydown($event)"
         (click)="onClick($event)">
      <ng-content />
    </div>
  `,
})
export class TableRow {
  /** Whether the row can be activated. A boolean rather than "is `click` bound?": Arena never derives what it draws from what a consumer listens for, because an outbound member's subscriber list is private in at least one platform and a consumer's binding leaves nothing in the DOM to detect, so deriving the interactive shape from it is a divergence waiting to happen, and it was one. Below --bp-md the row is a card, and an interactive card is a role="button" tab stop with an Enter/Space handler; a non-interactive one is inert, because a dead tab stop on every row of every table is worse than the gap it would close. */
  readonly interactive = input(false, { transform: booleanAttribute });
  /** Whether the row is drawn but cannot be activated: a record the consumer's rules lock. It reflects through `aria-disabled` rather than the native attribute, and the card shape stays a role="button" in the tab order rather than leaving it, because a disabled control nobody can reach is a control nobody knows exists. With no `click` there is nothing to disable and the row is inert already. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** The row was activated, by pointer or by Enter on one of its cells. No payload, because the consumer wrote this element and already holds the row this is about. */
  readonly click = output<void>();

  private readonly table = inject(TableState);
  private readonly rowState = inject(TableRowState);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly cells = contentChildren(TableCell);

  protected readonly role = computed(() => {
    if (!this.table.narrow()) return 'row';
    return this.interactive() ? 'button' : null;
  });

  protected readonly cardStop = computed(() => (this.table.narrow() && this.interactive() ? 0 : null));

  protected readonly inert = computed(() => (this.disabled() ? 'true' : null));

  protected readonly rowClass = computed(() => {
    const narrow = this.table.narrow();
    const styles = tableRowStyles({ narrow });
    if (narrow) return styles.card();
    return this.table.rowIndexOf(this) === 1 ? `${styles.row()} ${styles.rowFirst()}` : styles.row();
  });

  constructor() {
    this.rowState.index = computed(() => this.table.rowIndexOf(this));
    this.rowState.cells = this.cells;
    this.table.registerRow(this, {
      cells: computed(() => this.cells().length),
      activate: () => this.emit(),
    });
    this.destroyRef.onDestroy(() => this.table.releaseRow(this));
  }

  protected onClick(event: MouseEvent): void {
    event.stopPropagation();
    this.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.table.narrow() || !this.interactive()) return;
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    event.stopPropagation();
    this.emit();
  }

  private emit(): void {
    if (!this.disabled()) this.click.emit();
  }
}
