// frameworks/angular/components/display/arena-unauth-card/ArenaUnauthCard.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { ArenaBrand, ArenaFooter } from '../../../ProjectionMarkers';
import { arenaUnauthCardStyles } from './ArenaUnauthCard.variants';

@Component({
  selector: 'arena-unauth-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="styles().panel()">
      <div [class]="styles().body()">
        @if (brand()) {
          <div [class]="styles().brand()"><ng-content select="[brand]" /></div>
        }
        @if (eyebrow(); as label) {
          <div [class]="styles().eyebrow()">{{ label }}</div>
        }
        @if (title(); as heading) {
          <div [class]="styles().title()">{{ heading }}</div>
        }
        <ng-content />
        @if (footer()) {
          <div [class]="styles().footer()"><ng-content select="[footer]" /></div>
        }
      </div>
    </div>
  `,
})
export class ArenaUnauthCard {
  /** Mono crimson microlabel: the product, not the task. */
  readonly eyebrow = input<string>();
  /** The task. "Welcome back", "Check your inbox". */
  readonly title = input<string>();

  protected readonly brand = contentChild(ArenaBrand);
  protected readonly footer = contentChild(ArenaFooter);

  protected readonly styles = computed(() => arenaUnauthCardStyles());
}

// frameworks/react/components/display/arena-unauth-card/ArenaUnauthCard.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaUnauthCard.classes.generated.ts';
import { ArenaCard } from '../arena-card/ArenaCard.tsx';

export interface ArenaUnauthCardProps {

  /** The brand lock-up above the panel's content. An ArenaAppLogo, in practice. */
  brand?: React.ReactNode;

  /** Mono crimson microlabel: the product, not the task. */
  eyebrow?: string;

  /** The task. "Welcome back", "Check your inbox". */
  title?: string;

  /** Centred muted line below the content: a recovery link, a legal note. */
  footer?: React.ReactNode;

  /** The fields, composed from ArenaInput and ArenaButton. */
  children?: React.ReactNode;
}


const unauthStyles = arenaStyles(manifest);

export function ArenaUnauthCard({ brand, eyebrow, title, footer, children }: ArenaUnauthCardProps) {
  const styles = unauthStyles();
  return (
    <div className={styles.root()}>
      <ArenaCard>
        <div className={styles.body()}>
          {brand && <div className={styles.brand()}>{brand}</div>}
          {eyebrow && <div className={styles.eyebrow()}>{eyebrow}</div>}
          {title && <div className={styles.title()}>{title}</div>}
          {children}
          {footer && <div className={styles.footer()}>{footer}</div>}
        </div>
      </ArenaCard>
    </div>
  );
}
