// frameworks/react/components/navigation/side-nav-item/SideNavItem.jsx
import React from 'react';
import { rowStyle, rowGlyph } from '../side-nav/SideNavInject.jsx';

/** One destination in a SideNav. `href` decides which element it renders, so it
 *  is the field to read first: present => an <a>, absent => a <button>.
 *
 *  Everything about WHERE the item sits -- its nesting depth, which id is active,
 *  the indent step, the handler that reports `nav` -- is injected by SideNav (or
 *  by the section or collapsible it sits inside) and is deliberately absent from
 *  this component's contract, exactly as RadioProps omits what RadioGroup gives
 *  each Radio. */
export function SideNavItem({
  id, label, icon, href,
  depth = 0, activeId, indentStep = 3, onActivate,
}) {
  /* Both guards are falsy rather than absence-only, and that is the operator
   * decision plan 8C4's close-out review paid for: `label` is this link's whole
   * accessible name and `id` is what `active` matches, so a present-but-blank
   * value IS the defect and `== null` would let it through. `SideNav.items`'
   * `== null` guard was the opposite case -- an empty array is a caller saying
   * "no destinations right now" -- and it left with the member. */
  if (!id) throw new Error('SideNavItem: `id` is required');
  if (!label) throw new Error('SideNavItem: `label` is required');
  const on = id === activeId;
  /* One style object for both elements: an anchor and a button must be
   * indistinguishable here, and two copies of this would drift. `rowStyle` is why
   * that now holds ACROSS components too -- a collapsible's trigger sits in the
   * same list and draws the same row, and it reads the same figure from
   * side-nav-inject.jsx rather than a second copy of it. The active-state ink
   * below stays here: it is this component's decision, not shared geometry. The
   * padding is split into block/inline rather than the old shorthand because the
   * inline start is where the indent lands. */
  const shared = {
    'aria-current': on ? 'page' : undefined,
    onClick: () => onActivate && onActivate(id),
    style: rowStyle({
      indentStep, depth,
      background: on ? 'var(--crimson-soft)' : 'transparent',
      color: on ? 'var(--crimson)' : 'var(--mute)',
      /* An <a> and a <button> must be indistinguishable, and only one of them
         underlines itself. The trigger passes nothing here for the same reason. */
      textDecoration: 'none',
      fontWeight: on ? 'var(--fw-semibold)' : 'var(--fw-medium)',
    }),
  };
  /* Arena draws the glyph and the consumer names it -- the single-icon
   * convention, unchanged by this migration. */
  const glyph = rowGlyph(icon);
  return href
    ? <a href={href} {...shared}>{glyph}{label}</a>
    : <button type="button" {...shared}>{glyph}{label}</button>;
}

// frameworks/angular/components/navigation/side-nav-item/SideNavItem.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, forwardRef, inject, input } from '@angular/core';
import { SideNavChild, SideNavState, indentFor } from '../side-nav/SideNavState';
import { sideNavStyles } from '../side-nav/SideNav.variants';

@Component({
  selector: 'arena-side-nav-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: SideNavChild, useExisting: forwardRef(() => SideNavItem) }],
  host: {
    style: 'display: contents',
    '[attr.id]': 'null',
  },
  template: `
    @if (href(); as url) {
      <a [class]="styles().item()" [href]="url" [style.paddingInlineStart]="indent()"
         [attr.aria-current]="current()" [attr.aria-disabled]="off()"
         (click)="activate($event)">
        @if (icon(); as glyph) {
          <i [class]="styles().icon() + ' ' + glyph" aria-hidden="true"></i>
        }
        {{ name() }}
      </a>
    } @else {
      <button type="button" [class]="styles().item()" [style.paddingInlineStart]="indent()"
              [attr.aria-current]="current()" [attr.aria-disabled]="off()"
              (click)="activate($event)">
        @if (icon(); as glyph) {
          <i [class]="styles().icon() + ' ' + glyph" aria-hidden="true"></i>
        }
        {{ name() }}
      </button>
    }
  `,
})
export class SideNavItem {
  /** Identifies the destination. SideNav.active names one of these, and the item whose id matches is the one marked aria-current="page". Required, and guarded with a falsy check rather than an absence check: a blank id can never match and is an omission wearing a value. */
  readonly id = input.required<string>();
  /** What the item reads, and its whole accessible name. Required and falsy-guarded for the same reason. */
  readonly label = input.required<string>();
  /** A Phosphor class name drawn before the label -- Arena draws the <i>, the consumer names the glyph. */
  readonly icon = input<string>();
  /** Present => the item renders an <a>; absent => a <button>. A control that navigates must be a link -- openable in a new tab, address copyable, announced as a link. An item that only changes local state is a button. */
  readonly href = input<string>();
  /** Whether the destination is drawn but cannot be reached -- one the consumer's rules lock, such as a feature the current plan does not include. It reflects through `aria-disabled` rather than the native attribute, and rather than by not rendering the item at all: an unavailable destination a user can see and hear announced as unavailable is what tells them it exists, which is the whole reason to draw it. The anchor keeps its `href` so the case split stays what it is -- what changes is that activation is refused and the state is announced. */
  readonly disabled = input(false, { transform: booleanAttribute });

  private readonly nav = inject(SideNavState);

  protected readonly name = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('SideNavItem: `label` is required, and names the destination this row leads to');
    }
    return text;
  });

  protected readonly on = computed(() => {
    const key = this.id();
    if (key.trim() === '') {
      throw new Error('SideNavItem: `id` is required, and is what `active` and `nav` identify this row by');
    }
    return key === this.nav.activeId();
  });

  protected readonly current = computed(() => (this.on() ? 'page' : null));
  protected readonly indent = computed(() => indentFor(this.nav.indentStep(), this.nav.depth()));
  protected readonly styles = computed(() => sideNavStyles({ active: this.on() }));

  protected readonly off = computed(() => (this.disabled() ? 'true' : null));

  protected activate(event: Event): void {
    if (this.disabled()) { event.preventDefault(); return; }
    this.nav.activate(this.id());
  }
}
