// frameworks/react/components/navigation/side-nav-item/SideNavItem.tsx
import React from 'react';
import { isPrimaryActivation } from '../../../AnchorActivation.ts';
import type { SideNavInjected } from '../side-nav/SideNavInject.tsx';
import { rowStyle, rowGlyph, rowBadge } from '../side-nav/SideNavInject.tsx';

export interface SideNavItemProps {

  /** Identifies the destination. SideNav.active names one of these, and the item whose id matches is the one marked aria-current="page". Required, and guarded with a falsy check rather than an absence check: a blank id can never match and is an omission wearing a value. */
  id: string;

  /** What the item reads, and the whole of its accessible name unless a badge adds a count to it. Required and falsy-guarded for the same reason. */
  label: string;

  /** A Phosphor class name drawn before the label -- Arena draws the <i>, the consumer names the glyph. */
  icon?: string;

  /** A count drawn at the row's trailing edge -- pending orders, unread notices. Zero draws nothing, because a badge reading 0 is a mark that says there is nothing to mark; above 99 it reads "99+", so a four-digit count cannot widen the column. A number rather than a string, because the two rules above are arithmetic and a caller who has already formatted the value has taken them away. It is NOT hidden from assistive technology, so the row announces "Orders 12": a count a screen-reader user cannot hear is a count that is not there, and aria-hidden on it would trade a real loss for a tidier name. What the 12 counts stays unsaid, because nothing can derive it and no member states it -- say it in the label where it matters. */
  badge?: number;

  /** Present => the item renders an <a>; absent => a <button>. A control that navigates must be a link -- openable in a new tab, address copyable, announced as a link. An item that only changes local state is a button. A primary click with no modifier is cancelled and reported through SideNav's `nav`, so a router owns it; a modified or middle click is the browser's and reports nothing. */
  href?: string;

  /** Whether the destination is drawn but cannot be reached -- one the consumer's rules lock, such as a feature the current plan does not include. It reflects through `aria-disabled` rather than the native attribute, and rather than by not rendering the item at all: an unavailable destination a user can see and hear announced as unavailable is what tells them it exists, which is the whole reason to draw it. The anchor keeps its `href` so the case split stays what it is -- what changes is that activation is refused and the state is announced. */
  disabled?: boolean;
}


export function SideNavItem({
  id, label, icon, badge, href, disabled = false,
  depth = 0, activeId, indentStep = 3, onActivate,
}: SideNavItemProps & Partial<SideNavInjected>) {

  if (!id) throw new Error('SideNavItem: `id` is required');
  if (!label) throw new Error('SideNavItem: `label` is required');
  const on = id === activeId;

  const shared = {
    'aria-current': on ? 'page' as const : undefined,
    'aria-disabled': disabled ? 'true' as const : undefined,
    onClick: (e: React.MouseEvent) => {
      if (disabled) { e.preventDefault(); return; }
      if (href !== undefined) {
        if (!isPrimaryActivation(e)) return;
        e.preventDefault();
      }
      if (onActivate) onActivate(id);
    },
    style: rowStyle({
      indentStep, depth,
      background: on ? 'var(--crimson-soft)' : 'transparent',
      color: on ? 'var(--crimson)' : 'var(--mute)',
      opacity: disabled ? 0.5 : 1,
      cursor: disabled ? 'not-allowed' : 'pointer',

      textDecoration: 'none',
      fontWeight: on ? 'var(--fw-semibold)' : 'var(--fw-medium)',
    }),
  };

  const glyph = rowGlyph(icon);
  const tally = rowBadge(badge, on);
  return href
    ? <a href={href} {...shared}>{glyph}{label}{tally}</a>
    : <button type="button" {...shared}>{glyph}{label}{tally}</button>;
}

// frameworks/angular/components/navigation/side-nav-item/SideNavItem.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, forwardRef, inject, input } from '@angular/core';
import { isPrimaryActivation } from '../../../AnchorActivation';
import { SideNavChild, SideNavState, indentFor } from '../side-nav/SideNavState';
import { sideNavStyles } from '../side-nav/SideNav.variants';

@Component({
  selector: 'arena-side-nav-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: SideNavChild, useExisting: forwardRef(() => SideNavItem) }],
  host: {
    style: 'display: contents',
    '[attr.id]': 'null',
  },
  template: `
    @if (href(); as url) {
      <a [class]="styles().item()" [href]="url" [style.paddingInlineStart]="indent()"
         [attr.aria-current]="current()" [attr.aria-disabled]="off()"
         (click)="activateAnchor($event)">
        @if (icon(); as glyph) {
          <i [class]="styles().icon() + ' ' + glyph" aria-hidden="true"></i>
        }
        {{ name() }}
        @if (count(); as tally) {
          <span [class]="styles().badge()">{{ tally }}</span>
        }
      </a>
    } @else {
      <button type="button" [class]="styles().item()" [style.paddingInlineStart]="indent()"
              [attr.aria-current]="current()" [attr.aria-disabled]="off()"
              (click)="activate($event)">
        @if (icon(); as glyph) {
          <i [class]="styles().icon() + ' ' + glyph" aria-hidden="true"></i>
        }
        {{ name() }}
        @if (count(); as tally) {
          <span [class]="styles().badge()">{{ tally }}</span>
        }
      </button>
    }
  `,
})
export class SideNavItem {
  /** Identifies the destination. SideNav.active names one of these, and the item whose id matches is the one marked aria-current="page". Required, and guarded with a falsy check rather than an absence check: a blank id can never match and is an omission wearing a value. */
  readonly id = input.required<string>();
  /** What the item reads, and the whole of its accessible name unless a badge adds a count to it. Required and falsy-guarded for the same reason. */
  readonly label = input.required<string>();
  /** A Phosphor class name drawn before the label -- Arena draws the <i>, the consumer names the glyph. */
  readonly icon = input<string>();
  /** A count drawn at the row's trailing edge -- pending orders, unread notices. Zero draws nothing, because a badge reading 0 is a mark that says there is nothing to mark; above 99 it reads "99+", so a four-digit count cannot widen the column. A number rather than a string, because the two rules above are arithmetic and a caller who has already formatted the value has taken them away. It is NOT hidden from assistive technology, so the row announces "Orders 12": a count a screen-reader user cannot hear is a count that is not there, and aria-hidden on it would trade a real loss for a tidier name. What the 12 counts stays unsaid, because nothing can derive it and no member states it -- say it in the label where it matters. */
  readonly badge = input<number>();
  /** Present => the item renders an <a>; absent => a <button>. A control that navigates must be a link -- openable in a new tab, address copyable, announced as a link. An item that only changes local state is a button. A primary click with no modifier is cancelled and reported through SideNav's `nav`, so a router owns it; a modified or middle click is the browser's and reports nothing. */
  readonly href = input<string>();
  /** Whether the destination is drawn but cannot be reached -- one the consumer's rules lock, such as a feature the current plan does not include. It reflects through `aria-disabled` rather than the native attribute, and rather than by not rendering the item at all: an unavailable destination a user can see and hear announced as unavailable is what tells them it exists, which is the whole reason to draw it. The anchor keeps its `href` so the case split stays what it is -- what changes is that activation is refused and the state is announced. */
  readonly disabled = input(false, { transform: booleanAttribute });

  private readonly nav = inject(SideNavState);

  protected readonly name = computed(() => {
    const text = this.label();
    if (text.trim() === '') {
      throw new Error('SideNavItem: `label` is required, and names the destination this row leads to');
    }
    return text;
  });

  protected readonly on = computed(() => {
    const key = this.id();
    if (key.trim() === '') {
      throw new Error('SideNavItem: `id` is required, and is what `active` and `nav` identify this row by');
    }
    return key === this.nav.activeId();
  });

  protected readonly current = computed(() => (this.on() ? 'page' : null));
  protected readonly indent = computed(() => indentFor(this.nav.indentStep(), this.nav.depth()));
  protected readonly styles = computed(() => sideNavStyles({ active: this.on() }));

  protected readonly off = computed(() => (this.disabled() ? 'true' : null));

  protected readonly count = computed(() => {
    const tally = this.badge();
    if (tally === undefined || !(tally > 0)) return null;
    return tally > 99 ? '99+' : String(Math.floor(tally));
  });

  protected activate(event: Event): void {
    if (this.disabled()) { event.preventDefault(); return; }
    this.nav.activate(this.id());
  }

  protected activateAnchor(event: MouseEvent): void {
    if (this.disabled()) { event.preventDefault(); return; }
    if (!isPrimaryActivation(event)) return;
    event.preventDefault();
    this.nav.activate(this.id());
  }
}
