// frameworks/angular/components/feedback/spinner/Spinner.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { ControlSize, SpinnerTone } from '../../../Api.generated';
import { spinnerStyles } from './Spinner.variants';

@Component({
  selector: 'arena-spinner',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    role: 'progressbar',
    'aria-live': 'polite',
    '[attr.aria-label]': 'label()',
  },
  template: `<span [class]="styles().circle()" aria-hidden="true"></span>`,
})
export class Spinner {
  /** Diameter. 'sm' is --icon-sm exactly, so a spinner at that size sits inline with control text. */
  readonly size = input<ControlSize>('md');
  /** Colour of the ring. 'on-accent' inside a filled button; 'accent' on a page surface. */
  readonly tone = input<SpinnerTone>('accent');
  /** Accessible name, announced by the status role. Say what is loading when you can. */
  readonly label = input('Loading');

  protected readonly styles = computed(() => spinnerStyles({ tone: this.tone(), size: this.size() }));
}

// frameworks/react/components/feedback/spinner/Spinner.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Spinner.manifest.generated.ts';

import type { ControlSize, SpinnerTone } from '../../../Api.generated';

export interface SpinnerProps {

  /** Diameter. 'sm' is --icon-sm exactly, so a spinner at that size sits inline with control text. */
  size?: ControlSize;

  /** Colour of the ring. 'on-accent' inside a filled button; 'accent' on a page surface. */
  tone?: SpinnerTone;

  /** Accessible name, announced by the status role. Say what is loading when you can. */
  label?: string;
}


const spinnerStyles = tv(manifest);

export function Spinner({ size = 'md', tone = 'accent', label = 'Loading' }: SpinnerProps) {
  const styles = spinnerStyles({ size, tone });
  return (
    <span role="progressbar" aria-live="polite" aria-label={label} className={styles.root()}>
      <span className={styles.circle()} aria-hidden="true" />
    </span>
  );
}
