// frameworks/angular/primitives/skeleton/skeleton.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { skeletonStyles } from './skeleton.variants';

type Variant = 'text' | 'line' | 'block' | 'circle';

/** Loading placeholder that reserves the space the real content will take.
 *  The host itself is the recipe's visible slot — `root` for a single shape,
 *  `stack` when `variant="text"` — so it is the flex item a parent lays out,
 *  and the text variant's lines are the template's top level, not a wrapper's. */
@Component({
  selector: 'arena-skeleton',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass()',
    role: 'status',
    'aria-label': 'Loading',
  },
  template: `
    @if (stacked()) {
      @for (row of rows(); track row) {
        <div [class]="row === rows().length ? styles().lastLine() : styles().line()"></div>
      }
    }
  `,
})
export class Skeleton {
  readonly variant = input<Variant>('block');
  readonly lines = input(3);

  protected readonly styles = computed(() => skeletonStyles({ variant: this.variant() }));
  protected readonly stacked = computed(() => this.variant() === 'text');
  protected readonly rows = computed(() => Array.from({ length: this.lines() }, (_, i) => i + 1));
  protected readonly hostClass = computed(() => (this.stacked() ? this.styles().stack() : this.styles().root()));
}

// frameworks/react/components/display/skeleton/Skeleton.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Skeleton.manifest.generated.ts';

import type { SkeletonVariant } from '../../../Api.generated';

export interface SkeletonProps {
  /** The shape the placeholder reserves. */
  variant?: SkeletonVariant;

  /** CSS width, e.g. "100%" or "12rem". Defaults to full width. */
  width?: string;

  /** CSS height. Defaults per variant. For the `circle` variant a single diameter is what is wanted, so `height` wins over `width` when both are set. */
  height?: string;

  /** Number of rows when variant="text". The last runs short. */
  lines?: number;

  /** CSS border radius. Defaults to a small token radius. */
  radius?: string;
}


const skeletonStyles = tv(manifest);

export function Skeleton({ variant = 'block', width, height, lines = 3, radius }: SkeletonProps) {
  const styles = skeletonStyles({ variant });
  if (variant === 'text' && lines > 1) {
    return (
      <div role="status" aria-label="Loading" className={styles.stack()} style={{ width }}>
        {Array.from({ length: lines }).map((_, i) => (
          <div key={i} className={i === lines - 1 ? styles.lastLine() : styles.line()} />
        ))}
      </div>
    );
  }
  const box = variant === 'circle' ? (height || width) : undefined;
  return (
    <div className={styles.root()} role="status" aria-label="Loading"
      style={{ width: box ?? width, height: box ?? height, borderRadius: radius }} />
  );
}
