// frameworks/angular/components/feedback/arena-empty-state/ArenaEmptyState.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { ArenaAction } from '../../../ProjectionMarkers';
import { arenaEmptyStateStyles } from './ArenaEmptyState.variants';

@Component({
  selector: 'arena-empty-state',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    @if (icon(); as glyph) {
      <div [class]="styles().icon()"><i [class]="glyph" aria-hidden="true"></i></div>
    }
    @if (title(); as heading) {
      <div [class]="styles().title()">{{ heading }}</div>
    }
    @if (message(); as body) {
      <div [class]="styles().message()">{{ body }}</div>
    }
    @if (action()) {
      <div [class]="styles().action()"><ng-content select="[action]" /></div>
    }
  `,
})
export class ArenaEmptyState {
  /** A Phosphor class name for the glyph Arena draws, muted. */
  readonly icon = input<string>();
  /** The headline: what is empty. */
  readonly title = input.required<string>();
  /** A sentence of guidance under the title. */
  readonly message = input<string>();

  protected readonly action = contentChild(ArenaAction);

  protected readonly styles = computed(() => arenaEmptyStateStyles());
}

// frameworks/react/components/feedback/arena-empty-state/ArenaEmptyState.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaEmptyState.classes.generated.ts';

export interface ArenaEmptyStateProps {

  /** A Phosphor class name for the glyph Arena draws, muted. */
  icon?: string;

  /** The headline: what is empty. */
  title: string;
  /** A sentence of guidance under the title. */
  message?: string;
  /** A single call-to-action control, centred under the message. */
  action?: React.ReactNode;
}


const emptyStyles = arenaStyles(manifest);

export function ArenaEmptyState({ icon, title, message, action }: ArenaEmptyStateProps) {
  if (!title) throw new Error('ArenaEmptyState: `title` is required');
  const styles = emptyStyles();
  return (
    <div className={styles.root()}>
      {icon && <div className={styles.icon()}><i className={icon} aria-hidden="true" /></div>}
      {title && <div className={styles.title()}>{title}</div>}
      {message && <div className={styles.message()}>{message}</div>}
      {action && <div className={styles.action()}>{action}</div>}
    </div>
  );
}
