// frameworks/angular/components/feedback/dialog/Dialog.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  contentChild,
  inject,
  input,
  output,
  untracked,
  viewChild,
} from '@angular/core';
import { ArenaFooter } from '../../../ProjectionMarkers';
import { dialogStyles } from './Dialog.variants';
import { type FocusTrapState, handleOpenTransition, trapTabKey } from '../../../FocusTrap';

let nextId = 0;

@Component({
  selector: 'arena-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().scrim()',
    '(click)': 'onScrimClick()',
    '(keydown)': 'onKeydown($event)',
    '[attr.title]': 'null',
  },
  template: `
    @if (open()) {
      <div #panel [class]="styles().panel()" role="dialog" aria-modal="true" tabindex="-1"
           [attr.aria-labelledby]="titleId" [style.width]="width()"
           (click)="$event.stopPropagation()">
        <div [class]="styles().head()">
          @if (eyebrow(); as label) {
            <div [class]="styles().eyebrow()">{{ label }}</div>
          }
          <div [id]="titleId" [class]="styles().title()">{{ title() }}</div>
        </div>
        <div [class]="styles().body()"><ng-content /></div>
        @if (footer()) {
          <div [class]="styles().foot()"><ng-content select="[footer]" /></div>
        }
      </div>
    }
  `,
})
export class Dialog {
  /** Whether the dialog is shown. The host owns it. */
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });

  /** Names the dialog for assistive technology and heads it visually. Required: aria-labelledby points at it, and a modal with no name is worse than none at all. */
  readonly title = input.required<string>();
  /** A short kicker above the title. */
  readonly eyebrow = input<string>();
  /** A CSS width for the panel. It defaults to 480px, which each layer reaches in its own idiom, and the input overrides whichever. */
  readonly width = input<string>();
  /** The dialog was dismissed -- by Escape or by a scrim click. No payload. */
  readonly close = output<void>();

  private readonly doc = inject(DOCUMENT);
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  protected readonly titleId = `arena-dialog-${nextId++}-title`;
  protected readonly footer = contentChild(ArenaFooter);
  protected readonly styles = computed(() => dialogStyles({ open: this.open() }));

  private readonly focusTrap: FocusTrapState = { wasOpen: false, restoreTo: null };

  constructor() {
    afterRenderEffect(() => {
      const isOpen = this.open();
      untracked(() => {
        handleOpenTransition(this.focusTrap, isOpen, this.panel()?.nativeElement ?? null, this.doc.activeElement);
      });
    });
  }

  protected onScrimClick(): void {
    if (this.open()) this.close.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.open()) return;
    if (event.key === 'Escape') {
      event.preventDefault();
      this.close.emit();
      return;
    }
    if (event.key === 'Tab') {
      const panel = this.panel()?.nativeElement;
      if (panel) trapTabKey(panel, event, this.doc.activeElement);
    }
  }
}

// frameworks/react/components/feedback/dialog/Dialog.tsx
import React, { useId, useRef } from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Dialog.manifest.generated.ts';
import { useDialogModal } from '../../../UseDialogModal.ts';

export interface DialogProps {

  /** Whether the dialog is shown. The host owns it. */
  open: boolean;

  /** Names the dialog for assistive technology and heads it visually. Required: aria-labelledby points at it, and a modal with no name is worse than none at all. */
  title: string;

  /** A short kicker above the title. */
  eyebrow?: string;

  /** A CSS width for the panel. It defaults to 480px, which each layer reaches in its own idiom, and the input overrides whichever. */
  width?: string;

  /** The dialog's body. */
  children?: React.ReactNode;

  /** The action row, right-aligned. */
  footer?: React.ReactNode;

  /** The dialog was dismissed -- by Escape or by a scrim click. No payload. */
  onClose?: () => void;
}


const dialogStyles = tv(manifest);

export function Dialog({ open, onClose, title, eyebrow, children, footer, width }: DialogProps) {

  if (!title) throw new Error('Dialog: `title` is required');

  if (open == null) throw new Error('Dialog: `open` is required');

  const panelRef = useRef<HTMLDivElement | null>(null);
  const onKeyDown = useDialogModal({ open, panelRef, onDismiss: onClose });

  const titleId = useId();
  if (!open) return null;
  const styles = dialogStyles({ open: true });
  return (
    <div onClick={onClose} className={styles.scrim()}>
      <div onClick={(e) => e.stopPropagation()} role="dialog" aria-modal="true"
        ref={panelRef} tabIndex={-1} onKeyDown={onKeyDown} aria-labelledby={titleId}
        className={styles.panel()} style={{ width }}>
        <div className={styles.head()}>
          {eyebrow && <div className={styles.eyebrow()}>{eyebrow}</div>}
          <div id={titleId} className={styles.title()}>{title}</div>
        </div>
        <div className={styles.body()}>{children}</div>
        {footer && <div className={styles.foot()}>{footer}</div>}
      </div>
    </div>
  );
}
