// frameworks/angular/playground/PlaygroundState.ts
import { computed, signal } from '@angular/core';
import {
  applyBind, baseState, boundValues, describePayload, nextEntries, readState, searchUrl, writeSearch,
} from './PlaygroundCodec.generated';
import type { KnobModel, LogEntry, PlaygroundState } from './PlaygroundCodec.generated';

export * from './PlaygroundCodec.generated';

export class PlaygroundStore {
  private readonly current = signal<PlaygroundState>({ held: {}, bound: {} });
  private readonly log = signal<LogEntry[]>([]);
  private nextId = 0;

  readonly model: KnobModel;
  readonly state = computed(() => this.current());
  readonly values = computed(() => boundValues(this.model, this.current()));
  readonly entries = computed(() => this.log());

  constructor(model: KnobModel) {
    this.model = model;
    this.current.set(readState(model, window.location.search));
  }

  private commit(next: PlaygroundState): void {
    this.current.set(next);
    const search = writeSearch(this.model, next, window.location.search);
    window.history.replaceState(null, '', searchUrl(window.location.pathname, search));
  }

  setValue(member: string, value: unknown): void {
    const state = this.current();
    this.commit({ held: { ...state.held, [member]: value }, bound: state.bound });
  }

  setBound(member: string, on: boolean): void {
    const state = this.current();
    this.commit({ held: state.held, bound: { ...state.bound, [member]: on } });
  }

  fire(name: string, payload?: unknown): void {
    this.nextId += 1;
    this.log.set(nextEntries(this.log(), { id: this.nextId, name, payload: describePayload(payload) }));
    const event = this.model.events.find((one) => one.name === name);
    if (event?.bind) this.commit(applyBind(this.current(), event.bind, payload));
  }

  reset(): void {
    this.commit(baseState(this.model));
    this.log.set([]);
  }
}

// frameworks/react/playground/PlaygroundState.ts
import React from 'react';
import {
  applyBind, baseState, boundValues, describePayload, nextEntries, readState, searchUrl, writeSearch,
} from './PlaygroundCodec.generated.ts';
import type { KnobModel, LogEntry, PlaygroundState } from './PlaygroundCodec.generated.ts';

export * from './PlaygroundCodec.generated.ts';

export interface Playground {
  model: KnobModel;
  state: PlaygroundState;
  values: Record<string, unknown>;
  entries: LogEntry[];
  setValue: (member: string, value: unknown) => void;
  setBound: (member: string, on: boolean) => void;
  fire: (name: string, payload?: unknown) => void;
  reset: () => void;
}

export function usePlayground(model: KnobModel): Playground {
  const [state, setState] = React.useState<PlaygroundState>(() => readState(model, window.location.search));
  const [entries, setEntries] = React.useState<LogEntry[]>([]);
  const nextId = React.useRef(0);

  React.useEffect(() => {
    const search = writeSearch(model, state, window.location.search);
    window.history.replaceState(null, '', searchUrl(window.location.pathname, search));
  }, [model, state]);

  const setValue = React.useCallback((member: string, value: unknown) => {
    setState((current) => ({ ...current, held: { ...current.held, [member]: value } }));
  }, []);

  const setBound = React.useCallback((member: string, on: boolean) => {
    setState((current) => ({ ...current, bound: { ...current.bound, [member]: on } }));
  }, []);

  const fire = React.useCallback((name: string, payload?: unknown) => {
    nextId.current += 1;
    const id = nextId.current;
    setEntries((all) => nextEntries(all, { id, name, payload: describePayload(payload) }));
    const event = model.events.find((one) => one.name === name);
    if (event?.bind) setState((current) => applyBind(current, event.bind, payload));
  }, [model]);

  const reset = React.useCallback(() => setState(baseState(model)), [model]);

  return { model, state, values: boundValues(model, state), entries, setValue, setBound, fire, reset };
}
