// frameworks/angular/primitives/onboarding/onboarding.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  inject,
  input,
  output,
  untracked,
  viewChild,
} from '@angular/core';
import { onboardingStyles } from './onboarding.variants';
import { type FocusTrapState, handleOpenTransition, trapTabKey } from '../focus-trap';
import { onboardingWidth, sp3, sp4 } from '../../tokens.generated';
import type { OnboardingAnchor, OnboardingStep } from '../../api.generated';

/** Guided coachmark tour (H10). Presents features within the product with
 *  progress dots, "Skip" and "Next" -- controlled: the host owns `index` and
 *  answers `next`, `back`, `skip` and `done`. Floats bottom-right over an
 *  unblurred scrim by default, or anchors next to `anchor` (an
 *  `OnboardingAnchor`; a `DOMRect` is structurally assignable, so
 *  `getBoundingClientRect()` still passes directly), clamped inside the
 *  viewport. The host is the recipe's `root`, the fixed full-viewport scrim
 *  -- `open` drives it between the overlay and `hidden` rather than a
 *  wrapper element omitting itself, matching `arena-confirm-dialog`. Unlike
 *  that dialog, this scrim IS dismissible: clicking it reports `skip`, the
 *  same as React's `onClick={onSkip}` on its own scrim div. Because the
 *  panel is a descendant of the host here (React renders scrim and panel as
 *  siblings), a click inside the panel stops its own propagation so it
 *  never reaches the host's scrim listener.
 *
 *  Modal by assertion and by behaviour, not just by assertion: because the
 *  panel carries `aria-modal="true"`, focus moves into it on open and is
 *  restored to whatever held it beforehand on close, Tab/Shift+Tab cycle
 *  within the panel rather than walking into the page behind the scrim, and
 *  Escape reports dismissal through the same `skip` output the scrim click
 *  and the Skip button already use. This reuses `arena-confirm-dialog`'s
 *  focus contract through the shared
 *  `frameworks/angular/primitives/focus-trap.ts`
 *  (`handleOpenTransition`, `trapTabKey`) rather than a second
 *  implementation. React's `Onboarding.jsx` had none of it until plan 8C4, which
 *  gave it `use-dialog-modal.js` -- a port of this same module, consumed by all
 *  three React overlays. The divergence that recorded the gap is retired; see
 *  `components-divergences.md`. */
@Component({
  selector: 'arena-onboarding',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '(click)': 'onScrimClick()',
    '(keydown)': 'onKeydown($event)',
  },
  template: `
    @if (visible()) {
      <div #panel [class]="styles().panel()" role="dialog" aria-modal="true" tabindex="-1"
           [attr.aria-label]="label()"
           (click)="$event.stopPropagation()"
           [style.top.px]="position()?.top" [style.left.px]="position()?.left">
        @if (step().eyebrow; as eyebrow) {
          <div [class]="styles().eyebrow()">{{ eyebrow }}</div>
        }
        @if (step().title; as title) {
          <div [class]="styles().title()">{{ title }}</div>
        }
        @if (step().body; as body) {
          <div [class]="styles().body()">{{ body }}</div>
        }
        <div [class]="styles().foot()">
          <div [class]="styles().dots()" [attr.aria-label]="'Step ' + (index() + 1) + ' of ' + steps().length">
            @for (dot of steps(); track $index) {
              <span [class]="styles().dot() + ' ' + ($index === index() ? styles().dotOn() : styles().dotOff())"></span>
            }
          </div>
          @if (index() > 0) {
            <button type="button" [class]="styles().text()" (click)="back.emit()">Back</button>
          }
          @if (!last()) {
            <button type="button" [class]="styles().text()" (click)="skip.emit()">Skip</button>
          }
          <button type="button" [class]="styles().next()" (click)="last() ? done.emit() : next.emit()">
            {{ last() ? 'Got it' : 'Next' }}
          </button>
        </div>
      </div>
    }
  `,
})
export class Onboarding {
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });
  readonly steps = input.required<OnboardingStep[]>();
  readonly index = input(0);
  readonly anchor = input<OnboardingAnchor>();
  readonly next = output<void>();
  readonly back = output<void>();
  readonly skip = output<void>();
  readonly done = output<void>();

  private readonly doc = inject(DOCUMENT);
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  protected readonly visible = computed(() => this.open() && this.steps().length > 0);
  protected readonly step = computed<OnboardingStep>(() => this.steps()[this.index()] ?? {});
  protected readonly last = computed(() => this.index() === this.steps().length - 1);

  /** The dialog's accessible name. Falls back through `title` to `eyebrow` to a
   *  generic step count, so a step that omits `title` still names the dialog.
   *  This chain was this layer's alone until plan 8C4, when `Onboarding.jsx`
   *  ported it verbatim rather than `OnboardingStep.title` being made required --
   *  which would have broken a shipped two-layer contract to buy the same result.
   *  The two layers now agree by construction; keep them that way.
   *
   *  Known and accepted: on a step with neither `title` nor `eyebrow`, this
   *  produces the same string as the progress dots' own `aria-label` below, so a
   *  screen reader announces the two identically. A positional name is a floor,
   *  not a substitute for one the caller writes. */
  protected readonly label = computed(() => {
    const current = this.step();
    return current.title ?? current.eyebrow ?? `Step ${this.index() + 1} of ${this.steps().length}`;
  });

  protected readonly styles = computed(() => onboardingStyles({
    placement: this.anchor() ? 'anchored' : 'floating',
    open: this.open(),
  }));

  /** Clamped against the viewport, or null when the coachmark floats. `W`
   *  and `EDGE` are still real numbers, the same reason `Onboarding.jsx`
   *  states: `Math.min`/`Math.max` need real numbers. Both are authored once
   *  in tokens/src/ now instead of here and in React's copy. */
  protected readonly position = computed(() => {
    const rect = this.anchor();
    if (!rect) return null;
    const view = this.doc.defaultView;
    const W = onboardingWidth;
    const EDGE = sp4;
    const top = Math.min(rect.bottom + sp3, (view?.innerHeight ?? 900) - 220);
    const left = view ? Math.min(rect.left, view.innerWidth - W - EDGE) : rect.left;
    return { top, left: Math.max(EDGE, left) };
  });

  /** Bookkeeping `handleOpenTransition` mutates across renders -- a plain
   *  object rather than a signal, matching `arena-confirm-dialog`'s and
   *  `arena-command-palette`'s own field, for the identical reason: reading
   *  it inside the effect below must never register as a dependency, or
   *  writing it there would make the effect re-run itself. */
  private readonly focusTrap: FocusTrapState = { wasOpen: false, restoreTo: null };

  constructor() {
    afterRenderEffect(() => {
      // `visible()`, not `open()`: an `open` tour with no steps renders no
      // panel at all, so there is nothing to move focus into and nothing
      // for the user to have escaped from on the way back out.
      const isOpen = this.visible();
      untracked(() => {
        handleOpenTransition(this.focusTrap, isOpen, this.panel()?.nativeElement ?? null, this.doc.activeElement);
      });
    });
  }

  protected onScrimClick(): void {
    if (this.visible()) this.skip.emit();
  }

  /** Escape routes to `skip` -- the tour's existing dismissal, the same one
   *  the scrim click and the Skip button report -- rather than inventing a
   *  second close path the host would have to wire separately. */
  protected onKeydown(event: KeyboardEvent): void {
    if (!this.visible()) return;
    if (event.key === 'Escape') {
      event.preventDefault();
      this.skip.emit();
      return;
    }
    if (event.key === 'Tab') {
      const panel = this.panel()?.nativeElement;
      if (panel) trapTabKey(panel, event, this.doc.activeElement);
    }
  }
}

// frameworks/react/components/feedback/Onboarding.jsx
import React, { useRef } from 'react';
import { onboardingWidth, sp3, sp4 } from '../../tokens.generated.js';
import { useDialogModal } from '../../use-dialog-modal.js';

/** Guided onboarding (H10). Step-by-step coachmark: presents features within the product
 * with progress, "Skip", and "Next". Controlled: the host keeps `index`.
 * `anchor` (optional) anchors the callout next to an element by its left and bottom
 * viewport coordinates; a DOMRect satisfies it. Without it the coachmark floats bottom-right.
 *
 * Escape dismisses, and it reports through `onSkip` -- the component's own
 * dismissal channel, which is what Angular's arena-onboarding already routes its
 * Escape to, so no new member appears in either layer. The scrim's click stays:
 * Escape joins the mouse path rather than replacing it. */
export function Onboarding({ open, steps, index = 0, onNext, onBack, onSkip, onDone, anchor }) {
  if (open == null) throw new Error('Onboarding: `open` is required');
  if (steps == null) throw new Error('Onboarding: `steps` is required');
  /* EVERY hook below runs BEFORE the `if (!open || !steps.length)` early return.
   * useDialogModal calls useEffect and useRef of its own, so hoisting it under
   * the return would change the hook count on the render where `open` flips and
   * crash React. The two guards above it throw rather than render, so they are
   * not a conditional path. */
  const panelRef = useRef(null);
  const onKeyDown = useDialogModal({ open, panelRef, onDismiss: onSkip });
  if (!open || !steps.length) return null;
  const step = steps[index] || {};
  const last = index === steps.length - 1;
  /* The coachmark's accessible name, and a direct port of the `label` computed in
   * frameworks/angular/primitives/onboarding/onboarding.ts -- which named React's
   * bare `step.title` as the defect and shipped the fix first. `OnboardingStep.title`
   * is optional in a contract both layers share, so React omitted the attribute
   * entirely on an untitled step and rendered role="dialog" with no name at all.
   *
   * Guarding the title the way Dialog and ConfirmDialog do would have been a
   * breaking change to that shipped two-layer contract and would have moved
   * arena-onboarding too; adopting Angular's chain instead makes the two layers
   * agree by construction rather than by coincidence.
   *
   * The last arm is a floor, not a substitute: "Step 2 of 3" is positional, it
   * says nothing about the subject, and it is byte-for-byte the aria-label the
   * progress dots below already carry. That collision ships in Angular today and
   * is mirrored rather than dodged -- a different third arm would cost the
   * agreement that is the whole reason `title` stayed optional. A caller who
   * wants a useful name supplies a step title. */
  const label = step.title ?? step.eyebrow ?? `Step ${index + 1} of ${steps.length}`;
  // The popover's own geometry, from tokens/src/. These were plain constants
  // because Math.min/Math.max need real numbers; they are still real numbers,
  // but authored once in tokens/src/ instead of here and in Angular's copy.
  const W = onboardingWidth;
  const EDGE = sp4;

  let pos = { position: 'fixed', right: 'calc(var(--sp-1) * 6)', bottom: 'calc(var(--sp-1) * 6)', zIndex: 'var(--z-onboarding)' };
  if (anchor) {
    // Two plain numbers remain here, both arithmetic on a DOMRect and on
    // window.innerHeight:
    //   220 -- a floor estimate of the popover's own height, so a callout
    //          anchored near the bottom of the viewport is not pushed below
    //          the fold. It is deliberately an over-estimate: too high only
    //          lifts the popover, too low would clip it.
    //   900 -- the assumed viewport height before mount, where there is no
    //          window to measure. Not a design value; the charts make the
    //          same assumption about width.
    const top = Math.min(anchor.bottom + sp3, (typeof window !== 'undefined' ? window.innerHeight : 900) - 220);
    let left = anchor.left;
    if (typeof window !== 'undefined') left = Math.min(left, window.innerWidth - W - EDGE);
    pos = { position: 'fixed', top, left: Math.max(EDGE, left), zIndex: 'var(--z-onboarding)' };
  }

  const foot = { fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)', letterSpacing: 'var(--ls-uppercase-status)' };
  return (
    <>
      {/* The scrim sits just under the coachmark -- one slot, two uses, so the
        * relationship is expressed as a derivation at the point of use rather
        * than a second token. */}
      <div onClick={onSkip} style={{ position: 'fixed', inset: 0, zIndex: 'calc(var(--z-onboarding) - 10)', background: 'var(--scrim)' }} />
      <div role="dialog" aria-modal="true" aria-label={label}
        ref={panelRef} tabIndex={-1} onKeyDown={onKeyDown}
        style={{ ...pos, width: 'var(--onboarding-width)', maxWidth: '92vw', background: 'var(--surface-card)', border: 'var(--bw) solid var(--line-strong)',
          borderRadius: 'var(--r-lg)', boxShadow: 'var(--shadow-3)', padding: 'calc(var(--sp-1) * 5)' }}>
        {step.eyebrow && <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)', letterSpacing: 'var(--ls-label)', textTransform: 'uppercase', color: 'var(--crimson)', marginBottom: 'calc(var(--sp-1) * 2)' }}>{step.eyebrow}</div>}
        {step.title && <div style={{ fontFamily: 'var(--font-display)', fontWeight: 'var(--fw-extrabold)', fontSize: 'var(--fs-h4)', color: 'var(--bone)', letterSpacing: 'var(--ls-tight)' }}>{step.title}</div>}
        {step.body && <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--fs-md)', lineHeight: 'var(--lh-body)', color: 'var(--bone-dim)', marginTop: 'calc(var(--sp-1) * 2)' }}>{step.body}</div>}
        <div style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 1.5)', marginTop: 'calc(var(--sp-1) * 4.5)' }}>
          <div style={{ display: 'flex', gap: 'calc(var(--sp-1) * 1.5)', flex: 1 }} aria-label={'Step ' + (index + 1) + ' of ' + steps.length}>
            {steps.map((_, i) => (
              <span key={i} style={{ width: i === index ? 'calc(var(--sp-1) * 4.5)' : 'var(--sp-2)', height: 'calc(var(--sp-1) * 2)', borderRadius: 'var(--r-pill)', background: i === index ? 'var(--crimson)' : 'var(--line-strong)', transition: 'width var(--dur-mid) var(--ease-out)' }} />
            ))}
          </div>
          {index > 0 && (
            <button onClick={onBack} style={{ ...foot, background: 'none', border: 'none', cursor: 'pointer', color: 'var(--mute)', fontWeight: 'var(--fw-bold)', textTransform: 'uppercase' }}>Back</button>
          )}
          {!last && (
            <button onClick={onSkip} style={{ ...foot, background: 'none', border: 'none', cursor: 'pointer', color: 'var(--mute)', fontWeight: 'var(--fw-bold)', textTransform: 'uppercase' }}>Skip</button>
          )}
          <button onClick={last ? onDone : onNext}
            style={{ height: 'calc(var(--sp-1) * 8.5)', padding: '0 calc(var(--sp-1) * 4)', background: 'var(--crimson)', color: 'var(--on-accent)', border: 'none', borderRadius: 'var(--r-sm)',
              fontFamily: 'var(--font-body)', fontWeight: 'var(--fw-semibold)', fontSize: 'var(--dz-text-md)', cursor: 'pointer' }}>
            {last ? 'Got it' : 'Next'}
          </button>
        </div>
      </div>
    </>
  );
}
