// frameworks/react/components/display/table/Table.tsx
import React, { useEffect, useRef, useState } from 'react';
import { warnOnce } from '../../../WarnOnce.ts';
import { useContainerWidth, readBreakpoint } from '../../../UseContainerWidth.ts';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Table.manifest.generated.ts';

import { Pagination } from '../../navigation/pagination/Pagination.tsx';
import { Select } from '../../forms/select/Select.tsx';

import type {
  SelectOption, TableColumn, TablePage, TableSort, TableSortControl,
} from '../../../Api.generated';

export type { TableColumn };

export interface TableProps {

  /** Names the grid for assistive technology. Required, and guarded at runtime: nothing can derive it; Calendar names its grid from the range it is showing, and a data table's subject is editorial. Say what the rows are, never "Table". */
  label: string;

  /** The columns, in order. A column heads and sets its cells; it never says what goes in them. */
  columns: TableColumn[];

  /** The rows. One TableRow per row. Where a row sits, the columns its cells are set against and how the keyboard reaches them are Table's to decide and no row's to declare; how that reaches a row is each layer's own idiom. */
  children?: React.ReactNode;

  /** What shows when no row is written. In that state NO grid is drawn at all, header row included: a column head over a "no results" sentence describes a table that is not there, and a role="grid" holding neither a header nor a row is a degenerate render, the same judgement Tabs makes when it draws no panel for a tab that does not exist. Every layer falls back to the string 'No data.' when nothing is given, each in its own idiom for a default. Unlike Table.label this one IS derivable: 'No data.' states what happened rather than what the component is, which is the distinction that makes a fallback useful here and useless there. A consumer with a better sentence, what to do next or why the list is empty, projects it. */
  empty?: React.ReactNode;

  /** Card mode below --bp-md. Set false only when the columns are meaningless apart. */
  responsive?: boolean;

  /** Which column the rows are ordered by and which way. Controlled: Table draws the caret and the aria-sort, and the consumer does the ordering, because Table does not hold the rows. Absent, no header is a sort target. */
  sort?: TableSort;

  /** How the sort affordance is reached in CARD MODE, where there is no header row to activate and a `sortable` column therefore has no control under it at all. 'auto' draws one compact select above the cards, listing every sortable column in each direction, which is the shape a phone has room for; 'none' leaves card mode unsorted by hand, for a table whose order is the document's rather than the reader's. Above --bp-md the header row is the control and this member draws nothing. The header row does NOT come back below the breakpoint, because card mode exists for the one reason a grid does not fit. It is a member rather than something a consumer draws for themselves because the state it edits, TableSort, is Arena's: left to each consumer, the label, the option order and the way a direction is worded are invented once per project over a model they did not define. */
  sortControl?: TableSortControl;

  /** A sortable header was activated, carrying the column and the direction it should become: the same column flips, a different one starts ascending. Table never reorders anything itself, so a consumer who ignores this event gets a caret that moves and rows that do not, which is why the member is controlled rather than a starting value. */
  onSortChange?: (sort: TableSort) => void;

  /** Which page of a longer list is on screen. Present, Table draws its own Pagination below the grid and names it from `label`, which is what gives that required name its uniqueness on a page with two paged tables. Absent, no pager is drawn and the projected rows are the whole list. */
  page?: TablePage;

  /** A page was chosen, carrying the new 1-based page. It also fires with 1 when the current page has gone PAST THE END, which is the only reset Table performs; a filter that leaves the page in range is silent, so returning the reader to page one on a change of criterion stays the consumer's, beside the criterion they hold. */
  onPageChange?: (page: number) => void;
}


export function sortOptionValue(column: number, direction: TableSort['direction']): string {
  return `${column}:${direction}`;
}

export function parseSortOption(value: string): TableSort | null {
  const [column, direction] = value.split(':');
  const index = Number.parseInt(column ?? '', 10);
  if (!Number.isInteger(index) || (direction !== 'asc' && direction !== 'desc')) return null;
  return { column: index, direction };
}

const tableStyles = tv(manifest);

export function Table({
  columns, children, empty = 'No data.', responsive = true, label,
  sort, sortControl = 'auto', onSortChange, page, onPageChange,
}: TableProps) {
  if (!label?.trim()) throw new Error('Table: `label` is required');
  if (columns == null) throw new Error('Table: `columns` is required');
  const [ref, width] = useContainerWidth();

  const narrow = responsive && width !== null && width < readBreakpoint('md');

  const rowEls = React.Children.toArray(children);
  const bare = rowEls.length === 0;

  const pageCount = page ? Math.max(1, Math.ceil(page.total / Math.max(1, page.size))) : 1;

  useEffect(() => {
    if (page && page.index > pageCount) onPageChange?.(1);
  }, [page?.index, pageCount]);

  useEffect(() => {
    if (!sort) return;
    const column = columns[sort.column];
    if (column?.sortable) return;
    const name = column ? `"${column.header}"` : 'no column at all';
    warnOnce(`Table "${label}": sort.column ${sort.column} is ${name}, which does not declare`
      + ' `sortable`, so no header is a target and the caret is not drawn. TableSort.column is an'
      + ' INDEX, so moving a column reorders the rows in silence; keep the sort field inside the'
      + ' column entry it belongs to and the two move together.');
  }, [sort?.column, columns]);

  const sortStateOf = (index: number): 'ascending' | 'descending' | 'none' | undefined => {
    if (!columns[index]?.sortable || !sort) return undefined;
    if (sort.column !== index) return 'none';
    return sort.direction === 'asc' ? 'ascending' : 'descending';
  };

  const onHeaderActivate = (index: number) => {
    if (!columns[index]?.sortable || !sort || !onSortChange) return;
    onSortChange(sort.column === index
      ? { column: index, direction: sort.direction === 'asc' ? 'desc' : 'asc' }
      : { column: index, direction: 'asc' });
  };

  const gridRef = useRef<HTMLTableElement | null>(null);
  const [cursor, setCursor] = useState({ row: 0, col: 0 });

  const cellCounts = rowEls.map((row) => (
    React.isValidElement(row) ? React.Children.toArray(row.props.children).length : 0
  ));
  const rowLens = bare ? [] : [columns.length, ...cellCounts];

  const curRow = Math.min(Math.max(cursor.row, 0), Math.max(rowLens.length - 1, 0));
  const curCol = Math.min(Math.max(cursor.col, 0), Math.max((rowLens[curRow] || 0) - 1, 0));

  useEffect(() => {
    const g = gridRef.current;
    if (!g) return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active)) return;

    const activeRole = active.getAttribute('role');
    if (activeRole !== 'gridcell' && activeRole !== 'columnheader') return;
    const cell = g.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"], [role="columnheader"][tabindex="0"]');
    if (cell && cell !== active) cell.focus();
  }, [curRow, curCol]);

  const onGridKeyDown = (e: React.KeyboardEvent) => {
    const t = e.target;
    if (!(t instanceof Element)) return;
    const role = t.getAttribute('role');

    if (role !== 'gridcell' && role !== 'columnheader') return;

    let row = curRow;
    let col = curCol;
    if (e.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (e.key === 'ArrowDown') row = Math.min(rowLens.length - 1, row + 1);
    else if (e.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (e.key === 'ArrowRight') col = Math.min(Math.max((rowLens[row] || 1) - 1, 0), col + 1);

    else if (e.key === 'Home') col = 0;
    else if (e.key === 'End') col = Math.max((rowLens[row] || 1) - 1, 0);
    else if (e.key === 'Enter' || e.key === ' ') {

      e.preventDefault();
      if (curRow === 0) { onHeaderActivate(curCol); return; }
      if (e.key === ' ') return;
      const rowEl = rowEls[curRow - 1];
      if (rowEl && React.isValidElement<{ onClick?: () => void }>(rowEl) && rowEl.props.onClick) {
        rowEl.props.onClick();
      }
      return;
    } else return;

    col = Math.min(col, Math.max((rowLens[row] || 1) - 1, 0));

    e.preventDefault();

    if (row !== curRow || col !== curCol) setCursor({ row, col });
  };

  const onCellFocus = (ri: number, ci: number) => {
    if (ri !== curRow || ci !== curCol) setCursor({ row: ri, col: ci });
  };

  const headerNav = (ci: number) => ({
    tabIndex: 0 === curRow && ci === curCol ? 0 : -1,
    onFocus: (e: React.FocusEvent) => { if (e.target === e.currentTarget) onCellFocus(0, ci); },
  });

  const sortable = columns.map((column, index) => ({ column, index })).filter((c) => c.column.sortable);
  const sortBar = narrow && !bare && sortControl !== 'none' && Boolean(sort) && sortable.length > 0;
  const sortOptions: SelectOption[] = sortable.flatMap(({ column, index }) => [
    { value: sortOptionValue(index, 'asc'), label: `${column.header} \u2191` },
    { value: sortOptionValue(index, 'desc'), label: `${column.header} \u2193` },
  ]);
  const sortValue = sort ? sortOptionValue(sort.column, sort.direction) : undefined;

  const headerClass = (c: TableColumn): string => {
    const base = tableStyles({ narrow: false, align: c.align || 'left' }).th();
    return c.sortable && sort ? `${base} ${tableStyles({ narrow: false }).thSortable()}` : base;
  };

  return (
    <div ref={ref} className={tableStyles({ narrow }).root()}>
      {narrow ? (
        <div className={tableStyles({ narrow: true }).grid()}>
          {sortBar && (
            <Select label="Sort by" options={sortOptions} value={sortValue}
              onChange={(picked) => { const next = parseSortOption(picked); if (next) onSortChange?.(next); }} />
          )}
          {bare && (
            <div className={tableStyles({ narrow: true }).empty()}>{empty}</div>
          )}
          {rowEls.map((row, ri) => (React.isValidElement(row)
            ? React.cloneElement(row, { rowIndex: ri + 1, columns, layout: 'card' })
            : row))}
        </div>
      ) : bare ? (
        <div className={tableStyles({ narrow: false }).empty()}>{empty}</div>
      ) : (
        <>
          <table role="grid" aria-label={label} ref={gridRef}
            onKeyDown={onGridKeyDown}
            className={tableStyles({ narrow: false }).table()}>
            <thead>
              <tr role="row" className={tableStyles({ narrow: false }).headRow()}>
                {columns.map((c, ci) => (
                  <th key={ci} role="columnheader" {...headerNav(ci)}
                    aria-sort={sortStateOf(ci)}
                    onClick={c.sortable && sort ? () => onHeaderActivate(ci) : undefined}
                    className={headerClass(c)}
                    style={{ width: c.width }}>{c.header}{sortStateOf(ci) && sortStateOf(ci) !== 'none' && (
                        <i aria-hidden="true"
                          className={`${tableStyles({ narrow: false }).sortCaret()} ${sort?.direction === 'asc' ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down'}`} />
                      )}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rowEls.map((row, ri) => (React.isValidElement(row)
                ? React.cloneElement(row, {
                  rowIndex: ri + 1,
                  columns,
                  layout: 'table',
                  cursorCol: curRow === ri + 1 ? curCol : null,
                  onCellFocus,
                })
                : row))}
            </tbody>
          </table>
        </>
      )}
      {!bare && page && (
        <div className={tableStyles({ narrow: false }).pager()}>
          <Pagination page={page.index} pageCount={pageCount} ariaLabel={label}
            onChange={(next) => onPageChange?.(next)} />
        </div>
      )}
    </div>
  );
}

// frameworks/angular/components/display/table/Table.ts
import {
  ChangeDetectionStrategy, Component, ElementRef, afterRenderEffect, booleanAttribute, computed,
  contentChildren, effect, inject, input, output, untracked,
} from '@angular/core';
import type {
  SelectOption, TableColumn, TablePage, TableSort, TableSortControl,
} from '../../../Api.generated';
import { containerWidth, readBreakpoint } from '../../../ContainerSize';
import { warnOnce } from '../../../WarnOnce';
import { Pagination } from '../../navigation/pagination/Pagination';
import { Select } from '../../forms/select/Select';
import { TableRow } from '../table-row/TableRow';
import { TableState } from './TableState';
import { tableStyles } from './Table.variants';

export function sortOptionValue(column: number, direction: TableSort['direction']): string {
  return `${column}:${direction}`;
}

export function parseSortOption(value: string): TableSort | null {
  const [column, direction] = value.split(':');
  const index = Number.parseInt(column ?? '', 10);
  if (!Number.isInteger(index) || (direction !== 'asc' && direction !== 'desc')) return null;
  return { column: index, direction };
}

@Component({
  selector: 'arena-table',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [TableState],
  imports: [Pagination, Select],
  host: { '[class]': 'styles().root()' },
  template: `
    @if (sortBar()) {
      <div [class]="styles().sortBar()">
        <div [class]="styles().sortField()">
          <arena-select [label]="sortLabel" [options]="sortOptions()" [value]="sortValue()"
                        (change)="onSortPick($event)" />
        </div>
      </div>
    }
    <div [class]="styles().grid()" [attr.role]="gridRole()"
         [attr.aria-label]="empty() ? null : gridLabel()" (keydown)="onKeydown($event)">
      @if (!narrow() && !empty()) {
        <div role="row" [class]="styles().headRow()">
          @for (column of columns(); track $index; let i = $index) {
            <div role="columnheader" [class]="headerClass(column)" [style.width]="column.width"
                 [attr.tabindex]="state.isStop(0, i) ? 0 : -1"
                 [attr.aria-sort]="sortStateOf(i)"
                 (focus)="moveTo(0, i)" (click)="onHeader(i)">{{ column.header }}@if (sortStateOf(i) !== null && sortStateOf(i) !== 'none') {
              <i [class]="styles().sortCaret() + ' ' + caretOf(i)" aria-hidden="true"></i>
            }</div>
          }
        </div>
      }
      <ng-content />
    </div>
    @if (empty()) {
      <div [class]="styles().empty()"><ng-content select="[empty]">No data.</ng-content></div>
    } @else if (page(); as paging) {
      <div [class]="styles().pager()">
        <arena-pagination [page]="paging.index" [pageCount]="pageCount()"
                          [ariaLabel]="gridLabel()" (change)="pageChange.emit($event)" />
      </div>
    }
  `,
})
export class Table {
  /** Names the grid for assistive technology. Required, and guarded at runtime: nothing can derive it; Calendar names its grid from the range it is showing, and a data table's subject is editorial. Say what the rows are, never "Table". */
  readonly label = input.required<string>();
  /** The columns, in order. A column heads and sets its cells; it never says what goes in them. */
  readonly columns = input.required<TableColumn[]>();
  /** Card mode below --bp-md. Set false only when the columns are meaningless apart. */
  readonly responsive = input(true, { transform: booleanAttribute });
  /** Which column the rows are ordered by and which way. Controlled: Table draws the caret and the aria-sort, and the consumer does the ordering, because Table does not hold the rows. Absent, no header is a sort target. */
  readonly sort = input<TableSort>();
  /** How the sort affordance is reached in CARD MODE, where there is no header row to activate and a `sortable` column therefore has no control under it at all. 'auto' draws one compact select above the cards, listing every sortable column in each direction, which is the shape a phone has room for; 'none' leaves card mode unsorted by hand, for a table whose order is the document's rather than the reader's. Above --bp-md the header row is the control and this member draws nothing. The header row does NOT come back below the breakpoint, because card mode exists for the one reason a grid does not fit. It is a member rather than something a consumer draws for themselves because the state it edits, TableSort, is Arena's: left to each consumer, the label, the option order and the way a direction is worded are invented once per project over a model they did not define. */
  readonly sortControl = input<TableSortControl>('auto');
  /** Which page of a longer list is on screen. Present, Table draws its own Pagination below the grid and names it from `label`, which is what gives that required name its uniqueness on a page with two paged tables. Absent, no pager is drawn and the projected rows are the whole list. */
  readonly page = input<TablePage>();
  /** A sortable header was activated, carrying the column and the direction it should become: the same column flips, a different one starts ascending. Table never reorders anything itself, so a consumer who ignores this event gets a caret that moves and rows that do not, which is why the member is controlled rather than a starting value. */
  readonly sortChange = output<TableSort>();
  /** A page was chosen, carrying the new 1-based page. It also fires with 1 when the current page has gone PAST THE END, which is the only reset Table performs; a filter that leaves the page in range is silent, so returning the reader to page one on a change of criterion stays the consumer's, beside the criterion they hold. */
  readonly pageChange = output<number>();

  protected readonly state = inject(TableState);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly measured = containerWidth();
  private readonly medium = readBreakpoint('md');

  protected readonly rows = contentChildren(TableRow);

  protected readonly narrow = computed(() => {
    const width = this.measured();
    return this.responsive() && width !== null && width < this.medium;
  });

  protected readonly gridLabel = computed(() => {
    const name = this.label();
    if (name.trim() === '') {
      throw new Error('Table: `label` is required, and names what the rows are — never "Table"');
    }
    return name;
  });

  protected readonly empty = computed(() => this.rows().length === 0);

  protected readonly gridRole = computed(() => (this.narrow() || this.empty() ? null : 'grid'));

  protected readonly pageCount = computed(() => {
    const paging = this.page();
    if (!paging) return 1;
    return Math.max(1, Math.ceil(paging.total / Math.max(1, paging.size)));
  });

  protected readonly styles = computed(() => tableStyles({ narrow: this.narrow() }));

  protected readonly sortLabel = 'Sort by';

  protected readonly sortable = computed(() => this.columns()
    .map((column, index) => ({ column, index }))
    .filter(({ column }) => column.sortable));

  protected readonly sortBar = computed(() => this.narrow() && !this.empty()
    && this.sortControl() !== 'none' && Boolean(this.sort()) && this.sortable().length > 0);

  protected readonly sortOptions = computed<SelectOption[]>(() => this.sortable().flatMap(
    ({ column, index }) => [
      { value: sortOptionValue(index, 'asc'), label: `${column.header} \u2191` },
      { value: sortOptionValue(index, 'desc'), label: `${column.header} \u2193` },
    ],
  ));

  protected readonly sortValue = computed(() => {
    const current = this.sort();
    return current ? sortOptionValue(current.column, current.direction) : undefined;
  });

  protected onSortPick(value: string): void {
    const picked = parseSortOption(value);
    if (picked) this.sortChange.emit(picked);
  }

  protected sortStateOf(column: number): string | null {
    if (!this.columns()[column]?.sortable || !this.sort()) return null;
    const current = this.sort();
    if (current?.column !== column) return 'none';
    return current.direction === 'asc' ? 'ascending' : 'descending';
  }

  protected caretOf(column: number): string {
    return this.sort()?.direction === 'asc' ? 'ph-bold ph-caret-up' : 'ph-bold ph-caret-down';
  }

  protected headerClass(column: TableColumn): string {
    const base = tableStyles({ narrow: false, align: column.align ?? 'left' }).th();
    return column.sortable && this.sort() ? `${base} ${this.styles().thSortable()}` : base;
  }

  protected onHeader(column: number): void {
    if (!this.columns()[column]?.sortable) return;
    const current = this.sort();
    if (!current) return;
    this.sortChange.emit(current.column === column
      ? { column, direction: current.direction === 'asc' ? 'desc' : 'asc' }
      : { column, direction: 'asc' });
  }

  constructor() {
    this.state.columns = this.columns;
    this.state.narrow = this.narrow;
    this.state.rows = this.rows;

    effect(() => {
      const paging = this.page();
      const pages = this.pageCount();
      if (!paging || paging.index <= pages) return;
      untracked(() => this.pageChange.emit(1));
    });

    effect(() => {
      const current = this.sort();
      const columns = this.columns();
      if (!current) return;
      const column = columns[current.column];
      if (column?.sortable) return;
      const name = column ? `"${column.header}"` : 'no column at all';
      warnOnce(`Table "${untracked(() => this.label())}": sort.column ${current.column} is ${name},`
        + ' which does not declare `sortable`, so no header is a target and the caret is not drawn.'
        + ' TableSort.column is an INDEX, so moving a column reorders the rows in silence; keep the'
        + ' sort field inside the column entry it belongs to and the two move together.');
    });

    afterRenderEffect(() => {
      this.state.clamped();
      const grid = this.host.nativeElement.querySelector('[role="grid"]');
      if (!grid) return;
      const active = grid.ownerDocument.activeElement;
      if (!active || !grid.contains(active)) return;
      const role = active.getAttribute('role');
      if (role !== 'gridcell' && role !== 'columnheader') return;
      const stop = grid.querySelector<HTMLElement>(
        '[role="gridcell"][tabindex="0"], [role="columnheader"][tabindex="0"]',
      );
      if (stop && stop !== active) stop.focus();
    });
  }

  protected moveTo(row: number, col: number): void {
    if (!this.state.isStop(row, col)) this.state.cursor.set({ row, col });
  }

  protected onKeydown(event: KeyboardEvent): void {
    const target = event.target as Element | null;
    const role = target?.getAttribute?.('role');
    if (role !== 'gridcell' && role !== 'columnheader') return;

    const lengths = this.state.lengths();
    const at = this.state.clamped();
    let { row, col } = at;

    if (event.key === 'Enter' && at.row === 0) {
      event.preventDefault();
      this.onHeader(at.col);
      return;
    }
    if (event.key === ' ' && at.row === 0) {
      event.preventDefault();
      this.onHeader(at.col);
      return;
    }
    if (event.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (event.key === 'ArrowDown') row = Math.min(lengths.length - 1, row + 1);
    else if (event.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (event.key === 'ArrowRight') col = Math.min(Math.max((lengths[row] ?? 1) - 1, 0), col + 1);
    else if (event.key === 'Home') col = 0;
    else if (event.key === 'End') col = Math.max((lengths[row] ?? 1) - 1, 0);
    else if (event.key === 'Enter') {
      event.preventDefault();
      if (at.row > 0) this.state.activate(at.row);
      return;
    } else return;

    col = Math.min(col, Math.max((lengths[row] ?? 1) - 1, 0));
    event.preventDefault();
    this.moveTo(row, col);
  }
}
