// frameworks/react/components/display/table/Table.jsx
import React, { useEffect, useRef, useState } from 'react';
import { useContainerWidth, readBreakpoint } from '../../../UseContainerWidth.js';
import { HEADER_LABEL, CELL_BASE } from '../table-cell/TableCell.jsx';

export function Table({ columns, children, empty = 'No data.', responsive = true, label }) {
  if (!label?.trim()) throw new Error('Table: `label` is required');
  if (columns == null) throw new Error('Table: `columns` is required');
  const [ref, width] = useContainerWidth();

  const narrow = responsive && width !== null && width < readBreakpoint('md');

  const rowEls = React.Children.toArray(children);

  const gridRef = useRef(null);
  const [gridFocused, setGridFocused] = useState(false);
  const [cursor, setCursor] = useState({ row: 0, col: 0 });

  const cellCounts = rowEls.map((row) => (
    React.isValidElement(row) ? React.Children.toArray(row.props.children).length : 0
  ));
  const rowLens = [columns.length, ...(rowEls.length === 0 ? [1] : cellCounts)];

  const curRow = Math.min(Math.max(cursor.row, 0), Math.max(rowLens.length - 1, 0));
  const curCol = Math.min(Math.max(cursor.col, 0), Math.max((rowLens[curRow] || 0) - 1, 0));

  useEffect(() => {
    const g = gridRef.current;
    if (!g) return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active)) return;

    const activeRole = active.getAttribute && active.getAttribute('role');
    if (activeRole !== 'gridcell' && activeRole !== 'columnheader') return;
    const cell = g.querySelector('[role="gridcell"][tabindex="0"], [role="columnheader"][tabindex="0"]');
    if (cell && cell !== active) cell.focus();
  }, [curRow, curCol]);

  const onGridKeyDown = (e) => {
    const t = e.target;
    if (!t || typeof t.getAttribute !== 'function') return;
    const role = t.getAttribute('role');

    if (role !== 'gridcell' && role !== 'columnheader') return;

    let row = curRow;
    let col = curCol;
    if (e.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (e.key === 'ArrowDown') row = Math.min(rowLens.length - 1, row + 1);
    else if (e.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (e.key === 'ArrowRight') col = Math.min(Math.max((rowLens[row] || 1) - 1, 0), col + 1);

    else if (e.key === 'Home') col = 0;
    else if (e.key === 'End') col = Math.max((rowLens[row] || 1) - 1, 0);
    else if (e.key === 'Enter') {

      e.preventDefault();
      const rowEl = curRow > 0 ? rowEls[curRow - 1] : null;
      if (rowEl && React.isValidElement(rowEl) && rowEl.props.onClick) rowEl.props.onClick();
      return;
    } else return;

    col = Math.min(col, Math.max((rowLens[row] || 1) - 1, 0));

    e.preventDefault();

    if (row !== curRow || col !== curCol) setCursor({ row, col });
  };

  const onCellFocus = (ri, ci) => {
    if (ri !== curRow || ci !== curCol) setCursor({ row: ri, col: ci });
  };

  const headerNav = (ci) => ({
    tabIndex: 0 === curRow && ci === curCol ? 0 : -1,
    onFocus: (e) => { if (e.target === e.currentTarget) onCellFocus(0, ci); },
  });

  const cellRing = (ri, ci) => ({
    outline: 'none',
    boxShadow: ri === curRow && ci === curCol && gridFocused
      ? 'inset 0 0 0 var(--focus-width) var(--focus-ring)' : undefined,
  });

  return (
    <div ref={ref} style={{ width: '100%' }}>
      {narrow ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'calc(var(--sp-1) * 4)' }}>
          {rowEls.length === 0 && (
            <div style={{ background: 'var(--surface-card)', border: 'var(--bw) solid var(--color-base-300)',
              borderRadius: 'var(--r-lg)', padding: 'calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)', textAlign: 'center',
              color: 'var(--mute)', fontSize: 'var(--dz-text)' }}>{empty}</div>
          )}
          {rowEls.map((row, ri) => (React.isValidElement(row)
            ? React.cloneElement(row, { rowIndex: ri + 1, columns, layout: 'card' })
            : row))}
        </div>
      ) : (
        <div style={{ border: 'var(--bw) solid var(--color-base-300)', borderRadius: 'var(--r-lg)',
          overflow: 'hidden', background: 'var(--surface-card)' }}>
          {

}
          <table role="grid" aria-label={label} ref={gridRef}
            onKeyDown={onGridKeyDown}
            onFocus={() => setGridFocused(true)}
            onBlur={(e) => { if (!e.currentTarget.contains(e.relatedTarget)) setGridFocused(false); }}
            style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'var(--font-body)' }}>
            <thead>
              <tr role="row" style={{ background: 'var(--color-base-300)' }}>
                {columns.map((c, ci) => (
                  <th key={ci} role="columnheader" {...headerNav(ci)}
                    style={{ ...CELL_BASE, ...HEADER_LABEL, textAlign: c.align || 'left',
                      width: c.width, borderBottom: 'var(--bw) solid var(--color-base-300)',
                      ...cellRing(0, ci) }}>{c.header}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rowEls.length === 0 && (
                <tr role="row"><td role="gridcell" colSpan={columns.length}
                  tabIndex={curRow === 1 && curCol === 0 ? 0 : -1}
                  onFocus={(e) => { if (e.target === e.currentTarget) onCellFocus(1, 0); }}
                  style={{ ...CELL_BASE, textAlign: 'center', color: 'var(--mute)',
                    padding: 'calc(var(--sp-1) * 8) calc(var(--sp-1) * 4)',
                    ...cellRing(1, 0) }}>{empty}</td></tr>
              )}
              {rowEls.map((row, ri) => (React.isValidElement(row)
                ? React.cloneElement(row, {
                  rowIndex: ri + 1,
                  columns,
                  layout: 'table',
                  cursorCol: curRow === ri + 1 ? curCol : null,
                  gridFocused,
                  onCellFocus,
                })
                : row))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// frameworks/angular/components/display/table/Table.ts
import {
  ChangeDetectionStrategy, Component, ElementRef, afterRenderEffect, booleanAttribute, computed,
  contentChildren, inject, input,
} from '@angular/core';
import type { TableColumn } from '../../../Api.generated';
import { containerWidth, readBreakpoint } from '../../../ContainerSize';
import { TableRow } from '../table-row/TableRow';
import { TableState } from './TableState';
import { tableStyles } from './Table.variants';

@Component({
  selector: 'arena-table',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [TableState],
  host: { '[class]': 'styles().root()' },
  template: `
    <div [class]="styles().grid()" [attr.role]="narrow() ? null : 'grid'"
         [attr.aria-label]="gridLabel()" (keydown)="onKeydown($event)">
      @if (!narrow()) {
        <div role="row" [class]="styles().headRow()">
          @for (column of columns(); track $index; let i = $index) {
            <div role="columnheader" [class]="headerClass(column)" [style.width]="column.width"
                 [attr.tabindex]="state.isStop(0, i) ? 0 : -1"
                 (focus)="moveTo(0, i)">{{ column.header }}</div>
          }
        </div>
      }
      <ng-content />
    </div>
    @if (rows().length === 0) {
      <div [class]="styles().empty()"><ng-content select="[empty]" /></div>
    }
  `,
})
export class Table {
  readonly label = input.required<string>();
  readonly columns = input.required<TableColumn[]>();
  readonly responsive = input(true, { transform: booleanAttribute });

  protected readonly state = inject(TableState);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly measured = containerWidth();
  private readonly medium = readBreakpoint('md');

  protected readonly rows = contentChildren(TableRow);

  protected readonly narrow = computed(() => {
    const width = this.measured();
    return this.responsive() && width !== null && width < this.medium;
  });

  protected readonly gridLabel = computed(() => {
    const name = this.label();
    if (name.trim() === '') {
      throw new Error('Table: `label` is required, and names what the rows are — never "Table"');
    }
    return name;
  });

  protected readonly styles = computed(() => tableStyles({ narrow: this.narrow() }));

  constructor() {
    this.state.columns = this.columns;
    this.state.narrow = this.narrow;
    this.state.rows = this.rows;

    afterRenderEffect(() => {
      this.state.clamped();
      const grid = this.host.nativeElement.querySelector('[role="grid"]');
      if (!grid) return;
      const active = grid.ownerDocument.activeElement;
      if (!active || !grid.contains(active)) return;
      const role = active.getAttribute('role');
      if (role !== 'gridcell' && role !== 'columnheader') return;
      const stop = grid.querySelector<HTMLElement>(
        '[role="gridcell"][tabindex="0"], [role="columnheader"][tabindex="0"]',
      );
      if (stop && stop !== active) stop.focus();
    });
  }

  protected headerClass(column: TableColumn): string {
    return tableStyles({ narrow: false, align: column.align ?? 'left' }).th();
  }

  protected moveTo(row: number, col: number): void {
    if (!this.state.isStop(row, col)) this.state.cursor.set({ row, col });
  }

  protected onKeydown(event: KeyboardEvent): void {
    const target = event.target as Element | null;
    const role = target?.getAttribute?.('role');
    if (role !== 'gridcell' && role !== 'columnheader') return;

    const lengths = this.state.lengths();
    const at = this.state.clamped();
    let { row, col } = at;

    if (event.key === 'ArrowUp') row = Math.max(0, row - 1);
    else if (event.key === 'ArrowDown') row = Math.min(lengths.length - 1, row + 1);
    else if (event.key === 'ArrowLeft') col = Math.max(0, col - 1);
    else if (event.key === 'ArrowRight') col = Math.min(Math.max((lengths[row] ?? 1) - 1, 0), col + 1);
    else if (event.key === 'Home') col = 0;
    else if (event.key === 'End') col = Math.max((lengths[row] ?? 1) - 1, 0);
    else if (event.key === 'Enter') {
      event.preventDefault();
      if (at.row > 0) this.state.activate(at.row);
      return;
    } else return;

    col = Math.min(col, Math.max((lengths[row] ?? 1) - 1, 0));
    event.preventDefault();
    this.moveTo(row, col);
  }
}
