// frameworks/angular/components/display/calendar/Calendar.ts
import {
  ChangeDetectionStrategy, Component, DestroyRef, ElementRef, afterNextRender, afterRenderEffect,
  booleanAttribute, computed, contentChild, contentChildren, inject, input, linkedSignal,
  numberAttribute, output, signal,
} from '@angular/core';
import type { CalendarView } from '../../../Api.generated';
import { containerWidth, readBreakpoint } from '../../../ContainerSize';
import { ArenaActions } from '../../../ProjectionMarkers';
import { CalendarEvent } from '../calendar-event/CalendarEvent';
import { CalendarState, type ChipPlacement, type HourSlot } from './CalendarState';
import {
  addDays, defaultDayStart, formatDate, formatHM, layoutDay, nowMinutes, parseHM, placeEvents,
  rangeTitle, startOfWeek, todayIso, weekdayOf,
} from './CalendarInternals';
import { calendarStyles } from './Calendar.variants';

const MINUTE = 60000;

@Component({
  selector: 'arena-calendar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [CalendarState],
  host: { style: 'display: contents' },
  template: `
    <section [class]="styles().root()" [attr.aria-label]="'Schedule, ' + title()">
      <div [class]="styles().toolbar()">
        <button type="button" [class]="styles().nav()" aria-label="Previous" (click)="step(-1)">
          <i class="ph-bold ph-caret-left" aria-hidden="true"></i>
        </button>
        <button type="button" [class]="styles().today()" (click)="goto(today())">Today</button>
        <button type="button" [class]="styles().nav()" aria-label="Next" (click)="step(1)">
          <i class="ph-bold ph-caret-right" aria-hidden="true"></i>
        </button>
        <h2 [class]="styles().heading()">{{ title() }}</h2>
        @if (actionsSlot()) {
          <div [class]="styles().actions()"><ng-content select="[actions]" /></div>
        }
      </div>

      <div [class]="styles().headStrip()" [style.gridTemplateColumns]="tracks()">
        @for (day of days(); track day) {
          <div [class]="styles().dayHead()" (click)="onDateClick(day)">
            <div [class]="styles().weekday()">{{ weekdayOf(day) }}</div>
            <div [class]="dayNumberClass(day)">{{ dayNumberOf(day) }}</div>
          </div>
        }
      </div>

      <div [class]="styles().scroll()">
        <div [class]="styles().body()" [style.height.px]="bodyHeight()">
          <div [class]="styles().gutter()">
            @for (hour of hours(); track hour) {
              <div [class]="styles().hourLabel()" [style.top.px]="state.y(hour)">{{ hm(hour) }}</div>
            }
          </div>

          <div role="grid" [class]="styles().grid()" [style.gridTemplateColumns]="tracks()"
               [attr.aria-label]="'Schedule grid, ' + title()" (keydown)="onKeydown($event)">
            @for (hour of hours(); track hour) {
              <div aria-hidden="true" [class]="styles().rule()" [style.top.px]="state.y(hour)"></div>
            }

            @for (day of days(); track day; let di = $index) {
              <div role="row" [class]="columnClass(di)" [attr.aria-label]="dayLabel(day)"
                   [attr.aria-owns]="state.ownedIds(day)" (click)="onDateClick(day)">
                @for (slot of slots(); track slot.start; let si = $index) {
                  <div role="gridcell" [class]="styles().cell()" [attr.aria-label]="hm(slot.start)"
                       [attr.tabindex]="state.isStop(di, si) ? 0 : -1"
                       [style.top.px]="state.y(slot.start)"
                       [style.height.px]="state.y(slot.end) - state.y(slot.start)"
                       (focus)="moveTo(di, si)"></div>
                }
              </div>
            }

            <ng-content />

            @if (showNow()) {
              <div aria-hidden="true" [class]="styles().now()" [style.top.px]="state.y(nowMin())">
                <span [class]="styles().nowDot()"></span>
              </div>
            }
          </div>
        </div>
      </div>
    </section>
  `,
})
export class Calendar {
  readonly timeZone = input<string>();
  readonly anchorDate = input<string>();
  readonly view = input<CalendarView>();
  readonly dayStart = input<string>();
  readonly dayEnd = input('23:00');
  readonly weekStartsOn = input(1, { transform: numberAttribute });
  readonly hideEmptyWeekend = input(true, { transform: booleanAttribute });
  readonly dateClick = output<string>();
  readonly rangeChange = output<string>();

  protected readonly state = inject(CalendarState);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);
  private readonly measured = containerWidth();
  private readonly medium = readBreakpoint('md');
  private readonly tick = signal(0);

  protected readonly actionsSlot = contentChild(ArenaActions);
  protected readonly chips = contentChildren(CalendarEvent);

  protected readonly zone = computed(
    () => this.timeZone() || Intl.DateTimeFormat().resolvedOptions().timeZone,
  );

  protected readonly anchor = linkedSignal(() => this.anchorDate() ?? todayIso(this.zone()));

  protected readonly activeView = computed<CalendarView>(() => {
    const chosen = this.view();
    if (chosen) return chosen;
    const width = this.measured();
    return width !== null && width < this.medium ? 'day' : 'week';
  });

  private readonly placed = computed(() => placeEvents(
    this.chips().map((chip) => ({ id: chip.id(), start: chip.start(), end: chip.end(), chip })),
    this.zone(),
  ));

  protected readonly days = computed<readonly string[]>(() => {
    if (this.activeView() === 'day') return [this.anchor()];
    const first = startOfWeek(this.anchor(), this.weekStartsOn());
    const all = Array.from({ length: 7 }, (_, i) => addDays(first, i));
    if (!this.hideEmptyWeekend()) return all;
    return all.filter((d) => weekdayOf(d) !== 0 || this.placed().some((p) => p.dayIso === d));
  });

  private readonly visible = computed(
    () => this.placed().filter((p) => this.days().includes(p.dayIso)),
  );

  private readonly byDay = computed(
    () => this.days().map((d) => layoutDay(this.visible().filter((p) => p.dayIso === d))),
  );

  private readonly placements = computed<ReadonlyMap<object, ChipPlacement>>(() => {
    const out = new Map<object, ChipPlacement>();
    this.byDay().forEach((laid, dayIndex) => {
      for (const p of laid) {
        out.set(p.ev.chip, {
          dayIndex, dayIso: p.dayIso, startMin: p.startMin, endMin: p.endMin,
          col: p.col, cols: p.cols,
        });
      }
    });
    return out;
  });

  private readonly endMin = computed(() => parseHM(this.dayEnd(), 23 * 60));

  private readonly firstMin = computed(() => {
    const declared = this.dayStart();
    const raw = declared !== undefined ? parseHM(declared, 8 * 60) : defaultDayStart(this.visible());
    return Math.max(0, Math.min(raw, this.endMin() - 60));
  });

  protected readonly hours = computed(() => {
    const out: number[] = [];
    for (let m = Math.ceil(this.firstMin() / 60) * 60; m <= this.endMin(); m += 60) out.push(m);
    return out;
  });

  protected readonly slots = computed<readonly HourSlot[]>(() => {
    const hours = this.hours();
    return hours
      .map((start, i) => ({ start, end: i + 1 < hours.length ? hours[i + 1] : this.endMin() }))
      .filter((slot) => slot.end > slot.start);
  });

  protected readonly today = computed(() => todayIso(this.zone()));

  protected readonly nowMin = computed(() => {
    this.tick();
    return nowMinutes(this.zone());
  });

  protected readonly showNow = computed(
    () => this.days().includes(this.today())
      && this.nowMin() >= this.firstMin() && this.nowMin() <= this.endMin(),
  );

  protected readonly title = computed(() => rangeTitle(this.days()));

  protected readonly tracks = computed(
    () => `repeat(${this.days().length}, minmax(0, 1fr))`,
  );

  protected readonly bodyHeight = computed(() => this.state.y(this.endMin()));

  protected readonly styles = computed(() => calendarStyles());

  constructor() {
    this.state.zone = this.zone;
    this.state.days = this.days;
    this.state.slots = this.slots;
    this.state.startMin = this.firstMin;
    this.state.width = this.measured;
    this.state.placements = this.placements;
    this.state.focusCursorCell = () => this.focusCursorCell();

    afterNextRender(() => {
      const id = setInterval(() => this.tick.update((n) => n + 1), MINUTE);
      this.destroyRef.onDestroy(() => clearInterval(id));
    });

    afterRenderEffect(() => {
      this.state.clamped();
      const grid = this.host.nativeElement.querySelector('[role="grid"]');
      if (!grid) return;
      const active = grid.ownerDocument.activeElement;
      if (!active || !grid.contains(active)) return;
      if (active.getAttribute('role') !== 'gridcell') return;
      const stop = grid.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
      if (stop && stop !== active) stop.focus();
    });
  }

  protected hm(min: number): string {
    return formatHM(min);
  }

  protected weekdayOf(day: string): string {
    return formatDate(day, { weekday: 'short' });
  }

  protected dayNumberOf(day: string): string {
    return formatDate(day, { day: 'numeric' });
  }

  protected dayLabel(day: string): string {
    return formatDate(day, { weekday: 'long', day: 'numeric', month: 'long' });
  }

  protected dayNumberClass(day: string): string {
    return calendarStyles({ today: day === this.today() }).dayNumber();
  }

  protected columnClass(index: number): string {
    return calendarStyles({ firstColumn: index === 0 }).column();
  }

  protected goto(iso: string): void {
    this.anchor.set(iso);
    this.rangeChange.emit(iso);
  }

  protected step(direction: number): void {
    this.goto(addDays(this.anchor(), direction * (this.activeView() === 'day' ? 1 : 7)));
  }

  protected onDateClick(day: string): void {
    this.dateClick.emit(day);
  }

  protected moveTo(day: number, hour: number): void {
    if (!this.state.isStop(day, hour)) this.state.cursor.set({ day, hour });
  }

  protected onKeydown(event: KeyboardEvent): void {
    const target = event.target as Element | null;
    if (target?.getAttribute?.('role') !== 'gridcell') {
      if (event.key === 'Escape') {
        event.preventDefault();
        this.focusCursorCell();
      }
      return;
    }

    const at = this.state.clamped();
    let { day, hour } = at;
    const lastDay = Math.max(this.days().length - 1, 0);
    const lastHour = Math.max(this.slots().length - 1, 0);

    if (event.key === 'ArrowLeft') day = Math.max(0, day - 1);
    else if (event.key === 'ArrowRight') day = Math.min(lastDay, day + 1);
    else if (event.key === 'ArrowUp') hour = Math.max(0, hour - 1);
    else if (event.key === 'ArrowDown') hour = Math.min(lastHour, hour + 1);
    else if (event.key === 'Home') hour = 0;
    else if (event.key === 'End') hour = lastHour;
    else if (event.key === 'Enter') {
      event.preventDefault();
      const slot = this.slots()[at.hour];
      if (slot) this.state.focusOverlapping(at.day, slot.start, slot.end);
      return;
    } else return;

    event.preventDefault();
    this.moveTo(day, hour);
  }

  private focusCursorCell(): void {
    const cell = this.host.nativeElement
      .querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]');
    if (cell) cell.focus();
  }
}

// frameworks/react/components/display/calendar/Calendar.jsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useContainerWidth, readBreakpoint } from '../../../UseContainerWidth.js';
import { catColor } from '../../../DataVisuals.js';
import { calendarHourH } from '../../../Tokens.generated.js';
import {
  addDays, defaultDayStart, formatHM, layoutDay, nowMinutes, parseHM,
  placeEvents, rangeTitle, startOfWeek, todayIso, weekdayOf, formatDate,
} from './CalendarInternals.js';

const GUTTER = 'calc(var(--sp-1) * 14)';

export function Calendar({
  children, timeZone, anchorDate, view,
  dayStart, dayEnd = '23:00', weekStartsOn = 1, hideEmptyWeekend = true,
  onDateClick, onRangeChange, actions,
}) {

  const zone = timeZone || Intl.DateTimeFormat().resolvedOptions().timeZone;
  const [ref, width] = useContainerWidth();
  const [anchor, setAnchor] = useState(() => anchorDate || todayIso(zone));

  useEffect(() => { if (anchorDate) setAnchor(anchorDate); }, [anchorDate]);

  const [tick, setTick] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setTick((n) => n + 1), 60000);
    return () => clearInterval(id);
  }, []);

  const narrow = width !== null && width < readBreakpoint('md');
  const activeView = view || (narrow ? 'day' : 'week');

  const kids = useMemo(
    () => React.Children.toArray(children).filter(React.isValidElement),
    [children],
  );
  const events = useMemo(() => kids.map((k) => k.props), [kids]);
  const elementOf = useMemo(() => new Map(kids.map((k) => [k.props, k])), [kids]);

  const placed = useMemo(() => placeEvents(events, zone), [events, zone]);

  const days = useMemo(() => {
    if (activeView === 'day') return [anchor];
    const first = startOfWeek(anchor, weekStartsOn);
    const all = Array.from({ length: 7 }, (_, i) => addDays(first, i));
    if (!hideEmptyWeekend) return all;

    return all.filter((d) => weekdayOf(d) !== 0 || placed.some((p) => p.dayIso === d));
  }, [activeView, anchor, weekStartsOn, hideEmptyWeekend, placed]);

  const visible = useMemo(() => placed.filter((p) => days.includes(p.dayIso)), [placed, days]);
  const byDay = useMemo(
    () => days.map((d) => layoutDay(visible.filter((p) => p.dayIso === d))),
    [days, visible],
  );

  const endMin = parseHM(dayEnd, 23 * 60);
  const rawStart = dayStart !== undefined ? parseHM(dayStart, 8 * 60) : defaultDayStart(visible);

  const startMin = Math.max(0, Math.min(rawStart, endMin - 60));

  const y = (min) => ((min - startMin) / 60) * calendarHourH;
  const hours = [];
  for (let m = Math.ceil(startMin / 60) * 60; m <= endMin; m += 60) hours.push(m);

  const slots = hours
    .map((m, i) => ({ start: m, end: i + 1 < hours.length ? hours[i + 1] : endMin }))
    .filter((s) => s.end > s.start);

  const today = todayIso(zone);
  const nowMin = useMemo(() => nowMinutes(zone), [zone, tick]);
  const showNow = days.includes(today) && nowMin >= startMin && nowMin <= endMin;

  const step = activeView === 'day' ? 1 : 7;
  const goto = (iso) => { setAnchor(iso); onRangeChange && onRangeChange(iso); };

  const gridRef = useRef(null);

  const eventRefs = useRef(new Map());
  const [gridFocused, setGridFocused] = useState(false);
  const [cursor, setCursor] = useState({ day: 0, hour: 0 });

  const curDay = Math.min(Math.max(cursor.day, 0), Math.max(days.length - 1, 0));
  const curHour = Math.min(Math.max(cursor.hour, 0), Math.max(slots.length - 1, 0));

  useEffect(() => {
    const g = gridRef.current;
    if (!g) return;
    const active = g.ownerDocument.activeElement;
    if (!active || !g.contains(active)) return;
    const cell = g.querySelector('[role="gridcell"][tabindex="0"]');
    if (cell && cell !== active) cell.focus();
  }, [curDay, curHour]);

  const focusCursorCell = () => {
    const cell = gridRef.current && gridRef.current.querySelector('[role="gridcell"][tabindex="0"]');
    if (cell) cell.focus();
  };

  const onGridKeyDown = (e) => {
    const t = e.target;
    if (!t || typeof t.getAttribute !== 'function') return;

    if (t.getAttribute('role') === 'gridcell') {
      let day = curDay;
      let hour = curHour;
      if (e.key === 'ArrowLeft') day = Math.max(0, day - 1);
      else if (e.key === 'ArrowRight') day = Math.min(days.length - 1, day + 1);
      else if (e.key === 'ArrowUp') hour = Math.max(0, hour - 1);
      else if (e.key === 'ArrowDown') hour = Math.min(slots.length - 1, hour + 1);

      else if (e.key === 'Home') hour = 0;
      else if (e.key === 'End') hour = slots.length - 1;
      else if (e.key === 'Enter') {

        e.preventDefault();
        const s = slots[curHour];
        const hit = s && (byDay[curDay] || []).find((p) => p.startMin < s.end && p.endMin > s.start);
        const node = hit && eventRefs.current.get(hit.ev.id);
        if (node) node.focus();
        return;
      } else return;

      e.preventDefault();

      if (day !== curDay || hour !== curHour) setCursor({ day, hour });
      return;
    }

    if (e.key === 'Escape') {
      e.preventDefault();
      focusCursorCell();
    }
  };

  const label = { fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-2xs)', letterSpacing: 'var(--ls-column-header)', textTransform: 'uppercase', color: 'var(--mute)', fontWeight: 'var(--fw-bold)' };
  const navBtn = (dir) => (
    <button type="button" aria-label={dir < 0 ? 'Previous' : 'Next'}
      onClick={() => goto(addDays(anchor, dir * step))}
      style={{ height: 'calc(var(--sp-1) * 8.5)', minWidth: 'calc(var(--sp-1) * 8.5)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        background: 'transparent', border: 'var(--bw) solid var(--color-base-300)', borderRadius: 'var(--r-sm)',
        color: 'var(--bone-dim)', cursor: 'pointer', fontSize: 'var(--icon-md)' }}>
      <i className={dir < 0 ? 'ph-bold ph-caret-left' : 'ph-bold ph-caret-right'} />
    </button>
  );

  return (
    <section ref={ref} aria-label={`Schedule, ${rangeTitle(days)}`}
      style={{ display: 'flex', flexDirection: 'column', width: '100%', fontFamily: 'var(--font-body)' }}>

      <div style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2)', marginBottom: 'calc(var(--sp-1) * 3)', flexWrap: 'wrap' }}>
        {navBtn(-1)}
        <button type="button" onClick={() => goto(today)}
          style={{ height: 'calc(var(--sp-1) * 8.5)', padding: '0 calc(var(--sp-1) * 3)', background: 'transparent', border: 'var(--bw) solid var(--color-base-300)',
            borderRadius: 'var(--r-sm)', color: 'var(--bone-dim)', cursor: 'pointer',
            fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text-md)', fontWeight: 'var(--fw-semibold)' }}>Today</button>
        {navBtn(1)}
        <h2 style={{ margin: '0 0 0 calc(var(--sp-1) * 1)', fontSize: 'var(--fs-md)', fontWeight: 'var(--fw-semibold)', color: 'var(--text-strong)' }}>
          {rangeTitle(days)}
        </h2>
        {actions && <div style={{ marginLeft: 'auto', display: 'flex', gap: 'calc(var(--sp-1) * 2)', flexWrap: 'wrap' }}>{actions}</div>}
      </div>

      <div style={{ display: 'flex', paddingLeft: GUTTER, borderBottom: 'var(--bw) solid var(--color-base-300)' }}>
        {days.map((d) => {
          const isToday = d === today;
          return (
            <div key={d} onClick={onDateClick ? () => onDateClick(d) : undefined}
              style={{ flex: 1, minWidth: 0, padding: 'calc(var(--sp-1) * 1.5) calc(var(--sp-1) * 2) 0', textAlign: 'center',
                cursor: onDateClick ? 'pointer' : 'default' }}>
              <div style={label}>{formatDate(d, { weekday: 'short' })}</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text)', fontWeight: 'var(--fw-bold)', marginTop: 'calc(var(--sp-1) * 0.5)',
                color: isToday ? 'var(--crimson)' : 'var(--bone-dim)' }}>
                {formatDate(d, { day: 'numeric' })}
              </div>
            </div>
          );
        })}
      </div>

      {

}
      <div style={{ flex: 1, minHeight: 0, overflowY: 'auto', paddingTop: 'calc(var(--sp-1) * 2)', paddingBottom: 'calc(var(--sp-1) * 2)' }}>
        <div style={{ display: 'flex', position: 'relative', height: y(endMin) }}>

          <div style={{ width: GUTTER, flexShrink: 0, position: 'relative' }}>
            {hours.map((m) => (
              <div key={m} style={{ ...label, position: 'absolute', top: `calc(${y(m)}px - var(--sp-1))`, right: 'calc(var(--sp-1) * 2)', letterSpacing: 'var(--ls-uppercase-status)' }}>
                {formatHM(m)}
              </div>
            ))}
          </div>

          {

}
          <div ref={gridRef} role="grid" aria-label={`Schedule grid, ${rangeTitle(days)}`}
            onKeyDown={onGridKeyDown}
            onFocus={() => setGridFocused(true)}
            onBlur={(e) => { if (!e.currentTarget.contains(e.relatedTarget)) setGridFocused(false); }}
            style={{ flex: 1, minWidth: 0, display: 'flex', position: 'relative' }}>
            {hours.map((m) => (
              <div key={m} aria-hidden="true" style={{ position: 'absolute', top: y(m), left: 0, right: 0,
                borderTop: 'var(--bw) solid var(--color-base-300)', pointerEvents: 'none' }} />
            ))}

            {days.map((d, di) => (
              <div key={d} role="row"
                aria-label={formatDate(d, { weekday: 'long', day: 'numeric', month: 'long' })}
                onClick={onDateClick ? () => onDateClick(d) : undefined}
                style={{ flex: 1, minWidth: 0, position: 'relative',
                  borderLeft: di === 0 ? 'none' : 'var(--bw) solid var(--color-base-300)',
                  cursor: onDateClick ? 'pointer' : 'default' }}>

                {

}
                {slots.map((s, si) => {
                  const isCursor = di === curDay && si === curHour;
                  return (
                    <div key={s.start} role="gridcell" aria-label={formatHM(s.start)}
                      tabIndex={isCursor ? 0 : -1}

                      onFocus={() => { if (di !== curDay || si !== curHour) setCursor({ day: di, hour: si }); }}
                      style={{ position: 'absolute', top: y(s.start), left: 0, right: 0,
                        height: y(s.end) - y(s.start), outline: 'none',
                        boxShadow: isCursor && gridFocused
                          ? 'inset 0 0 0 var(--focus-width) var(--focus-ring)' : undefined }} />
                  );
                })}

                {

}
                {byDay[di].map((p) => {
                  const color = catColor(p.ev.colorId ?? 1);
                  const top = y(p.startMin);
                  const rawH = y(p.endMin) - top;

                  const h = `max(calc(var(--sp-1) * 6.5), ${rawH}px)`;
                  return React.cloneElement(elementOf.get(p.ev), {
                    ref: (node) => {
                      if (node) eventRefs.current.set(p.ev.id, node);
                      else eventRefs.current.delete(p.ev.id);
                    },

                    tabIndex: -1,
                    box: { top, height: h,
                      left: `calc(${(p.col / p.cols) * 100}% + calc(var(--sp-1) * 0.5))`,
                      width: `calc(${(1 / p.cols) * 100}% - var(--sp-1))` },
                    color,
                    timeLabel: `${formatHM(p.startMin)} – ${formatHM(p.endMin)}`,
                    dateLabel: formatDate(d, { weekday: 'long', day: 'numeric', month: 'long' }),
                    showTime: rawH >= 32,
                  });
                })}
              </div>
            ))}

            {showNow && (
              <div aria-hidden="true" style={{ position: 'absolute', top: y(nowMin), left: 0, right: 0,
                borderTop: 'var(--bw-strong) solid var(--crimson)', pointerEvents: 'none', zIndex: 1 }}>
                <span style={{ position: 'absolute', top: 'calc(var(--sp-1) * -1)', left: 'calc(var(--sp-1) * -1)', width: 'calc(var(--sp-1) * 1.5)', height: 'calc(var(--sp-1) * 1.5)',
                  borderRadius: '50%', background: 'var(--crimson)' }} />
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
