// frameworks/react/components/charts/chart-card/ChartCard.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './ChartCard.manifest.generated.ts';

export interface ChartCardProps {

  /** The card heading. Absent renders no head unless `actions` is present. */
  title?: string;

  /** Controls in the head row, right-aligned beside the title. */
  actions?: React.ReactNode;
  /** The chart (or any body) the card frames. */
  children?: React.ReactNode;
}


const chartCardStyles = tv(manifest);

export function ChartCard({ title, actions, children }: ChartCardProps) {
  const styles = chartCardStyles();
  return (
    <div className={styles.root()}>
      {(title || actions) && (
        <div className={styles.head()}>
          {title && <span className={styles.title()}>{title}</span>}
          {actions && <div className={styles.actions()}>{actions}</div>}
        </div>
      )}
      {children}
    </div>
  );
}

// frameworks/angular/components/charts/chart-card/ChartCard.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { ArenaActions } from '../../../ProjectionMarkers';
import { chartCardStyles } from './ChartCard.variants';

@Component({
  selector: 'arena-chart-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    @if (title() || actions()) {
      <div [class]="styles().head()">
        @if (title(); as label) {
          <span [class]="styles().title()">{{ label }}</span>
        }
        @if (actions()) {
          <div [class]="styles().actions()"><ng-content select="[actions]" /></div>
        }
      </div>
    }
    <ng-content />
  `,
})
export class ChartCard {
  /** The card heading. Absent renders no head unless `actions` is present. */
  readonly title = input<string>();

  protected readonly actions = contentChild(ArenaActions);

  protected readonly styles = computed(() => chartCardStyles());
}
