// frameworks/react/components/forms/checkbox/Checkbox.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Checkbox.manifest.generated.ts';

export interface CheckboxProps {

  /** Whether it is ticked. */
  checked?: boolean;

  /** Text beside the box. */
  label?: string;

  /** Blocks toggling and dims it. */
  disabled?: boolean;

  /** Must be checked for the form to submit. */
  required?: boolean;

  /** Submitted with the form. */
  name?: string;

  /** The value submitted under `name` when checked. */
  value?: string;

  /** Toggled; carries the new checked state. */
  onChange?: (checked: boolean) => void;
}


const checkboxStyles = tv(manifest);

export function Checkbox({ checked = false, onChange, label, disabled = false, required = false, name, value }: CheckboxProps) {
  const styles = checkboxStyles({ checked, disabled });
  return (
    <label className={styles.root()}>
      <span className={styles.box()}>
        {checked && (
          <svg className={styles.check()} viewBox="0 0 12 12" fill="none">
            <path d="M2 6l3 3 5-6" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        )}
      </span>
      {label && <span className={styles.label()}>{label}</span>}
      <input type="checkbox" checked={checked} name={name} value={value} required={required}
        onChange={(e) => onChange && onChange(e.target.checked)} disabled={disabled}
        className={styles.input()} />
    </label>
  );
}

// frameworks/angular/components/forms/checkbox/Checkbox.ts
import {
  ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output,
} from '@angular/core';
import { checkboxStyles } from './Checkbox.variants';

export const CHECK_GLYPH_STYLE = { width: 'var(--sp-3)', height: 'var(--sp-3)' };
export const CHECK_STROKE_STYLE = { strokeWidth: 'var(--bw-strong)' };

@Component({
  selector: 'arena-checkbox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: 'display: contents',
    '[attr.name]': 'null',
  },
  template: `
    <label [class]="styles().root()">
      <span [class]="styles().box()">
        @if (checked()) {
          <svg [class]="styles().check()" viewBox="0 0 12 12" fill="none" [style]="glyph">
            <path d="M2 6l3 3 5-6" stroke="currentColor" stroke-linecap="round"
                  stroke-linejoin="round" [style]="glyphStroke"></path>
          </svg>
        }
      </span>
      @if (label(); as text) {
        <span [class]="styles().label()">{{ text }}</span>
      }
      <input type="checkbox" [class]="styles().input()" [checked]="checked()"
             [attr.name]="name()" [attr.value]="value()" [required]="required()"
             [disabled]="disabled()" (change)="onChange($event)" />
    </label>
  `,
})
export class Checkbox {
  /** Whether it is ticked. */
  readonly checked = input(false, { transform: booleanAttribute });
  /** Text beside the box. */
  readonly label = input<string>();
  /** Blocks toggling and dims it. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Must be checked for the form to submit. */
  readonly required = input(false, { transform: booleanAttribute });
  /** Submitted with the form. */
  readonly name = input<string>();
  /** The value submitted under `name` when checked. */
  readonly value = input<string>();
  /** Toggled; carries the new checked state. */
  readonly change = output<boolean>();

  protected readonly glyph = CHECK_GLYPH_STYLE;
  protected readonly glyphStroke = CHECK_STROKE_STYLE;

  protected readonly styles = computed(() => checkboxStyles({
    checked: this.checked(), disabled: this.disabled(),
  }));

  protected onChange(event: Event): void {
    event.stopPropagation();
    this.change.emit((event.target as HTMLInputElement).checked);
  }
}
