// frameworks/angular/components/display/badge/Badge.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input } from '@angular/core';
import type { Tone } from '../../../Api.generated';
import { badgeStyles } from './Badge.variants';

@Component({
  selector: 'arena-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    @if (dot()) {
      <span [class]="styles().dot()"></span>
    }
    <ng-content />
  `,
})
export class Badge {
  /** System status (success/warning/danger/info) reflects an object's actual state; emphasis (accent, gold) is editorial; neutral carries no semantic weight. */
  readonly tone = input<Tone>('neutral');
  /** Draws a filled dot in the tone colour before the label. */
  readonly dot = input(false, { transform: booleanAttribute });

  protected readonly styles = computed(() => badgeStyles({ tone: this.tone() }));
}

// frameworks/react/components/display/badge/Badge.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './Badge.manifest.generated.ts';

import type { Tone } from '../../../Api.generated';

export interface BadgeProps {

  /** The label text. Short: a badge is a chip, not a sentence. */
  children?: React.ReactNode;
  /** System status (success/warning/danger/info) reflects an object's actual state; emphasis (accent, gold) is editorial; neutral carries no semantic weight. */
  tone?: Tone;

  /** Draws a filled dot in the tone colour before the label. */
  dot?: boolean;
}

const badgeStyles = tv(manifest);
const TONES = Object.keys(manifest.variants.tone);
const toneOf = (tone: string | undefined): Tone | undefined =>
  (tone && TONES.includes(tone) ? tone as Tone : 'neutral');

export function Badge({ children, tone = 'neutral', dot = false }: BadgeProps) {
  const styles = badgeStyles({ tone: toneOf(tone) });
  return (
    <span className={styles.root()}>
      {dot && <span className={styles.dot()} />}
      {children}
    </span>
  );
}
