// frameworks/react/components/display/arena-skeleton/ArenaSkeleton.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaSkeleton.classes.generated.ts';

import type { ArenaSkeletonVariant } from '../../../Api.generated';

export interface ArenaSkeletonProps {
  /** The shape the placeholder reserves. */
  variant?: ArenaSkeletonVariant;

  /** CSS width, e.g. "100%" or "12rem". Defaults to full width. */
  width?: string;

  /** CSS height. Defaults per variant. For the `circle` variant a single diameter is what is wanted, so `height` wins over `width` when both are set. */
  height?: string;

  /** Number of rows when variant="text". The last runs short. */
  lines?: number;

  /** CSS border radius. Defaults to a small token radius. */
  radius?: string;
}


const arenaSkeletonStyles = arenaStyles(manifest);

export function ArenaSkeleton({ variant = 'block', width, height, lines = 3, radius }: ArenaSkeletonProps) {
  const styles = arenaSkeletonStyles({ variant });
  if (variant === 'text' && lines > 1) {
    return (
      <div role="status" aria-label="Loading" className={styles.stack()} style={{ width }}>
        {Array.from({ length: lines }).map((_, i) => (
          <div key={i} className={i === lines - 1 ? styles.lastLine() : styles.line()} />
        ))}
      </div>
    );
  }
  const box = variant === 'circle' ? (height || width) : undefined;
  return (
    <div className={styles.root()} role="status" aria-label="Loading"
      style={{ width: box ?? width, height: box ?? height, borderRadius: radius }} />
  );
}

// frameworks/angular/components/display/arena-skeleton/ArenaSkeleton.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { arenaSkeletonStyles } from './ArenaSkeleton.variants';
import type { ArenaSkeletonVariant } from '../../../Api.generated';

export function skeletonRowSlot(row: number, total: number): 'line' | 'lastLine' {
  return row === total && total > 1 ? 'lastLine' : 'line';
}

@Component({
  selector: 'arena-skeleton',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass()',
    '[style.width]': 'hostWidth()',
    '[style.height]': 'hostHeight()',
    '[style.borderRadius]': 'hostRadius()',
    role: 'status',
    'aria-label': 'Loading',
  },
  template: `
    @if (stacked()) {
      @for (row of rows(); track row) {
        <div [class]="rowSlot(row, rows().length) === 'lastLine' ? styles().lastLine() : styles().line()"></div>
      }
    }
  `,
})
export class ArenaSkeleton {
  /** The shape the placeholder reserves. */
  readonly variant = input<ArenaSkeletonVariant>('block');
  /** Number of rows when variant="text". The last runs short. */
  readonly lines = input(3);
  /** CSS width, e.g. "100%" or "12rem". Defaults to full width. */
  readonly width = input<string>();
  /** CSS height. Defaults per variant. For the `circle` variant a single diameter is what is wanted, so `height` wins over `width` when both are set. */
  readonly height = input<string>();
  /** CSS border radius. Defaults to a small token radius. */
  readonly radius = input<string>();

  protected readonly styles = computed(() => arenaSkeletonStyles({ variant: this.variant() }));
  protected readonly stacked = computed(() => this.variant() === 'text');
  protected readonly rows = computed(() => Array.from({ length: this.lines() }, (_, i) => i + 1));
  protected readonly hostClass = computed(() => (this.stacked() ? this.styles().stack() : this.styles().root()));
  protected readonly rowSlot = skeletonRowSlot;

  protected readonly diameter = computed<string | undefined>(() => this.height() || this.width());
  protected readonly hostWidth = computed<string | undefined>(() =>
    this.variant() === 'circle' ? this.diameter() : this.width());
  protected readonly hostHeight = computed<string | undefined>(() => {
    const v = this.variant();
    if (v === 'circle') return this.diameter();
    if (v === 'text') return undefined;
    return this.height();
  });
  protected readonly hostRadius = computed<string | undefined>(() =>
    this.variant() === 'block' ? this.radius() : undefined);
}
