// frameworks/angular/primitives/breadcrumbs/breadcrumbs.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import type { Crumb } from '../../api.generated';
import { breadcrumbsStyles } from './breadcrumbs.variants';

/** Explicit return path for hierarchies deeper than tabs. The last crumb is
 *  the current page -- not a link, and marked `aria-current="page"`. The
 *  host itself is the recipe's `root`, so it is both the flex item a parent
 *  row lays out and the trail's own `nav` landmark (`role="navigation"`,
 *  `aria-label="Breadcrumb"`), with no wrapper element rendered inside it.
 *  A crumb click reports the clicked `Crumb` alone through `navigate`,
 *  matching React's `onNavigate(crumb)`; the native `MouseEvent` is not
 *  forwarded, so a listener cannot call `preventDefault()` on the anchor's
 *  own navigation. The anchor still navigates natively -- ctrl-click,
 *  middle-click and open-in-new-tab keep working for a consumer who wires
 *  nothing -- but intercepting a plain click to substitute SPA routing now
 *  belongs at the router (`routerLink`), not here. */
@Component({
  selector: 'arena-breadcrumbs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    role: 'navigation',
    'aria-label': 'Breadcrumb',
  },
  template: `
    @for (crumb of items(); track crumb.label; let last = $last) {
      @if (last) {
        <span [class]="styles().current()" aria-current="page">{{ crumb.label }}</span>
      } @else {
        <a [class]="styles().crumb()" [attr.href]="crumb.href ?? '#'" (click)="onCrumbClick(crumb)">{{ crumb.label }}</a>
        <span [class]="styles().separator()" aria-hidden="true">{{ separator() }}</span>
      }
    }
  `,
})
export class Breadcrumbs {
  readonly items = input.required<Crumb[]>();
  readonly separator = input('/');
  readonly navigate = output<Crumb>();

  protected readonly styles = computed(() => breadcrumbsStyles());

  protected onCrumbClick(crumb: Crumb): void {
    this.navigate.emit(crumb);
  }
}

// frameworks/react/components/navigation/breadcrumbs/Breadcrumbs.tsx
import React from 'react';

import type { Crumb } from '../../../Api.generated';

export type { Crumb };
export interface BreadcrumbsProps {

  /** Names this navigation landmark. Required, and guarded at runtime: nothing can derive it, and the constant "Breadcrumb" it used to hardcode made two trails on one page indistinguishable as landmarks while satisfying the requirement mechanically. Say which hierarchy this is a trail through: "Project navigation", never "Breadcrumb". */
  ariaLabel: string;

  /** The trail, root first. The last entry is the current location and is never a link. */
  items: Crumb[];

  /** Drawn between crumbs, never before the first. Arena draws it, in its own aria-hidden span. */
  separator?: string;

  /** A non-current crumb was activated, carrying that crumb alone. The native MouseEvent is not forwarded, so a listener cannot call preventDefault() on the anchor's own navigation -- ctrl-click, middle-click and open-in-new-tab still work for a consumer who wires nothing; intercepting a plain click to substitute SPA routing belongs at the router (routerLink, Link), not here. */
  onNavigate?: (crumb: Crumb) => void;
}


export function Breadcrumbs({ items, ariaLabel, separator = '/', onNavigate }: BreadcrumbsProps) {
  if (!ariaLabel?.trim()) throw new Error('Breadcrumbs: `ariaLabel` is required');
  if (!items) throw new Error('Breadcrumbs: `items` is required');
  return (
    <nav aria-label={ariaLabel} style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 'calc(var(--sp-1) * 2)' }}>
      {items.map((it, i) => {
        const last = i === items.length - 1;
        const common = { fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)', letterSpacing: 'var(--ls-mono-nav)' };
        return (
          <React.Fragment key={i}>
            {last ? (
              <span aria-current="page" style={{ ...common, color: 'var(--bone)', fontWeight: 'var(--fw-bold)' }}>{it.label}</span>
            ) : (
              <a href={it.href || '#'} onClick={() => onNavigate?.(it)}
                style={{ ...common, color: 'var(--mute)', textDecoration: 'none', cursor: 'pointer', transition: 'color var(--dur-fast) var(--ease-out)' }}
                onMouseEnter={(e) => (e.currentTarget.style.color = 'var(--bone-dim)')}
                onMouseLeave={(e) => (e.currentTarget.style.color = 'var(--mute)')}>
                {it.label}
              </a>
            )}
            {!last && <span aria-hidden="true" style={{ color: 'var(--line-strong)', fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-sm)' }}>{separator}</span>}
          </React.Fragment>
        );
      })}
    </nav>
  );
}
