// frameworks/react/components/navigation/command-palette/CommandPalette.jsx
import React, { useState, useEffect, useRef } from 'react';
import { trapTabKey } from '../../../UseDialogModal.js';

let nextId = 0;

export function CommandPalette({ open, commands, placeholder = 'Search for an action or project…', onClose, onRun }) {
  if (open == null) throw new Error('CommandPalette: `open` is required');
  if (commands == null) throw new Error('CommandPalette: `commands` is required');
  const [q, setQ] = useState('');
  const [i, setI] = useState(0);
  const inputRef = useRef(null);
  const panelRef = useRef(null);
  const uid = useRef(null);
  if (uid.current === null) uid.current = `arena-command-palette-${nextId++}`;
  const listboxId = `${uid.current}-listbox`;
  const optionId = (index) => `${uid.current}-option-${index}`;
  const filtered = commands.filter((c) => (c.label + ' ' + (c.hint || '')).toLowerCase().includes(q.toLowerCase()));
  useEffect(() => { if (open) { setQ(''); setI(0); setTimeout(() => inputRef.current && inputRef.current.focus(), 0); } }, [open]);
  useEffect(() => { setI(0); }, [q]);
  if (!open) return null;
  const run = (c) => { onClose && onClose(); c && onRun && onRun(c); };
  const onKey = (e) => {
    if (e.key === 'ArrowDown') { e.preventDefault(); setI((v) => Math.min(v + 1, filtered.length - 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setI((v) => Math.max(v - 1, 0)); }
    else if (e.key === 'Enter') { e.preventDefault(); run(filtered[i]); }
    else if (e.key === 'Escape') { e.preventDefault(); onClose && onClose(); }
  };
  const onPanelKeyDown = (e) => {
    if (e.key === 'Tab' && panelRef.current) trapTabKey(panelRef.current, e, document.activeElement);
  };
  return (
    <div onClick={onClose} style={{ position: 'fixed', inset: 0, zIndex: 'var(--z-palette)', display: 'flex', alignItems: 'flex-start', justifyContent: 'center',
      paddingTop: '12vh', background: 'var(--scrim)', backdropFilter: 'blur(var(--scrim-blur))', WebkitBackdropFilter: 'blur(var(--scrim-blur))' }}>
      <div ref={panelRef} onKeyDown={onPanelKeyDown}
        onClick={(e) => e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Command palette"
        style={{ width: 'calc(var(--sp-1) * 140)', maxWidth: '92vw', background: 'var(--surface-card)', border: 'var(--bw) solid var(--line-strong)', borderRadius: 'var(--r-lg)', boxShadow: 'var(--shadow-3)', overflow: 'hidden' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 2.5)', padding: 'calc(var(--sp-1) * 3.5) calc(var(--sp-1) * 4)', borderBottom: 'var(--bw) solid var(--color-base-300)' }}>
          <i className="ph-bold ph-magnifying-glass" aria-hidden="true" style={{ color: 'var(--mute)', fontSize: 'var(--icon-lg)' }} />
          <input ref={inputRef} value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={onKey} placeholder={placeholder}
            role="combobox" aria-autocomplete="list" aria-haspopup="listbox" aria-expanded="true"
            aria-controls={listboxId} aria-label={placeholder || 'Search commands'}
            aria-activedescendant={i >= 0 && i < filtered.length ? optionId(i) : undefined}
            style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: 'var(--bone)', fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text)' }} />
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)', color: 'var(--mute)', border: 'var(--bw) solid var(--color-base-300)', borderRadius: 'var(--r-xs)', padding: 'calc(var(--sp-1) * 0.5) calc(var(--sp-1) * 1.5)' }}>ESC</span>
        </div>
        <div id={listboxId} role="listbox" aria-label="Commands"
          style={{ maxHeight: 'calc(var(--sp-1) * 80)', overflow: 'auto', padding: 'calc(var(--sp-1) * 1.5)' }}>
          {filtered.length === 0 && <div style={{ padding: 'calc(var(--sp-1) * 4.5) calc(var(--sp-1) * 3)', fontFamily: 'var(--font-body)', fontSize: 'var(--fs-md)', color: 'var(--mute)' }}>No results for "{q}".</div>}
          {filtered.map((c, idx) => (
            <button key={c.id} id={optionId(idx)} role="option" aria-selected={idx === i} tabIndex={-1}
              onMouseEnter={() => setI(idx)} onClick={() => run(c)}
              style={{ display: 'flex', alignItems: 'center', gap: 'calc(var(--sp-1) * 3)', width: '100%', textAlign: 'left', padding: 'calc(var(--sp-1) * 2.5) calc(var(--sp-1) * 3)', borderRadius: 'var(--r-sm)', border: 'none', cursor: 'pointer',
                background: idx === i ? 'var(--crimson-soft)' : 'transparent', color: idx === i ? 'var(--crimson)' : 'var(--bone-dim)' }}>
              {c.icon && <span style={{ fontSize: 'var(--icon-lg)', display: 'inline-flex' }}><i className={c.icon} aria-hidden="true" /></span>}
              <span style={{ flex: 1, fontFamily: 'var(--font-body)', fontSize: 'var(--dz-text)', fontWeight: idx === i ? 'var(--fw-semibold)' : 'var(--fw-medium)' }}>{c.label}</span>
              {c.shortcut && <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-xs)', color: 'var(--mute)' }}>{c.shortcut}</span>}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// frameworks/angular/components/navigation/command-palette/CommandPalette.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  ElementRef,
  afterRenderEffect,
  booleanAttribute,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import { commandPaletteStyles } from './CommandPalette.variants';
import { type FocusTrapState, handleOpenTransition, trapTabKey } from '../../../FocusTrap';
import type { Command } from '../../../Api.generated';

let nextId = 0;

export function filterCommands(commands: readonly Command[], query: string): Command[] {
  const needle = query.toLowerCase();
  return commands.filter((command) => `${command.label} ${command.hint ?? ''}`.toLowerCase().includes(needle));
}

export function nextActiveIndex(current: number, key: 'ArrowDown' | 'ArrowUp', count: number): number {
  if (count === 0) return 0;
  const last = count - 1;
  return key === 'ArrowDown' ? Math.min(current + 1, last) : Math.max(current - 1, 0);
}

export function scrollRowIntoView(list: HTMLElement, index: number): void {
  const row = list.children.item(index);
  if (row instanceof HTMLElement) row.scrollIntoView({ block: 'nearest' });
}

export function optionRowId(uid: string, index: number): string {
  return `${uid}-option-${index}`;
}

export function activeOptionId(uid: string, active: number, rowCount: number): string | undefined {
  return active >= 0 && active < rowCount ? optionRowId(uid, active) : undefined;
}

@Component({
  selector: 'arena-command-palette',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '(click)': 'onScrimClick()',
  },
  template: `
    @if (open()) {
      <div #panel [class]="styles().panel()" role="dialog" aria-modal="true" aria-label="Command palette"
           (click)="$event.stopPropagation()">
        <div [class]="styles().search()">
          <i [class]="styles().searchIcon() + ' ph-bold ph-magnifying-glass'" aria-hidden="true"></i>
          <input [class]="styles().input()" [value]="query()" [attr.placeholder]="placeholder()"
                 role="combobox" aria-autocomplete="list" aria-haspopup="listbox" aria-expanded="true"
                 [attr.aria-controls]="listboxId" [attr.aria-activedescendant]="activeId()"
                 [attr.aria-label]="placeholder() || 'Search commands'"
                 (input)="onQuery($event)" (keydown)="onKey($event)" />
          <span [class]="styles().esc()">ESC</span>
        </div>
        <div #list [class]="styles().list()" [id]="listboxId" role="listbox" aria-label="Commands">
          @for (command of filtered(); track command.id ?? command.label; let i = $index) {
            <button type="button" [id]="optionId(i)" role="option" [attr.aria-selected]="i === active()" tabindex="-1"
                    [class]="styles().row() + ' ' + (i === active() ? styles().rowActive() : styles().rowDefault())"
                    (mouseenter)="onHover(i)" (click)="onRun(command)">
              @if (command.icon; as glyph) {
                <span [class]="styles().rowIcon()"><i [class]="glyph" aria-hidden="true"></i></span>
              }
              <span [class]="styles().rowLabel() + ' ' + (i === active() ? styles().rowLabelActive() : styles().rowLabelDefault())">{{ command.label }}</span>
              @if (command.shortcut; as shortcut) {
                <span [class]="styles().shortcut()">{{ shortcut }}</span>
              }
            </button>
          }
        </div>
        @if (filtered().length === 0) {
          <div [class]="styles().empty()">No results for "{{ query() }}".</div>
        }
      </div>
    }
  `,
})
export class CommandPalette {
  readonly open = input.required<boolean, unknown>({ transform: booleanAttribute });
  readonly commands = input.required<Command[]>();
  readonly placeholder = input('Search for an action or project…');
  readonly close = output<void>();
  readonly run = output<Command>();

  protected readonly query = signal('');
  protected readonly active = signal(0);
  protected readonly styles = computed(() => commandPaletteStyles({ open: this.open() }));
  protected readonly filtered = computed(() => filterCommands(this.commands(), this.query()));

  private readonly doc = inject(DOCUMENT);
  private readonly uid = `arena-command-palette-${nextId++}`;
  protected readonly listboxId = `${this.uid}-listbox`;
  protected readonly activeId = computed(() => activeOptionId(this.uid, this.active(), this.filtered().length));

  private readonly list = viewChild<ElementRef<HTMLElement>>('list');
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  private readonly focusTrap: FocusTrapState = { wasOpen: false, restoreTo: null };

  constructor() {
    effect(() => {
      if (this.open()) {
        this.query.set('');
        this.active.set(0);
      }
    });
    afterRenderEffect(() => {
      const isOpen = this.open();
      untracked(() => {
        handleOpenTransition(this.focusTrap, isOpen, this.panel()?.nativeElement ?? null, this.doc.activeElement);
      });
    });
    afterRenderEffect(() => {
      const index = this.active();
      const hasRows = this.filtered().length > 0;
      untracked(() => {
        const list = this.list()?.nativeElement;
        if (list && hasRows) scrollRowIntoView(list, index);
      });
    });
  }

  protected optionId(index: number): string {
    return optionRowId(this.uid, index);
  }

  protected onQuery(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
    this.active.set(0);
  }

  protected onHover(index: number): void {
    this.active.set(index);
  }

  protected onKey(event: KeyboardEvent): void {
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault();
      this.active.update((current) => nextActiveIndex(current, event.key as 'ArrowDown' | 'ArrowUp', this.filtered().length));
    } else if (event.key === 'Enter') {
      event.preventDefault();
      const command = this.filtered()[this.active()];
      if (command) this.onRun(command);
    } else if (event.key === 'Escape') {
      event.preventDefault();
      this.close.emit();
    } else if (event.key === 'Tab') {
      const panel = this.panel()?.nativeElement;
      if (panel) trapTabKey(panel, event, this.doc.activeElement);
    }
  }

  protected onRun(command: Command): void {
    this.close.emit();
    this.run.emit(command);
  }

  protected onScrimClick(): void {
    if (this.open()) this.close.emit();
  }
}
