// frameworks/react/components/feedback/arena-error-state/ArenaErrorState.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaErrorState.classes.generated.ts';
import { ArenaButton } from '../../forms/arena-button/ArenaButton.tsx';

export interface ArenaErrorStateProps {
  /** A Phosphor class name for the danger glyph Arena draws. */
  icon?: string;
  /** The headline: what failed. */
  title?: string;
  /** A sentence of detail under the title. */
  message?: string;
  /** A diagnostic/support code, shown monospaced. */
  code?: string;
  /** The label of the retry button Arena draws. Absent renders no retry. */
  retryLabel?: string;
  /** The retry button was activated. */
  onRetry?: () => void;
  /** An extra control beside the retry (e.g. a link to logs). */
  secondaryAction?: React.ReactNode;
}


const errorStyles = arenaStyles(manifest);

export function ArenaErrorState({ icon, title = 'Something went wrong', message, code, retryLabel, onRetry, secondaryAction }: ArenaErrorStateProps) {
  const styles = errorStyles();
  return (
    <div role="alert" className={styles.root()}>
      {icon && <div className={styles.icon()}><i className={icon} aria-hidden="true" /></div>}
      <div className={styles.title()}>{title}</div>
      {message && <div className={styles.message()}>{message}</div>}
      {code && <code className={styles.code()}>{code}</code>}
      <div className={styles.actions()}>
        {retryLabel && <ArenaButton variant="primary" onClick={onRetry}>{retryLabel}</ArenaButton>}
        {secondaryAction}
      </div>
    </div>
  );
}

// frameworks/angular/components/feedback/arena-error-state/ArenaErrorState.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input, output } from '@angular/core';
import { ArenaSecondaryAction } from '../../../ProjectionMarkers';
import { arenaErrorStateStyles } from './ArenaErrorState.variants';

@Component({
  selector: 'arena-error-state',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    role: 'alert',
    '[attr.title]': 'null',
  },
  template: `
    @if (icon(); as glyph) {
      <div [class]="styles().icon()"><i [class]="glyph" aria-hidden="true"></i></div>
    }
    <div [class]="styles().title()">{{ title() }}</div>
    @if (message(); as body) {
      <div [class]="styles().message()">{{ body }}</div>
    }
    @if (code(); as support) {
      <code [class]="styles().code()">{{ support }}</code>
    }
    @if (retryLabel() || secondaryAction()) {
      <div [class]="styles().actions()">
        @if (retryLabel(); as label) {
          <button type="button" [class]="styles().retry()" (click)="retry.emit()">{{ label }}</button>
        }
        <ng-content select="[secondaryAction]" />
      </div>
    }
  `,
})
export class ArenaErrorState {
  /** A Phosphor class name for the danger glyph Arena draws. */
  readonly icon = input<string>();
  /** The headline: what failed. */
  readonly title = input('Something went wrong');
  /** A sentence of detail under the title. */
  readonly message = input<string>();
  /** A diagnostic/support code, shown monospaced. */
  readonly code = input<string>();
  /** The label of the retry button Arena draws. Absent renders no retry. */
  readonly retryLabel = input<string>();
  /** The retry button was activated. */
  readonly retry = output<void>();

  protected readonly secondaryAction = contentChild(ArenaSecondaryAction);

  protected readonly styles = computed(() => arenaErrorStateStyles());
}
