// frameworks/angular/components/feedback/arena-alert/ArenaAlert.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, computed, input, output } from '@angular/core';
import { arenaAlertStyles } from './ArenaAlert.variants';
import type { ArenaAlertTone } from '../../../Api.generated';

const TONE_ICONS: Record<ArenaAlertTone, string> = {
  info: 'ph-fill ph-info',
  success: 'ph-fill ph-check-circle',
  warning: 'ph-fill ph-warning',
  danger: 'ph-fill ph-warning-octagon',
  neutral: 'ph-fill ph-note',
};

@Component({
  selector: 'arena-alert',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.role]': "tone() === 'danger' ? 'alert' : 'status'",
    '[attr.title]': 'null',
  },
  template: `
    <i [class]="styles().icon() + ' ' + (icon() ?? toneIcon())" aria-hidden="true"></i>
    <div [class]="styles().body()">
      @if (title(); as heading) {
        <div [class]="styles().title()">{{ heading }}</div>
      }
      <div [class]="styles().message()"><ng-content /></div>
      @if (actionLabel(); as label) {
        <button type="button" [class]="styles().action()" (click)="action.emit()">{{ label }}</button>
      }
    </div>
    @if (dismissible()) {
      <button type="button" [class]="styles().close()" aria-label="Dismiss" (click)="close.emit()">
        <i class="ph-bold ph-x" aria-hidden="true"></i>
      </button>
    }
  `,
})
export class ArenaAlert {
  /** The severity: colour, default icon, and (for danger) the alert role. */
  readonly tone = input<ArenaAlertTone>('info');
  /** An optional bold lead line above the message. */
  readonly title = input<string>();
  /** A Phosphor class name overriding the tone's default glyph. Arena draws it. */
  readonly icon = input<string>();
  /** The label of a single inline action button. Absent renders no action. */
  readonly actionLabel = input<string>();
  /** Whether the × is shown. Every layer gates the × on this member and never on whether anything listens for `close`, because Arena never derives what it draws from what a consumer listens for. */
  readonly dismissible = input(false, { transform: booleanAttribute });
  /** The inline action button was activated. */
  readonly action = output<void>();
  /** The × was activated. */
  readonly close = output<void>();

  protected readonly styles = computed(() => arenaAlertStyles({ tone: this.tone(), titled: !!this.title() }));
  protected readonly toneIcon = computed(() => TONE_ICONS[this.tone()]);
}

// frameworks/react/components/feedback/arena-alert/ArenaAlert.tsx
import React from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaAlert.classes.generated.ts';

import type { ArenaAlertTone } from '../../../Api.generated';

export interface ArenaAlertProps {
  /** The severity: colour, default icon, and (for danger) the alert role. */
  tone?: ArenaAlertTone;
  /** An optional bold lead line above the message. */
  title?: string;
  /** The message body. */
  children?: React.ReactNode;
  /** A Phosphor class name overriding the tone's default glyph. Arena draws it. */
  icon?: string;
  /** The label of a single inline action button. Absent renders no action. */
  actionLabel?: string;
  /** The inline action button was activated. */
  onAction?: () => void;
  /** Whether the × is shown. Every layer gates the × on this member and never on whether anything listens for `close`, because Arena never derives what it draws from what a consumer listens for. */
  dismissible?: boolean;
  /** The × was activated. */
  onClose?: () => void;
}

const arenaAlertStyles = arenaStyles(manifest);
const TONES = Object.keys(manifest.variants.tone);
const GLYPHS: Record<string, string> = {
  info: 'ph-fill ph-info',
  success: 'ph-fill ph-check-circle',
  warning: 'ph-fill ph-warning',
  danger: 'ph-fill ph-warning-octagon',
  neutral: 'ph-fill ph-note',
};
type ArenaTone = keyof typeof manifest.variants.tone;
const toneOf = (tone: string | undefined): ArenaTone =>
  (tone && TONES.includes(tone) ? tone as ArenaTone : 'info');

export function ArenaAlert({ tone = 'info', title, children, icon, actionLabel, onAction, dismissible, onClose }: ArenaAlertProps) {
  const at = toneOf(tone);
  const styles = arenaAlertStyles({ tone: at, titled: Boolean(title) });
  return (
    <div role={tone === 'danger' ? 'alert' : 'status'} className={styles.root()}>
      <i className={`${icon || GLYPHS[at]} ${styles.icon()}`} />
      <div className={styles.body()}>
        {title && <div className={styles.title()}>{title}</div>}
        {children && <div className={styles.message()}>{children}</div>}
        {actionLabel && (
          <button onClick={onAction} className={styles.action()}>{actionLabel}</button>
        )}
      </div>
      {dismissible && (
        <button onClick={onClose} aria-label="Dismiss" className={styles.close()}>
          <i className="ph-bold ph-x" />
        </button>
      )}
    </div>
  );
}
