// components/display/Avatar.jsx
import React from 'react';
const SIZES = { xs: 24, sm: 32, md: 40, lg: 56 };
const STATUS = { online: 'var(--success)', busy: 'var(--danger)', away: 'var(--warning)', offline: 'var(--mute-2-disabled)' };
/** Representation of a person or entity. `src` for image; without it, initials on panel.
 * `shape` circle (people) or rounded (teams/orgs). `status` adds a presence dot. */
export function Avatar({ src, name = '', size = 'md', shape = 'circle', status, style, ...rest }) {
  const d = SIZES[size] || SIZES.md;
  const radius = shape === 'rounded' ? 'var(--r-md)' : '50%';
  const initials = name.trim().split(/\s+/).slice(0, 2).map((w) => w[0] || '').join('').toUpperCase();
  return (
    <span style={{ position: 'relative', display: 'inline-flex', width: d, height: d, flexShrink: 0, ...style }} {...rest}>
      <span style={{ width: d, height: d, borderRadius: radius, overflow: 'hidden', display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        background: 'var(--panel-2)', border: '1px solid var(--line-strong)',
        fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: d * 0.4, color: 'var(--bone-dim)', letterSpacing: '.02em' }}>
        {src ? <img src={src} alt={name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : initials}
      </span>
      {status && (
        <span aria-label={status} title={status}
          style={{ position: 'absolute', right: -1, bottom: -1, width: Math.max(8, d * 0.28), height: Math.max(8, d * 0.28),
            borderRadius: '50%', background: STATUS[status] || STATUS.offline, border: '2px solid var(--surface-card)' }} />
      )}
    </span>
  );
}

// frameworks/angular/primitives/avatar/avatar.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { avatarStyles } from './avatar.variants';

type Size = 'xs' | 'sm' | 'md' | 'lg';
type Shape = 'circle' | 'rounded';
type Status = 'online' | 'busy' | 'away' | 'offline';

/** Person or entity mark — the image when `src` is set, initials from `name` otherwise. */
@Component({
  selector: 'arena-avatar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [class]="styles().root()">
      <span [class]="styles().box()">
        @if (src(); as source) {
          <img [src]="source" [alt]="name()" [class]="styles().image()" />
        } @else {
          {{ initials() }}
        }
      </span>
      @if (status(); as presence) {
        <span [class]="styles().status()" [attr.aria-label]="presence" [title]="presence"></span>
      }
    </span>
  `,
})
export class Avatar {
  readonly src = input<string>();
  readonly name = input('');
  readonly size = input<Size>('md');
  readonly shape = input<Shape>('circle');
  readonly status = input<Status>();

  protected readonly styles = computed(() =>
    avatarStyles({ size: this.size(), shape: this.shape(), status: this.status() ?? 'none' }));

  protected readonly initials = computed(() =>
    this.name().trim().split(/\s+/).slice(0, 2).map((word) => word[0] ?? '').join('').toUpperCase());
}
