// frameworks/react/components/forms/arena-textarea/ArenaTextarea.tsx
import React, { useEffect, useRef } from 'react';
import { arenaStyles } from '../../../ArenaStyles.generated.ts';
import manifest from './ArenaTextarea.classes.generated.ts';

export interface ArenaTextareaProps {

  /** Field label; the counter and error sit under the field. */
  label?: string;

  /** The control's id, and what the label's `for` points at. Generated from `label` when omitted, as `ta-` followed by the label with each run of whitespace replaced by a single hyphen and the whole lowercased: the derivation ArenaInput.id states, under this component's own prefix. */
  id?: string;

  /** A line of help under the field. */
  hint?: string;

  /** Error message; turns the border crimson and shows below. */
  error?: string;

  /** Marks the label and the control required. */
  required?: boolean;

  /** Shows a live length/maxLength count, which warns once the length is STRICTLY past nine tenths of `maxLength`; exactly at the share is not yet near the limit. */
  counter?: boolean;

  /** Grows with the content instead of scrolling. */
  autoResize?: boolean;

  /** The controlled text. */
  value?: string;

  /** Blocks editing and dims it. */
  disabled?: boolean;

  /** Shows the value but blocks editing. */
  readOnly?: boolean;

  /** Shown when empty. */
  placeholder?: string;

  /** Submitted with the form. */
  name?: string;

  /** Caps the length; feeds the counter. */
  maxLength?: number;

  /** Initial visible rows. */
  rows?: number;

  /** Edited; carries the new text. */
  onChange?: (value: string) => void;
}


export function arenaBorderBoxSlack(element: HTMLElement): number {
  return element.offsetHeight - element.clientHeight;
}

export function arenaFitToContent(element: HTMLElement | null): void {
  if (!element) return;
  element.style.height = 'auto';
  element.style.height = `${element.scrollHeight + arenaBorderBoxSlack(element)}px`;
}

const arenaTextareaStyles = arenaStyles(manifest);

export function ArenaTextarea({
  label, id, hint, error, required = false, rows = 4, maxLength, counter = false,
  disabled = false, readOnly = false, autoResize = false, placeholder, name, value, onChange,
}: ArenaTextareaProps) {
  const boxRef = useRef<HTMLTextAreaElement | null>(null);
  const taId = id || (label ? 'ta-' + label.replace(/\s+/g, '-').toLowerCase() : undefined);
  const len = typeof value === 'string' ? value.length : 0;
  const styles = arenaTextareaStyles({
    state: error ? 'error' : 'neutral',
    resize: autoResize ? 'none' : 'vertical',
    disabled,
    readonly: readOnly,
  });
  useEffect(() => {
    if (autoResize) arenaFitToContent(boxRef.current);
  }, [autoResize, value, rows]);
  return (
    <div className={styles.root()}>
      {label && (
        <label htmlFor={taId} className={styles.label()}>
          {label}{required && <span className={styles.required()}>*</span>}
        </label>
      )}
      <textarea ref={boxRef} id={taId} rows={rows} maxLength={maxLength} disabled={disabled} required={required}
        readOnly={readOnly} placeholder={placeholder} name={name}
        aria-invalid={!!error} value={value}
        onChange={(e) => { if (autoResize) arenaFitToContent(e.target); onChange && onChange(e.target.value); }}
        className={styles.field()} />
      <div className={styles.foot()}>
        {error ? <span className={styles.error()}>{error}</span>
          : hint ? <span className={styles.hint()}>{hint}</span> : <span />}
        {counter && maxLength && (
          <span className={len > maxLength * 0.9 ? styles.counterNear() : styles.counter()}>{len}/{maxLength}</span>
        )}
      </div>
    </div>
  );
}

// frameworks/angular/components/forms/arena-textarea/ArenaTextarea.ts
import {
  ChangeDetectionStrategy, Component, ElementRef, afterRenderEffect, booleanAttribute, computed,
  input, output, viewChild,
} from '@angular/core';
import { arenaTextareaStyles } from './ArenaTextarea.variants';

export const ARENA_COUNTER_WARNING_SHARE = 0.9;

export function arenaTextareaIdFor(id: string | undefined, label: string | undefined): string | null {
  if (id) return id;
  return label ? `ta-${label.replace(/\s+/g, '-').toLowerCase()}` : null;
}

export function arenaCounterIsNear(length: number, maxLength: number): boolean {
  return length > maxLength * ARENA_COUNTER_WARNING_SHARE;
}

export function arenaBorderBoxSlack(element: HTMLElement): number {
  return element.offsetHeight - element.clientHeight;
}

@Component({
  selector: 'arena-textarea',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.name]': 'null',
    '[attr.id]': 'null',
  },
  template: `
    @if (label(); as text) {
      <label [class]="styles().label()" [attr.for]="controlId()">{{ text }}@if (required()) {
        <span [class]="styles().required()">*</span>
      }</label>
    }
    <textarea #control [class]="styles().field()" [attr.id]="controlId()" [attr.rows]="rows()"
              [attr.maxlength]="maxLength()" [disabled]="disabled()" [required]="required()"
              [readOnly]="readOnly()" [attr.placeholder]="placeholder()" [attr.name]="name()"
              [attr.aria-invalid]="hasError()" [value]="value() ?? ''"
              (input)="onInput($event)" (change)="onNativeChange($event)"></textarea>
    <div [class]="styles().foot()">
      @if (shownError(); as message) {
        <span [class]="styles().error()">{{ message }}</span>
      } @else if (hint(); as text) {
        <span [class]="styles().hint()">{{ text }}</span>
      } @else {
        <span></span>
      }
      @if (counterText(); as text) {
        <span [class]="counterClass()">{{ text }}</span>
      }
    </div>
  `,
})
export class ArenaTextarea {
  /** Field label; the counter and error sit under the field. */
  readonly label = input<string>();
  /** The control's id, and what the label's `for` points at. Generated from `label` when omitted, as `ta-` followed by the label with each run of whitespace replaced by a single hyphen and the whole lowercased: the derivation ArenaInput.id states, under this component's own prefix. */
  readonly id = input<string>();
  /** A line of help under the field. */
  readonly hint = input<string>();
  /** Error message; turns the border crimson and shows below. */
  readonly error = input<string>();
  /** Marks the label and the control required. */
  readonly required = input(false, { transform: booleanAttribute });
  /** Shows a live length/maxLength count, which warns once the length is STRICTLY past nine tenths of `maxLength`; exactly at the share is not yet near the limit. */
  readonly counter = input(false, { transform: booleanAttribute });
  /** Grows with the content instead of scrolling. */
  readonly autoResize = input(false, { transform: booleanAttribute });
  /** The controlled text. */
  readonly value = input<string>();
  /** Blocks editing and dims it. */
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Shows the value but blocks editing. */
  readonly readOnly = input(false, { transform: booleanAttribute });
  /** Shown when empty. */
  readonly placeholder = input<string>();
  /** Submitted with the form. */
  readonly name = input<string>();
  /** Caps the length; feeds the counter. */
  readonly maxLength = input<number>();
  /** Initial visible rows. */
  readonly rows = input(4);
  /** Edited; carries the new text. */
  readonly change = output<string>();

  protected readonly controlId = computed(() => arenaTextareaIdFor(this.id(), this.label()));
  protected readonly shownError = computed(() => this.error() ?? null);
  protected readonly hasError = computed(() => Boolean(this.shownError()));

  protected readonly styles = computed(() => arenaTextareaStyles({
    state: this.hasError() ? 'error' : 'neutral',
    resize: this.autoResize() ? 'none' : 'vertical',
    disabled: this.disabled(),
    readonly: this.readOnly(),
  }));

  protected readonly length = computed(() => (this.value() ?? '').length);

  protected readonly counterText = computed(() => {
    const cap = this.maxLength();
    if (!this.counter() || cap === undefined) return null;
    return `${this.length()}/${cap}`;
  });

  protected readonly counterClass = computed(() => {
    const cap = this.maxLength();
    return cap !== undefined && arenaCounterIsNear(this.length(), cap)
      ? this.styles().counterNear()
      : this.styles().counter();
  });

  private readonly control = viewChild<ElementRef<HTMLTextAreaElement>>('control');

  constructor() {
    afterRenderEffect(() => {
      this.value();
      if (this.autoResize()) this.grow();
    });
  }

  protected onInput(event: Event): void {
    const target = event.target as HTMLTextAreaElement;
    if (this.autoResize()) this.fit(target);
    this.change.emit(target.value);
  }

  protected onNativeChange(event: Event): void {
    event.stopPropagation();
  }

  private grow(): void {
    const element = this.control()?.nativeElement;
    if (element) this.fit(element);
  }

  private fit(element: HTMLTextAreaElement): void {
    element.style.height = 'auto';
    element.style.height = `${element.scrollHeight + arenaBorderBoxSlack(element)}px`;
  }
}
