// frameworks/angular/primitives/chart-card/chart-card.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { ArenaActions } from '../projection-markers';
import { chartCardStyles } from './chart-card.variants';

/** The card a chart sits on. `title` is an uppercase muted microlabel,
 *  deliberately not a heading element: a dashboard is a grid of tiles, and
 *  one `h2` per tile would fabricate a document outline nobody asked for —
 *  the chart inside carries the accessible name through its own
 *  `role="img"`. The host is the recipe's `root`, the flex item a parent
 *  lays out. The head row — the title plus the projected `[arena-actions]`
 *  — renders only when at least one of them is actually present, mirroring
 *  React's own `{(title || actions) && (...)}` gate: with neither, an empty
 *  flex row would still consume the root's `gap-3` between it and the
 *  chart. */
@Component({
  selector: 'arena-chart-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'styles().root()' },
  template: `
    @if (title() || actions()) {
      <div [class]="styles().head()">
        @if (title(); as label) {
          <span [class]="styles().title()">{{ label }}</span>
        }
        @if (actions()) {
          <div [class]="styles().actions()"><ng-content select="[arena-actions]" /></div>
        }
      </div>
    }
    <ng-content />
  `,
})
export class ChartCard {
  readonly title = input<string>();

  protected readonly actions = contentChild(ArenaActions);

  protected readonly styles = computed(() => chartCardStyles());
}

// frameworks/react/components/charts/ChartCard.jsx
import React from 'react';

/* The card a chart sits on. `title` is an uppercase muted microlabel, NOT a
 * heading element: a dashboard is a grid of tiles, and emitting an h2 per tile
 * would fabricate a document outline nobody asked for. The chart's own
 * role="img" carries the accessible name. */
export function ChartCard({ title, actions, children, style, ...rest }) {
  return (
    <div style={{
      background: 'var(--surface-card)', border: '1px solid var(--color-base-300)',
      borderRadius: 'var(--r-lg)', padding: 20,
      display: 'flex', flexDirection: 'column', gap: 12, ...style,
    }} {...rest}>
      {(title || actions) && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
          {title && <span style={{
            fontFamily: 'var(--font-mono)', fontSize: 'var(--dz-text-2xs)', letterSpacing: 'var(--ls-label)',
            textTransform: 'uppercase', color: 'var(--mute)',
          }}>{title}</span>}
          {actions && <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{actions}</div>}
        </div>
      )}
      {children}
    </div>
  );
}
