// frameworks/react/components/navigation/page-head/PageHead.tsx
import React from 'react';
import { tv } from '../../../Tv.generated.ts';
import manifest from './PageHead.manifest.generated.ts';
import { useContainerWidth, readBreakpoint } from '../../../UseContainerWidth.ts';

import type { PageHeadAlign } from '../../../Api.generated';

export interface PageHeadProps {

  /** The page title. Required: a page head with no title is a bug, not a state. */
  title: string;

  /** A muted line under the title. */
  subtitle?: string;

  /** Page-level controls, right-aligned in the head. */
  actions?: React.ReactNode;

  /** Cross-axis alignment of the actions block against the title, wide layout only. */
  align?: PageHeadAlign;
}


const pageHeadStyles = tv(manifest);

export function PageHead({ title, subtitle, actions, align = 'start' }: PageHeadProps) {
  if (!title) throw new Error('PageHead: `title` is required');
  const [ref, width] = useContainerWidth();
  const narrow = width !== null && width < readBreakpoint('sm');
  const styles = pageHeadStyles({ narrow, align });

  return (
    <div ref={ref} className={styles.root()}>
      <div className={styles.titles()}>
        <h1 className={styles.title()}>{title}</h1>
        {subtitle && <p className={styles.subtitle()}>{subtitle}</p>}
      </div>
      {actions && <div className={styles.actions()}>{actions}</div>}
    </div>
  );
}

// frameworks/angular/components/navigation/page-head/PageHead.ts
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core';
import { containerWidth, readBreakpoint } from '../../../ContainerSize';
import { ArenaActions } from '../../../ProjectionMarkers';
import { pageHeadStyles } from './PageHead.variants';
import type { PageHeadAlign } from '../../../Api.generated';

@Component({
  selector: 'arena-page-head',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'styles().root()',
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="styles().titles()">
      <h1 [class]="styles().title()">{{ title() }}</h1>
      @if (subtitle(); as caption) {
        <p [class]="styles().subtitle()">{{ caption }}</p>
      }
    </div>
    @if (actions()) {
      <div [class]="styles().actions()"><ng-content select="[actions]" /></div>
    }
  `,
})
export class PageHead {
  /** The page title. Required — a page head with no title is a bug, not a state. */
  readonly title = input.required<string>();
  /** A muted line under the title. */
  readonly subtitle = input<string>();
  /** Cross-axis alignment of the actions block against the title, wide layout only. */
  readonly align = input<PageHeadAlign>('start');

  protected readonly actions = contentChild(ArenaActions);

  private readonly width = containerWidth();
  private readonly small = readBreakpoint('sm');

  protected readonly styles = computed(() => {
    const measured = this.width();
    return pageHeadStyles({ narrow: measured !== null && measured < this.small, align: this.align() });
  });
}
