// frameworks/react/components/display/table-cell/TableCell.tsx
import React from 'react';
import type { TableColumn } from '../../../Api.generated';
import { tv } from '../../../Tv.generated.ts';
import manifest from '../table/Table.manifest.generated.ts';

const cellStyles = tv(manifest);

export interface TableCellProps {

  /** What the cell shows: a value, or one of Arena's own components, such as a Badge for a status or a Button for an action. This is what the compound shape exists for. The consumer instantiates one element per cell, so nothing here is per-item projection. */
  children?: React.ReactNode;
}

export interface TableCellInjected {
  column: TableColumn;
  layout: 'table' | 'card';
  tabIndex: number | undefined;
  focused: boolean;
  onCellFocus: (() => void) | undefined;
}



export function TableCell({
  children, column, layout = 'table', tabIndex, focused = false, onCellFocus,
}: TableCellProps & Partial<TableCellInjected>) {

  const c: Partial<TableColumn> = column ?? {};

  if (layout === 'card') {
    if (c.mobileLayout === 'block') {

      return (
        <div className={cellStyles({ narrow: true }).cardBlock()}>
          {children}
        </div>
      );
    }
    const card = cellStyles({ narrow: true });
    return (
      <div className={card.cardRow()}>
        <span className={card.cardLabel()}>{c.header}</span>
        <span className={c.mono ? card.cardValueMono() : card.cardValue()}>
          {children}
        </span>
      </div>
    );
  }

  return (
    <td role="gridcell" tabIndex={tabIndex}

      onFocus={onCellFocus ? (e) => { if (e.target === e.currentTarget) onCellFocus(); } : undefined}
      className={c.mono
        ? cellStyles({ narrow: false, align: c.align || 'left' }).tdMono()
        : cellStyles({ narrow: false, align: c.align || 'left' }).td()}
      style={{ boxShadow: focused ? 'inset 0 0 0 var(--focus-width) var(--focus-ring)' : undefined }}>
      {children}
    </td>
  );
}

// frameworks/angular/components/display/table-cell/TableCell.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import type { TableColumn } from '../../../Api.generated';
import { TableState } from '../table/TableState';
import { TableRowState } from '../table-row/TableRowState';
import { tableCellStyles } from './TableCell.variants';

const PLAIN: TableColumn = { header: '' };

@Component({
  selector: 'arena-table-cell',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'cellClass()',
    '[attr.role]': 'role()',
    '[attr.tabindex]': 'tabIndex()',
    '[style.width]': 'width()',
    '(focus)': 'onFocus()',
  },
  template: `
    @if (labelled()) {
      <span [class]="styles().cardLabel()">{{ column().header }}</span>
    }
    <span [class]="valueClass()"><ng-content /></span>
  `,
})
export class TableCell {
  private readonly table = inject(TableState);
  private readonly row = inject(TableRowState);

  protected readonly columnIndex = computed(() => this.row.columnIndexOf(this));

  protected readonly column = computed(() => this.table.columns()[this.columnIndex()] ?? PLAIN);

  protected readonly narrow = computed(() => this.table.narrow());

  protected readonly styles = computed(() => tableCellStyles({ narrow: this.narrow() }));

  protected readonly labelled = computed(() => this.narrow() && this.column().mobileLayout !== 'block');

  protected readonly role = computed(() => (this.narrow() ? null : 'gridcell'));

  protected readonly width = computed(() => (this.narrow() ? null : this.column().width ?? null));

  protected readonly tabIndex = computed(() => {
    if (this.narrow()) return null;
    return this.table.isStop(this.row.index(), this.columnIndex()) ? 0 : -1;
  });

  protected readonly cellClass = computed(() => {
    const column = this.column();
    if (this.narrow()) {
      const styles = tableCellStyles({ narrow: true });
      return column.mobileLayout === 'block' ? styles.cardBlock() : styles.cardRow();
    }
    const styles = tableCellStyles({ narrow: false, align: column.align ?? 'left' });
    return column.mono ? styles.tdMono() : styles.td();
  });

  protected readonly valueClass = computed(() => {
    if (!this.narrow() || this.column().mobileLayout === 'block') return '';
    const styles = tableCellStyles({ narrow: true });
    return this.column().mono ? styles.cardValueMono() : styles.cardValue();
  });

  protected onFocus(): void {
    if (this.narrow()) return;
    this.table.cursor.set({ row: this.row.index(), col: this.columnIndex() });
  }
}
